import { describe, it, expect } from 'vitest';
import { generateFullLeague } from '../simulation/leagueGenerator';
import { initializeCoaching, staffMembers, hireStaff, fireStaff, staffOfferAssessment, teachingQuality, promoteStaff, advanceStaffSeason } from '../simulation/staffManagement';
import { prepareCoachingForGame, setDevelopmentPlan, setPlayerProject, discussRole, badgeRequirements, finishCoachingGame, initialTraining } from '../simulation/playerDevelopment';
import { DEFAULT_COACHING_SETTINGS } from '../simulation/coachingModel';
import { simulateNextGame } from '../simulation/league';
import { beginNewSeasonRoster } from '../simulation/seasonTransition';
import { emptySeasonStatTotals } from '../simulation/types';
import { buildSnapshot, parseUniverseFile } from '../storage/universeIO';
import { developOffseasonPlayer } from '../simulation/engine/development';
import { RNG } from '../simulation/engine/rng';
import { calculateOverall } from '../simulation/engine/overall';
import { applyCoachingPlan } from '../simulation/engine/coachingPlan';
import { computeRuleMods } from '../simulation/engine/ruleMods';
import { defaultCoachTendencies } from '../simulation/league';
import { computeTeamFinances } from '../simulation/finances';
const fixture=()=>{const f=generateFullLeague(4242,4,12,12,'2026',{priorSeasons:false});return {...f,league:initializeCoaching(f.league,f.league.teams[0].teamId)}};

describe('coaching migration, market and careers',()=>{
 it('adds five staff roles and saved plans without replacing old identities, and is idempotent',()=>{const f=generateFullLeague(42,4,12,12,'2026',{priorSeasons:false});const old=JSON.stringify(f.league);const l=initializeCoaching(f.league,f.league.teams[0].teamId);expect(JSON.stringify(f.league)).toBe(old);expect(l.teams.every(t=>staffMembers(t).length===5)).toBe(true);expect(l.teams[0].coachIdentity?.coachId).toBe(f.league.teams[0].coachIdentity?.coachId);expect(initializeCoaching(l)).toEqual(l);expect(l.teams[0].coachingControl?.staffAuto).toBe(false);expect(l.teams[1].coachingControl?.staffAuto).toBe(true)});
 it('preserves plans, market and history through portable save round trips',()=>{const {league,extras}=fixture();const snapshot=parseUniverseFile(JSON.stringify(buildSnapshot(league,extras)));expect(snapshot.league).toEqual(league);expect(snapshot.league.staffMarket?.length).toBe(30)});
 it('guards ownership, rejects impossible offers, pays out replaced contracts and removes hired candidates',()=>{let {league}=fixture();const t=league.teams[0],candidate=league.staffMarket![0];expect(hireStaff(league,t.teamId,candidate.coachId,'head',1,3,'other').league).toBe(league);expect(staffOfferAssessment(t,candidate,'head',1,3,league).accepted).toBe(false);league={...league,coachingSettings:{...DEFAULT_COACHING_SETTINGS,staffBudgetRestrictions:false}};const hired=hireStaff(league,t.teamId,candidate.coachId,'head',candidate.contract.annualSalary*3,5,t.teamId);expect(hired.league).not.toBe(league);expect(hired.league.teams[0].coachingControl?.payout).toBe(t.coachIdentity!.contract.annualSalary*t.coachIdentity!.contract.yearsRemaining);expect(hired.league.staffMarket?.some(c=>c.coachId===candidate.coachId)).toBe(false);expect(hireStaff(hired.league,t.teamId,candidate.coachId,'head',1e7,3,t.teamId).league).toBe(hired.league)});
 it('permits vacancies and reflects firing costs in finances',()=>{const {league,extras}=fixture(),t=league.teams[0];const before=computeTeamFinances(t,extras.contracts,extras.capSettings,undefined,.5);const fired=fireStaff(league,t.teamId,'offense',t.teamId).league;expect(fired.teams[0].staff?.offense).toBeUndefined();expect(initializeCoaching(fired).teams[0].staff?.offense).toBeUndefined();const after=computeTeamFinances(fired.teams[0],extras.contracts,extras.capSettings,undefined,.5);expect(after.operatingIncome).toBeLessThanOrEqual(before.operatingIncome);expect(fireStaff(fired,t.teamId,'offense',t.teamId).league).toBe(fired)});
 it('can promote an assistant without employing the same coach twice',()=>{let {league}=fixture();league={...league,coachingSettings:{...DEFAULT_COACHING_SETTINGS,staffBudgetRestrictions:false}};const t=league.teams[0],c=t.staff!.development!;const r=promoteStaff(league,t.teamId,c.coachId,c.contract.annualSalary*5,5,t.teamId);expect(r.league.teams[0].coachIdentity?.coachId).toBe(c.coachId);expect(r.league.teams[0].staff?.development).toBeUndefined();expect(staffMembers(r.league.teams[0]).filter(s=>s.coach.coachId===c.coachId)).toHaveLength(1)});
 it('distinguishes teaching from strategy and advances coach careers on rollover',()=>{const {league}=fixture(),t=league.teams[0];t.coachingControl!.staffAuto=false;const teacher=t.staff!.development!;teacher.profile!.attributes.teaching=10;const weak=teachingQuality(t);teacher.profile!.attributes.teaching=95;expect(teachingQuality(t)).toBeGreaterThan(weak);t.coachIdentity!.contract.yearsRemaining=2;const next=advanceStaffSeason({...league,season:'2027'},'2026',t.teamId,t.coachIdentity!.coachId);expect(next.teams[0].coachIdentity!.age).toBe(t.coachIdentity!.age+1);expect(next.teams[0].coachIdentity!.contract.yearsRemaining).toBe(1);expect(next.teams[0].coachIdentity!.profile!.coyAwards).toBe(1);expect(next.teams[0].coachIdentity!.championships).toBe(t.coachIdentity!.championships+1)});
});
describe('training, workload and persistent experience',()=>{
 it('ticks practice by date once, not by opening pages or by number of league games',()=>{const {league}=fixture(),id=league.teams[0].teamId;const old=JSON.stringify(league);const first=prepareCoachingForGame(league,[id],'2026-10-22');const second=prepareCoachingForGame(first,[id],'2026-10-29');expect(JSON.stringify(league)).toBe(old);expect(second.teams[0].coachingControl!.practiceDays).toBe(8);expect(second.teams[1].coachingControl!.practiceDays).toBe(0);expect(prepareCoachingForGame(second,[id],'2026-10-29').teams[0].coachingControl!.practiceDays).toBe(8);expect(second.teams[0].coachingControl!.reports.some(r=>r.kind==='weekly')).toBe(true)});
 it('manual hard sessions create more fatigue than recovery and protect injured players',()=>{const {league}=fixture(),t=league.teams[0],id=t.teamId,p=t.seasons[0];t.coachingControl!.practiceAuto=false;t.coachingControl!.lastPracticeDate='2026-10-20';const hard=structuredClone(league),rest=structuredClone(league);hard.teams[0].coachingControl!.practice=Array(7).fill({type:'skills',intensity:'hard'});rest.teams[0].coachingControl!.practice=Array(7).fill({type:'recovery',intensity:'light'});const h=prepareCoachingForGame(hard,[id],'2026-10-25'),r=prepareCoachingForGame(rest,[id],'2026-10-25');expect(h.teams[0].seasons[0].training!.workload).toBeGreaterThan(r.teams[0].seasons[0].training!.workload);hard.injuries={[p.playerId]:{playerId:p.playerId,teamId:id,severity:'moderate',gamesRemaining:10,totalGames:10}};const injured=prepareCoachingForGame(hard,[id],'2026-10-25').teams[0].seasons[0];expect(injured.attributes).toEqual(p.attributes);expect(injured.training!.injuredDays).toBe(5)});
 it('limits mentors to two eligible teammates and rejects other-team plans',()=>{const {league}=fixture(),t=league.teams[0],mentor=t.seasons[0];mentor.age=35;for(const p of t.seasons.slice(1,4))p.age=20;let l=league;for(const p of t.seasons.slice(1,3))l=setDevelopmentPlan(l,p.playerId,{mentorId:mentor.playerId},t.teamId).league;const third=setDevelopmentPlan(l,t.seasons[3].playerId,{mentorId:mentor.playerId},t.teamId);expect(third.league).toBe(l);expect(third.message).toContain('at most two');expect(setDevelopmentPlan(l,t.seasons[1].playerId,{primary:'midrange'},'other').league).toBe(l)});
 it('preserves real gains when cancelling a project and retains familiarity across system changes',()=>{const {league}=fixture(),t=league.teams[0],p=t.seasons[0];let l=setPlayerProject(league,p.playerId,'corner-three',t.teamId);l=prepareCoachingForGame(l,[t.teamId],'2026-10-22');l=prepareCoachingForGame(l,[t.teamId],'2026-11-22');const developed=l.teams[0].seasons[0];expect(developed.training!.project!.progress).toBeGreaterThan(0);const before=structuredClone(developed.attributes);l=setPlayerProject(l,p.playerId,null,t.teamId);expect(l.teams[0].seasons[0].attributes).toEqual(before);l.teams[0].coach!.offensiveSystem='motion';const changed=prepareCoachingForGame(l,[t.teamId],'2026-11-24').teams[0].seasons[0];expect(changed.training!.familiarity['offense:motion']).toBeGreaterThan(12);expect(Object.keys(changed.training!.familiarity).length).toBeGreaterThanOrEqual(3)});
 it('records actual minutes and possessions, not planned targets',()=>{const {league}=fixture();const next=simulateNextGame(league,424);const game=next.schedule.find(g=>g.played)!.result!;for(const t of next.teams.filter(t=>[game.homeTeamId,game.awayTeamId].includes(t.teamId)))for(const p of t.seasons){const box=t.teamId===game.homeTeamId?game.homeBox:game.awayBox;expect(p.training!.evidence.minutes).toBeCloseTo(box.players[p.playerId]?.minutes??0,6)}expect(next.teams.find(t=>t.teamId===game.homeTeamId)!.seasons.reduce((n,p)=>n+p.training!.evidence.handling,0)).toBeGreaterThan(0)});
 it('does not award shooting badges for inefficient volume or experimental badges from training',()=>{const {league}=fixture(),p=league.teams[0].seasons[0];p.attributes.offense.catchAndShoot=95;p.attributes.offense.corner3=95;p.seasonStats={...emptySeasonStatTotals(),gamesPlayed:40,minutes:1000};p.training!.evidence={games:40,minutes:1000,handling:400,defensiveReps:1000,shots:{catchAndShoot3:{attempts:400,makes:60}}};expect(badgeRequirements(p,'catch_and_shoot').eligible).toBe(false);p.training!.evidence.shots.catchAndShoot3.makes=180;expect(badgeRequirements(p,'catch_and_shoot').eligible).toBe(true);expect(badgeRequirements(p,'perfect_shooter').eligible).toBe(false)});
 it('starts measurable promises, prevents repeated conversation farming and evaluates fulfillment',()=>{const {league}=fixture(),t=league.teams[0],p=t.seasons[0];const promised=discussRole(league,p.playerId,'compete',t.teamId).league;expect(promised.teams[0].seasons[0].training!.promise?.required).toBe(4);expect(discussRole(promised,p.playerId,'compete',t.teamId).league).toBe(promised);let l=simulateNextGame(promised,411);const game=l.schedule.find(g=>g.played)!.result!;const player=l.teams.flatMap(t=>t.seasons).find(s=>s.playerId===p.playerId)!;if([game.homeTeamId,game.awayTeamId].includes(t.teamId)){player.training!.promise={kind:'rotation',remaining:1,achieved:0,required:4,failures:0};l=finishCoachingGame(l,game);expect(l.teams.flatMap(t=>t.seasons).find(s=>s.playerId===p.playerId)!.training!.brokenPromises).toBe(1)}});
 it('keeps offseason history and staff contracts through the real transition',()=>{const {league,extras}=fixture(),id=league.teams[0].seasons[0].playerId;league.teams[0].seasons[0].age=21;const next=beginNewSeasonRoster(league,extras,77).league;const p=next.teams.flatMap(t=>t.seasons).find(p=>p.playerId===id)??next.retiredPlayers?.find(p=>p.playerId===id)?.finalSeasonData;expect(p?.training?.history.some(h=>h.kind==='offseason'&&h.changes)).toBe(true);expect(next.teams[0].coachingControl!.reports.some(r=>r.kind==='offseason')).toBe(true);expect(next.season).toBe('2027')});
});
describe('basketball and development tradeoffs',()=>{
 it('motion rewards familiarity and switching exposes slow defenders',()=>{const {league}=fixture(),roster=league.teams[0].seasons,off={...defaultCoachTendencies(),offensiveSystem:'motion' as const},def={...defaultCoachTendencies(),defensiveScheme:'switch' as const};const base=computeRuleMods(undefined);const low=structuredClone(roster),high=structuredClone(roster);for(const p of low){p.training!.familiarity['offense:motion']=10;p.attributes.physical.agility=25;}for(const p of high){p.training!.familiarity['offense:motion']=95;p.attributes.physical.agility=95;}const weak=applyCoachingPlan(base,off,def,undefined,undefined,low,low),strong=applyCoachingPlan(base,off,def,undefined,undefined,high,high);expect(strong.shot.offensiveEfficiency).toBeGreaterThan(weak.shot.offensiveEfficiency);expect(strong.shot.closeoutEffectiveness).toBeGreaterThan(weak.shot.closeoutEffectiveness)});
 it('excessive minutes do not maximize growth and high work ethic helps over seeded trials',()=>{const {league}=fixture(),p=league.teams[0].seasons[0];p.age=20;p.development.potential=95;p.development.peakAge=27;let moderate=0,excessive=0,lazy=0;for(let seed=0;seed<32;seed++){const a=structuredClone(p),b=structuredClone(p),c=structuredClone(p);a.seasonStats={...emptySeasonStatTotals(),gamesPlayed:82,minutes:82*28};b.seasonStats={...emptySeasonStatTotals(),gamesPlayed:82,minutes:82*44};c.seasonStats=a.seasonStats;a.development.workEthic=95;b.development.workEthic=95;c.development.workEthic=10;moderate+=calculateOverall(developOffseasonPlayer(a,new RNG(seed)));excessive+=calculateOverall(developOffseasonPlayer(b,new RNG(seed)));lazy+=calculateOverall(developOffseasonPlayer(c,new RNG(seed)));}expect(moderate).toBeGreaterThan(excessive);expect(moderate).toBeGreaterThan(lazy)});
 it('keeps uncapped sandbox potential for young players, ties it to overall in decline, and separates late skill development from physical decline',()=>{const {league}=fixture(),p=league.teams[0].seasons[0];p.age=38;p.development.potential=150;p.development.peakAge=25;p.development.primeLengthYears=5;p.training=initialTraining(p,league.teams[0]);const next=developOffseasonPlayer(p,new RNG(40),undefined,1,'balanced',200);expect(next.development.potential).toBe(calculateOverall(next));expect(next.attributes.physical.speed).toBeLessThan(p.attributes.physical.speed);expect(next.attributes.offense.passingIQ).toBeGreaterThanOrEqual(p.attributes.offense.passingIQ);const young={...league.teams[0].seasons[1],age:19,development:{...league.teams[0].seasons[1].development,potential:150,peakAge:26}};expect(developOffseasonPlayer(young,new RNG(41),undefined,1,'balanced',200).development.potential).toBeGreaterThan(100)});
});
