import { systemFitReport } from '../simulation/coachingSystems';
import { enrichCoach } from '../simulation/staffManagement';
import { TeamLink } from './TeamLink';
import { rotationReviewInterval } from '../simulation/rotationReview';
import { formatPlayingTime } from '../simulation/boxscore';
import { useState } from 'react';
import type { League, CoachTendencies } from '../simulation/league';
import { defaultCoachTendencies } from '../simulation/league';
import { relationshipLabel, relationshipWith, COACH_TRAIT_LABELS } from '../simulation/coaching';
import { PlayerNameTag } from './PlayerAvatar';

const SYSTEM_NOTES = {
  isolation: 'Feeds elite individual creators. Fewer assisted chances and more fatigue for the primary scorer.',
  balanced: 'A balanced mix of actions. Use the tendency sliders to shape your offense.',
  'pace-space': 'More threes and transition possessions. Best suited to shooters and a deep rotation.',
  'pick-roll': 'More pick-and-roll actions. Passing and ball handling help your creators make the right read.',
  post: 'More post possessions and fewer threes. Feed skilled interior scorers.',
  motion: 'Fewer isolations and more assisted baskets. Keep the ball moving.',
};
const DEFENSE_NOTES = {
  drop: 'Protects the paint and rim, but gives pull-up shooters space.',
  man: 'Standard matchup defense with no scheme bonus or penalty.',
  switch: 'Improves pick-and-roll coverage and closeouts, with weaker interior coverage.',
  zone: 'Stronger interior coverage, with slower perimeter closeouts.',
  pressure: 'Creates more steal chances but also commits more fouls.',
};
export function CoachingPage({ league, controlledTeamId, onChange, onOpenRoster, onOpenStaff, onOpenDevelopment, sandboxMode = false }: { onOpenStaff?:()=>void; onOpenDevelopment?:()=>void; sandboxMode?: boolean; league: League; controlledTeamId?: string | null; onChange: (league: League) => void; onOpenRoster: () => void }) {
  const [teamId, setTeamId] = useState(controlledTeamId ?? league.teams[0]?.teamId ?? '');
  const team = sandboxMode ? league.teams.find(t => t.teamId === teamId) ?? league.teams[0] : league.teams.find(t => t.teamId === controlledTeamId);
  if (!team) return <p className="empty-state">Control a team to manage its coaches. You can inspect other coaching staffs through team profiles, or enable Sandbox Mode to manage them.</p>;
  const coach = team.coachIdentity;
  const plan = { ...defaultCoachTendencies(), ...team.coach };
  const update = (patch: Partial<CoachTendencies>) => onChange({ ...league, teams: league.teams.map(t => t.teamId === team.teamId ? { ...t, coach: { ...plan, ...patch } } : t) });
  const profile = coach ? enrichCoach(coach, 'head').profile : undefined;
  const total = team.seasons.reduce((n, s) => n + s.minutes.target, 0);
  const budget = league.settings.era.quarterLengthMinutes * league.settings.era.numberOfQuarters * 5;
  const dials = [['paceTendency', 'Tempo'], ['threePointFrequency', 'Three-point emphasis'], ['starUsage', 'Star / closing usage'], ['benchUsage', 'Bench usage'], ['defensiveAggression', 'Defensive aggression'], ['doubleTeamFrequency', 'Double teams'], ['pnrFrequency', 'Pick-and-roll frequency'], ['postFrequency', 'Post frequency']] as const;
  return <div className="coaching-page"><div className="season-feature-header"><div><span className="pixel-eyebrow">THE COACH'S OFFICE</span><h2>Coaching & Game Plan</h2><p><TeamLink name={team.name} /></p><p>Shape the rotation, prepare your offense, and develop your roster.</p></div>{sandboxMode && <label>Team<select aria-label="Coaching team" value={team.teamId} onChange={e => setTeamId(e.target.value)}>{league.teams.map(t => <option key={t.teamId} value={t.teamId}>{t.name}</option>)}</select></label>}</div>
    <section className="coaching-identity"><div><h3>{coach?.coachId ?? 'Interim coaching staff'}</h3><p className="hint-text">{coach ? `Rating ${coach.rating} · ${coach.careerWins}–${coach.careerLosses} career · ${coach.contract.yearsRemaining} years left` : 'Hire a head coach from the roster page.'}</p><button onClick={onOpenRoster}>Roster & Coach Market</button></div>{coach && <div className="coaching-trait-grid">{Object.entries(coach.traits).map(([key, value]) => <div key={key}><span>{COACH_TRAIT_LABELS[key as keyof typeof COACH_TRAIT_LABELS]}</span><meter min="0" max="99" value={value} /><strong>{value}</strong></div>)}</div>}</section>
    <p>{systemFitReport(team)}</p><div className="code-mode-actions">{onOpenStaff&&<button onClick={onOpenStaff}>Staff & Contracts</button>}{onOpenDevelopment&&<button onClick={onOpenDevelopment}>Practice, Rotations & Development</button>}</div>
    <div className="feature-stat-grid"><div><small>OFFENSIVE STRATEGY</small><strong>{coach?.traits.offense.toFixed(0)??'—'}</strong></div><div><small>DEFENSIVE STRATEGY</small><strong>{coach?.traits.defense.toFixed(0)??'—'}</strong></div><div><small>TEACHING</small><strong>{profile?.attributes.teaching.toFixed(0)??'—'}</strong></div><div><small>ADJUSTMENTS</small><strong>{profile?.attributes.adjustments.toFixed(0)??'—'}</strong></div></div>
    <div className="coaching-systems"><section><h3>Offensive system</h3><label>System<select aria-label="System" value={plan.offensiveSystem ?? 'balanced'} onChange={e => update({ offensiveSystem: e.target.value as CoachTendencies['offensiveSystem'] })}><option value="balanced">Balanced</option><option value="pace-space">Pace & Space</option><option value="pick-roll">Pick & Roll</option><option value="post">Post Centric</option><option value="motion">Motion</option><option value="isolation">Isolation</option></select></label><p className="hint-text">{SYSTEM_NOTES[plan.offensiveSystem ?? 'balanced']}</p></section><section><h3>Defensive coverage</h3><label>Scheme<select aria-label="Scheme" value={plan.defensiveScheme ?? 'man'} onChange={e => update({ defensiveScheme: e.target.value as CoachTendencies['defensiveScheme'] })}><option value="man">Conservative Man to Man</option><option value="drop">Drop Coverage</option><option value="switch">Switch</option><option value="zone">Zone</option><option value="pressure">Pressure</option></select></label><p className="hint-text">{DEFENSE_NOTES[plan.defensiveScheme ?? 'man']}</p></section><section><h3>Player development</h3><label>Training focus<select aria-label="Training focus" value={plan.trainingFocus ?? 'balanced'} onChange={e => update({ trainingFocus: e.target.value as CoachTendencies['trainingFocus'] })}><option value="balanced">Balanced</option><option value="shooting">Shooting</option><option value="defense">Defense</option><option value="playmaking">Playmaking</option></select></label><p className="hint-text">Specialized training shifts offseason growth toward the chosen skills. Age, potential, minutes and coaching quality still matter.</p></section></div>
    <section><h3>Rotation management</h3><div className="coaching-systems"><label>Rotation depth<strong>{plan.rotationDepth ?? 10} players</strong><input aria-label="Rotation depth" type="range" min="5" max="15" value={plan.rotationDepth ?? 10} onChange={e => update({ rotationDepth: +e.target.value })} /></label><label>Preferred stint<strong>{plan.stintLengthMinutes ?? league.rulesSettings?.rotationStintMinutes ?? 5} minutes</strong><input aria-label="Preferred stint" type="range" min="2" max="8" step="0.5" value={plan.stintLengthMinutes ?? league.rulesSettings?.rotationStintMinutes ?? 5} onChange={e => update({ stintLengthMinutes: +e.target.value })} /><button className="link-button" onClick={() => update({ stintLengthMinutes: undefined })}>Use league default</button></label><div><small>PLANNED / AVAILABLE MINUTES</small><strong className="rotation-budget">{total.toFixed(0)} / {budget}</strong><p className="hint-text">Flexible targets scale to the available clock. EXACT budgets take priority when possible. Fouls and injuries can override a plan.</p></div></div><p className="hint-text">Depth applies to AI minutes. Manual minute settings remain eligible. Players rotate during quarters; starters close tight games and the bench gets more time in blowouts.</p></section>
    <section className="rotation-reviews"><h3>Performance reviews</h3><div className="coaching-dials"><label><span><input type="checkbox" checked={plan.autoRotation !== false} onChange={e => update({ autoRotation: e.target.checked })} /> Let the coach adjust AI rotations</span></label><label>Review every<select aria-label="Rotation review interval" value={rotationReviewInterval(team)} onChange={e => update({ rotationReviewInterval: +e.target.value })}>{[5,6,7,8,9,10].map(n => <option key={n} value={n}>{n} team games</option>)}</select></label></div><p className="hint-text">Production, efficiency, workload and system fit guide gradual minute changes and starting spots. At least three appearances are required. Only AI minutes and their roles can change; TARGET, EXACT and MANUAL plans are protected. Injured players are not penalized for missing games.</p>
      {team.rotationReview?.season === (league.season ?? team.seasons[0]?.season ?? '') ? <div><p><strong>After game {team.rotationReview.gamesReviewed}</strong> · {team.rotationReview.summary}</p>{team.rotationReview.changes.length > 0 && <div className="rotation-change-list">{team.rotationReview.changes.map(change => <article key={change.playerId}><PlayerNameTag playerId={change.playerId} teamId={team.teamId} /><strong>{formatPlayingTime(change.fromMinutes)} → {formatPlayingTime(change.toMinutes)}</strong><p>{change.reason}</p></article>)}</div>}</div> : <p className="hint-text">First review after {rotationReviewInterval(team)} completed regular-season games.</p>}
    </section>
    <section><h3>Tactical tendencies</h3><div className="coaching-dials">{dials.map(([key, label]) => <label key={key}>{label}<strong>{plan[key]}</strong><input type="range" min="0" max="100" value={plan[key]} onChange={e => update({ [key]: +e.target.value })} /></label>)}</div></section>
    <section><h3>Locker-room relationships</h3><p className="hint-text">Wins, motivation and playing time change buy-in after every game. Buy-in affects offensive and defensive execution.</p><div className="relationship-grid">{team.seasons.map(s => <div key={s.playerId}><PlayerNameTag playerId={s.playerId} teamId={team.teamId} size={28} /><span>{relationshipLabel(relationshipWith(coach, s.playerId))}</span><strong>{Math.round(relationshipWith(coach, s.playerId))}</strong></div>)}</div></section>
  </div>;
}
