import { useState } from 'react';
import type { League, LeagueTeam, CoachTendencies } from '../simulation/league';
import { defaultCoachTendencies } from '../simulation/league';
import { DEFAULT_COACHING_SETTINGS, PRACTICE_TYPES, type CoachingControl, type RotationPolicy, type PracticeSession } from '../simulation/coachingModel';
import { newControl } from '../simulation/staffManagement';
import { practicePreview } from '../simulation/playerDevelopment';
import { systemFitReport } from '../simulation/coachingSystems';
import { TeamLink } from './TeamLink';
import { DevelopmentRoster } from './PlayerDevelopmentPanel';
import { realDevelopmentOn } from '../simulation/realDevelopmentGate';

export function RotationControls({team,onChange,gameMinutes}:{team:LeagueTeam;onChange:(t:LeagueTeam)=>void;gameMinutes:number}){
 const policy:RotationPolicy=team.coach?.rotationPolicy??{mode:'performance',starters:[],closing:[],smallBall:[],defensive:[],allowStarterChanges:true,allowOverrides:true};
 const update=(patch:Partial<RotationPolicy>)=>onChange({...team,coach:{...defaultCoachTendencies(),...team.coach,rotationPolicy:{...policy,...patch},...(patch.mode?{autoRotation:patch.mode!=='fixed'}:{})}});
 const toggle=(key:'starters'|'closing'|'smallBall'|'defensive',id:string)=>{const ids=policy[key];if(!ids.includes(id)&&ids.length>=5)return;update({[key]:ids.includes(id)?ids.filter(s=>s!==id):[...ids,id]})};
 return <section className="rotation-policy"><h3>Rotation Authority & Lineups</h3><div className="development-controls"><label>Rotation style<select aria-label="Rotation style" value={policy.mode} onChange={e=>update({mode:e.target.value as RotationPolicy['mode']})}>{['fixed','performance','development','matchup','playoff'].map(m=><option key={m}>{m}</option>)}</select></label><label>Backup ball handler<select aria-label="Backup ball handler" value={policy.backupHandler??''} onChange={e=>update({backupHandler:e.target.value||undefined})}><option value="">Coach decides</option>{team.seasons.map(p=><option key={p.playerId}>{p.playerId}</option>)}</select></label><label><input type="checkbox" checked={policy.allowStarterChanges} onChange={e=>update({allowStarterChanges:e.target.checked})}/> Coach may change unlocked starters</label><label><input type="checkbox" checked={policy.allowOverrides} onChange={e=>update({allowOverrides:e.target.checked})}/> Fatigue and foul-trouble adjustments</label></div>
 <p className="hint-text">Choose up to five players per lineup. Empty slots use the coach’s rotation. Preferred starters are protected from automatic reviews. EXACT, TARGET and MANUAL minute plans are never rewritten by reviews. Injuries, disqualification and impossible five-player budgets still require substitutions.</p>
 <div className="feature-table-scroll"><table className="db-table"><thead><tr><th>Player</th><th>Starter</th><th>Closing</th><th>Small ball</th><th>Defense</th><th>Minutes mode</th><th>Target</th><th>Min</th><th>Max</th></tr></thead><tbody>{team.seasons.map(p=>{const setMinutes=(patch:Partial<typeof p.minutes>)=>onChange({...team,seasons:team.seasons.map(s=>s.playerId===p.playerId?{...s,minutes:{...s.minutes,...patch}}:s)});return <tr key={p.playerId}><td>{p.playerId}</td>{(['starters','closing','smallBall','defensive'] as const).map(k=><td key={k}><input type="checkbox" aria-label={`${p.playerId} ${k}`} checked={policy[k].includes(p.playerId)} disabled={!policy[k].includes(p.playerId)&&policy[k].length>=5} onChange={()=>toggle(k,p.playerId)}/></td>)}<td><select aria-label={`${p.playerId} minutes mode`} value={p.minutes.mode} onChange={e=>setMinutes({mode:e.target.value as typeof p.minutes.mode})}>{['AI','TARGET','EXACT','MANUAL'].map(m=><option key={m}>{m}</option>)}</select></td>{(['target','min','max'] as const).map(k=><td key={k}><input className="rotation-minute-input" aria-label={`${p.playerId} ${k} minutes`} type="number" min="0" max={gameMinutes} step="0.5" value={p.minutes[k]??(k==='max'?gameMinutes:0)} onChange={e=>setMinutes({[k]:Math.max(0,Math.min(gameMinutes,+e.target.value))})}/></td>)}</tr>})}</tbody></table></div></section>;
}
export function DevelopmentCenterPage({league,controlledTeamId,sandboxMode,onChange,onSelectPlayer}:{league:League;controlledTeamId:string|null;sandboxMode:boolean;onChange:(l:League)=>void;onSelectPlayer:(id:string)=>void}){
 const [selectedTeam,setSelectedTeam]=useState(controlledTeamId??league.teams[0]?.teamId??''),[tab,setTab]=useState('plans'),[reportCount,setReportCount]=useState(12);
 const team=league.teams.find(t=>t.teamId===(sandboxMode?selectedTeam:controlledTeamId));
 if(!team)return <p className="empty-state">Control a team to manage its development. Player development histories remain available through their profiles.</p>;
 const control=team.coachingControl??newControl(true),updateTeam=(t:LeagueTeam)=>onChange({...league,teams:league.teams.map(old=>old.teamId===team.teamId?t:old)}),update=(patch:Partial<CoachingControl>)=>updateTeam({...team,coachingControl:{...control,...patch}});
 const preset=(value:CoachingControl['preset'])=>update({preset:value,staffAuto:value==='simple',practiceAuto:value!=='deep',developmentAuto:value==='simple'});
 const setPractice=(i:number,patch:Partial<PracticeSession>)=>update({practice:control.practice.map((p,index)=>index===i?{...p,...patch}:p)});
 return <div className="development-center"><div className="season-feature-header" data-tour="development"><div><span className="pixel-eyebrow">BUILD THE NEXT GENERATION</span><h2>Player Development</h2><TeamLink teamId={team.teamId}/></div>{sandboxMode&&<label>Development team<select aria-label="Development team" value={team.teamId} onChange={e=>setSelectedTeam(e.target.value)}>{league.teams.map(t=><option key={t.teamId} value={t.teamId}>{t.name}</option>)}</select></label>}</div>
 <p>{systemFitReport(team)}</p>
 {realDevelopmentOn(league)&&<p className="real-dev-note" role="note"><strong>Real Player Development is on.</strong> Real NBA players’ ratings follow their real season-by-season reference and change only at the season rollover. Practice, plans, coaches, mentors, projects and minutes still drive workload, recovery, morale, system and role familiarity — not their ratings. Fictional players develop normally. Change this in League Settings → League Rules.</p>}<div className="code-mode-actions" role="group" aria-label="Development sections">{['plans','practice','rotations','reports','automation'].map(t=><button key={t} className={tab===t?'active':''} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>
 {tab==='plans'&&<><p>Open a player’s Development tab to set focuses, assign a coach or mentor, start a project and discuss roles.</p><DevelopmentRoster league={league} teamId={team.teamId} onSelectPlayer={onSelectPlayer}/></>}
 {tab==='practice'&&<section><h3>Weekly Practice Planner</h3><label><input type="checkbox" checked={control.practiceAuto} onChange={e=>update({practiceAuto:e.target.checked})}/> Auto Practice</label><p className="hint-text">Auto Practice chooses recovery after recent games or high workload, film on game days and during playoffs, and harder work during long breaks. Injured players receive restricted training. The custom week is used when Auto Practice is off.</p><div className="feature-table-scroll"><table className="db-table"><thead><tr><th>Day</th><th>Practice</th><th>Intensity</th><th>Expected effect</th></tr></thead><tbody>{control.practice.map((p,i)=><tr key={i}><td>{['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][i]}</td><td><select aria-label={`Day ${i+1} practice`} disabled={control.practiceAuto} value={p.type} onChange={e=>setPractice(i,{type:e.target.value as PracticeSession['type']})}>{PRACTICE_TYPES.map(k=><option key={k}>{k}</option>)}</select></td><td><select aria-label={`Day ${i+1} intensity`} disabled={control.practiceAuto} value={p.intensity} onChange={e=>setPractice(i,{intensity:e.target.value as PracticeSession['intensity']})}>{['light','normal','hard'].map(k=><option key={k}>{k}</option>)}</select></td><td>{practicePreview(p)}</td></tr>)}</tbody></table></div><p>Changes save immediately and apply on upcoming calendar days. {control.practiceDays} practice days completed; last practice {control.lastPracticeDate??'not yet started'}.</p></section>}
 {tab==='rotations'&&<RotationControls team={team} onChange={updateTeam} gameMinutes={league.settings.era.numberOfQuarters*league.settings.era.quarterLengthMinutes}/>}
 {tab==='reports'&&<section><h3>Coaching Reports</h3>{!control.reports.length?<p>Weekly and monthly reports arrive as calendar days pass. Offseason reports appear after the season transition. Permanent changes also remain in each player’s career history.</p>:control.reports.slice(0,reportCount).map((r,i)=><details className="coaching-report" key={i} open={i===0}><summary>{r.date} · {r.season} · {r.kind}</summary><p>{r.summary}</p><ul>{r.items.map((text,j)=><li key={j}>{text}</li>)}</ul></details>)}{control.reports.length>reportCount&&<button onClick={()=>setReportCount(n=>n+12)}>Older Reports</button>}</section>}
 {tab==='automation'&&<section><h3>Management Depth</h3><label>Preset<select aria-label="Management preset" value={control.preset} onChange={e=>preset(e.target.value as CoachingControl['preset'])}><option value="simple">Simple</option><option value="standard">Standard</option><option value="deep">Deep</option></select></label><p>Simple delegates staff, practice and plans. Standard keeps staff and player focuses in your hands. Deep adds manual practice planning. Individual switches can override any preset.</p><div className="development-controls">{([['staffAuto','Automatic staff management'],['practiceAuto','Auto Practice'],['developmentAuto','Automatic development plans']] as const).map(([key,label])=><label key={key}><input type="checkbox" checked={control[key]} onChange={e=>update({[key]:e.target.checked})}/>{label}</label>)}<label>Team direction<select aria-label="Team direction" value={control.direction} onChange={e=>{const direction=e.target.value as CoachingControl['direction'];const coach:CoachTendencies={...defaultCoachTendencies(),...team.coach,rotationPolicy:{starters:[],closing:[],smallBall:[],defensive:[],allowStarterChanges:true,allowOverrides:true,...team.coach?.rotationPolicy,mode:direction==='rebuild'?'development':direction==='contend'?'playoff':'performance'}};updateTeam({...team,coach,coachingControl:{...control,direction}})}}><option value="balanced">Balanced</option><option value="contend">Contend</option><option value="rebuild">Rebuild</option></select></label></div></section>}
 </div>;
}
export function CoachingSettingsPanel({league,onChange}:{league:League;onChange:(l:League)=>void}){
 const settings={...DEFAULT_COACHING_SETTINGS,...league.coachingSettings};
 return <section><h3>Coaching & Development Controls</h3><p>These league-wide rules apply equally to user and AI teams. Development speed, randomness and coaching impact use the existing League Rules sliders.</p><div className="development-controls">{([['familiaritySpeed','System familiarity speed'],['mentorshipImpact','Mentorship impact'],['moraleImpact','Morale impact'],['trainingFatigue','Training fatigue']] as const).map(([key,label])=><label key={key}>{label} ({settings[key]}%)<input aria-label={label} type="range" min="0" max="200" value={settings[key]} onChange={e=>onChange({...league,coachingSettings:{...settings,[key]:+e.target.value}})}/></label>)}<label><input type="checkbox" checked={settings.staffBudgetRestrictions} onChange={e=>onChange({...league,coachingSettings:{...settings,staffBudgetRestrictions:e.target.checked}})}/> Staff budget restrictions</label><label>Detailed report frequency<select aria-label="Detailed report frequency" value={settings.reportFrequency} onChange={e=>onChange({...league,coachingSettings:{...settings,reportFrequency:e.target.value as typeof settings.reportFrequency}})}><option value="weekly">Weekly + monthly + offseason</option><option value="monthly">Monthly + offseason</option><option value="offseason">Offseason only</option></select></label></div></section>;
}
