import { useState } from 'react';
import type { League } from '../simulation/league';
import type { PlayerSeason } from '../simulation/types';
import { FOCUS_SKILLS, TARGET_ROLES, PROJECTS, type DevelopmentPlan, type ProjectKey } from '../simulation/coachingModel';
import { initialTraining, setDevelopmentPlan, setPlayerProject, planOpportunity, discussRole, CONVERSATIONS, badgeRequirements } from '../simulation/playerDevelopment';
import { staffMembers } from '../simulation/staffManagement';
import { calculateOverall } from '../simulation/engine/overall';
import { NORMAL_BADGES } from '../simulation/badges';
import { badgeCapacity, BADGE_SPACING_GAMES } from '../simulation/badgeRules';
import { PlayerNameTag } from './PlayerAvatar';
import { realDevelopmentStatus } from '../history/realDevelopment';
import { followsRealDevelopment } from '../simulation/realDevelopmentGate';
export function PlayerDevelopmentPanel({player,league,controlledTeamId,sandboxMode,onChange}:{player:PlayerSeason;league:League;controlledTeamId:string|null;sandboxMode:boolean;onChange?:(l:League)=>void}){
 const [message,setMessage]=useState(''),[projectKey,setProjectKey]=useState<ProjectKey>('corner-three');
 const team=league.teams.find(t=>t.seasons.some(p=>p.playerId===player.playerId));
 const tr=player.training??(team?initialTraining(player,team):null);
 if(!tr)return <p className="empty-state">This player does not have a recorded development plan yet. Plans begin when a player joins a roster.</p>;
 const editable=!!team&&!!onChange&&(sandboxMode||controlledTeamId===team.teamId);
 const change=(patch:Partial<DevelopmentPlan>)=>{if(!editable)return;const r=setDevelopmentPlan(league,player.playerId,patch,controlledTeamId,sandboxMode);onChange?.(r.league);setMessage(r.message)};
 return <div className="player-development"><h3>Development Plan</h3><p>{editable?'Direct this player’s training and long-term role.':'Read-only development history and plan.'} {team?.coachingControl?.developmentAuto?'Automatic development is on; staff reassess plans about once a month.':''}</p>
 {player.real&&<p className={followsRealDevelopment(player,league)?'real-dev-note':'hint-text'} role="note"><strong>{followsRealDevelopment(player,league)?'Real Player Development · ':'Real player · '}</strong>{realDevelopmentStatus(player,league)}{followsRealDevelopment(player,league)?' Plans, practice, coaches, mentors and projects below still shape workload, recovery, morale and familiarity.':''}</p>}
 <fieldset disabled={!editable} className="development-controls"><legend>Individual training</legend>
 {(['primary','secondary'] as const).map(key=><label key={key}>{key==='primary'?'Primary focus':'Secondary focus'}<select aria-label={key==='primary'?'Primary focus':'Secondary focus'} value={tr.plan[key]} onChange={e=>change({[key]:e.target.value})}>{Object.keys(FOCUS_SKILLS).map(f=><option key={f}>{f}</option>)}</select></label>)}
 <label>Training intensity<select aria-label="Training intensity" value={tr.plan.intensity} onChange={e=>change({intensity:e.target.value as DevelopmentPlan['intensity']})}>{['light','normal','hard'].map(f=><option key={f}>{f}</option>)}</select></label>
 <label>Target role<select aria-label="Target role" value={tr.plan.targetRole} onChange={e=>change({targetRole:e.target.value as DevelopmentPlan['targetRole']})}>{TARGET_ROLES.map(f=><option key={f}>{f}</option>)}</select></label>
 <label>Assigned coach<select aria-label="Assigned coach" value={tr.plan.coachId??''} onChange={e=>change({coachId:e.target.value||undefined})}><option value="">Development staff / head coach</option>{team&&staffMembers(team).map(s=><option key={s.coach.coachId}>{s.coach.coachId}</option>)}</select></label>
 <label>Veteran mentor<select aria-label="Veteran mentor" value={tr.plan.mentorId??''} onChange={e=>change({mentorId:e.target.value||undefined})}><option value="">None</option>{team?.seasons.filter(p=>p.age>=27&&p.age>=player.age+4&&p.playerId!==player.playerId).map(p=><option key={p.playerId} value={p.playerId}>{p.playerId} · {team.seasons.filter(s=>s.training?.plan.mentorId===p.playerId).length}/2 assignments</option>)}</select></label></fieldset>
 <p className="hint-text">Prioritizes {tr.plan.primary}, with secondary work on {tr.plan.secondary}. This leaves less practice time for other skills. Training changes the chance and direction of growth; it does not guarantee rating gains.</p><p>{planOpportunity({...player,training:tr})}</p>
 <div className="team-profile-facts"><div><small>Temporary workload</small><strong>{tr.workload.toFixed(0)}/100</strong></div><div><small>Role familiarity</small><strong>{tr.roleFamiliarity.toFixed(0)}%</strong></div><div><small>Practice days</small><strong>{tr.practiceDays} ({tr.injuredDays} restricted)</strong></div><div><small>Useful game experience</small><strong>{tr.evidence.minutes.toFixed(0)} minutes / {tr.evidence.handling} handling possessions</strong></div></div>
 <details><summary>System familiarity and development outlook</summary><p>Development patterns are tendencies, not promised careers. Potential is an estimate. Different skills peak at different times.</p><p>Observed tendency: {tr.practiceDays>=90||tr.history.some(h=>h.kind==='offseason')?tr.pattern:'Not enough tracked experience yet'}.</p>{Object.entries(tr.familiarity).map(([name,n])=><p key={name}>{name}: {Math.round(n)}%</p>)}</details>
 <section><h3>Long-term Project</h3>{tr.project?<><h4>{PROJECTS[tr.project.key].name}</h4><progress aria-label="Project progress" max="100" value={tr.project.progress}/><p>{tr.project.progress.toFixed(1)}% · {tr.project.status} · {tr.project.days} practice days</p><p>{PROJECTS[tr.project.key].impact}</p><p>Requirements: {PROJECTS[tr.project.key].threshold}+ {PROJECTS[tr.project.key].skill.split('.')[1]}. Relevant specialty: {PROJECTS[tr.project.key].specialty}.</p><p>{tr.project.obstacle||'No current obstacle.'} Broad estimate: 6–24 months of suitable work; stalled periods can take longer.</p>{editable&&<button onClick={()=>{onChange?.(setPlayerProject(league,player.playerId,null,controlledTeamId,sandboxMode));setMessage('Project cancelled. Attribute gains already earned are retained.')}}>Cancel Project</button>}</>:editable?<><label>Project<select aria-label="Project" value={projectKey} onChange={e=>setProjectKey(e.target.value as ProjectKey)}>{Object.entries(PROJECTS).map(([key,p])=><option key={key} value={key}>{p.name}</option>)}</select></label><p>{PROJECTS[projectKey].impact} Requires {PROJECTS[projectKey].threshold}+ {PROJECTS[projectKey].skill.split('.')[1]}, relevant practice and months of work.</p><button onClick={()=>onChange?.(setPlayerProject(league,player.playerId,projectKey,controlledTeamId,sandboxMode))}>Start Project</button></>:<p>No active project.</p>}</section>
 <section><h3>Role Discussions</h3><div className="team-profile-facts">{Object.entries(tr.morale).map(([key,n])=><div key={key}><small>{key}</small><strong>{Math.round(n)}/100</strong></div>)}</div>{tr.promise&&<p>Active {tr.promise.kind} promise: {tr.promise.achieved}/{tr.promise.required} qualifying games; {tr.promise.remaining} available games left. Injured games do not count.</p>}{editable&&<div className="code-mode-actions">{Object.entries(CONVERSATIONS).map(([key,label])=><button key={key} disabled={tr.games-tr.lastConversationGame<5} onClick={()=>{const r=discussRole(league,player.playerId,key as keyof typeof CONVERSATIONS,controlledTeamId,sandboxMode);onChange?.(r.league);setMessage(r.message)}}>{label}</button>)}</div>}<p className="hint-text">Discussions are available every five team games. Rotation promises require 12+ minutes in four of ten available games; workload promises require 30 minutes or fewer in seven of ten.</p></section>
 {message&&<p role="status">{message}</p>}
 <section><h3>Normal Badge Development</h3><p>Ability, efficient opportunities, a substantial sample and relevant practice all matter. Manual badge editing remains Sandbox-only.</p><div className="feature-table-scroll"><table className="db-table"><thead><tr><th>Badge</th><th>Stage</th><th>Effects and requirements</th></tr></thead><tbody>{NORMAL_BADGES.map(b=><tr key={b.id}><td>{b.name}</td><td>{tr.badgeProgress[b.id]?.stage??(player.badges.includes(b.id)?'Established':'Developing')}</td><td>{b.description}<details><summary>Requirements</summary>{badgeRequirements({...player,training:tr},b.id).description}<p>Badges arrive one at a time (at least {BADGE_SPACING_GAMES} games apart), and a {calculateOverall(player)} overall carries at most {badgeCapacity(calculateOverall(player))}.</p></details></td></tr>)}</tbody></table></div></section>
 <section><h3>Development History</h3>{!tr.history.length?<p>Reports appear as this player trains, plays, completes projects and advances through offseasons.</p>:[...tr.history].reverse().map((h,i)=><article className="development-history-entry" key={i}><strong>{h.season} · {h.date} · {h.kind}</strong><p>{h.text}</p>{h.changes&&<details><summary>Permanent attribute changes</summary><div className="staff-relationship-list">{Object.entries(h.changes).map(([k,n])=><span key={k}>{k}: {n>=0?'+':''}{n.toFixed(2)}</span>)}</div></details>}</article>)}</section>
 </div>;
}
export function DevelopmentRoster({league,teamId,onSelectPlayer}:{league:League;teamId:string;onSelectPlayer:(id:string)=>void}){
 const team=league.teams.find(t=>t.teamId===teamId);if(!team)return null;
 return <div className="feature-table-scroll"><table className="db-table"><thead><tr><th>Player</th><th>Age</th><th>Primary focus</th><th>Target role</th><th>Workload</th><th>Project</th></tr></thead><tbody>{team.seasons.map(p=><tr key={p.playerId}><td><button className="link-button" onClick={()=>onSelectPlayer(p.playerId)}><PlayerNameTag playerId={p.playerId} teamId={team.teamId}/></button></td><td>{p.age}</td><td>{p.training?.plan.primary??'Awaiting plan'}</td><td>{p.training?.plan.targetRole??'balanced'}</td><td>{Math.round(p.training?.workload??0)}/100</td><td>{p.training?.project?`${PROJECTS[p.training.project.key].name} · ${p.training.project.progress.toFixed(0)}%`:'—'}</td></tr>)}</tbody></table></div>;
}
