import { PersonalityPanel } from './MoralePanels';
import { scoutingReport } from '../simulation/scouting';
import { PlayerDevelopmentPanel } from './PlayerDevelopmentPanel';
import { PixelIcon } from './PixelIcon';
import { TeamLink } from './TeamLink';
import { Fragment, useState, useMemo } from 'react';
import type { PlayerSeason } from '../simulation/types';
import type { League } from '../simulation/league';
import { FullPlayerEditor } from './FullPlayerEditor';
import { PlayerAvatar } from './PlayerAvatar';
import { PixelBall } from './PixelIcon';
import { calculateRatings } from '../simulation/engine/overall';
import { perGameAverages, computeAdvancedStats, careerSummary, careerYearRows, careerStatUnavailable, type PerGameAverages, type AdvancedStats, type CareerYearRow, type CareerSummary } from '../simulation/careerStats';
import { currentSeasonAdvanced } from '../simulation/advancedStats';
import type { SeasonStatTotals, SeasonMilestones, MissingStat } from '../simulation/types';
import { fx, fpct, finiteSum, NA } from './statFormat';
import { RealPlayerFacts, AwardsByOrigin } from './RealPlayerFacts';
import { ratingSourceLabel } from '../history/datasetInfo';
import { NORMAL_BADGES, EXPERIMENTAL_BADGES } from '../simulation/badges';
import { getPlayerAwardsHistory, getPlayerAwardRaceHistory, type PlayerAwardEntry } from '../simulation/leagueAnalytics';
import { TrophyShelf } from './TrophyShelf';
import { awardOptions, computeSeasonAwards, placementsForPlayer } from '../simulation/awards';
import { formatSeasonYear } from '../simulation/calendar';

import type { GMLeagueExtras } from '../simulation/gm';
import { toggleWatchList } from '../simulation/gm';

interface Props {
  controlledTeamId?: string | null;
  activeTab?: 'overview'|'development';
  onTabChange?: (tab:'overview'|'development')=>void;
  season: PlayerSeason;
  teamName: string;
  onChange: (next: PlayerSeason) => void;
  sandboxMode: boolean;
  league?: League;
  extras?: GMLeagueExtras;
  onLeagueExtrasChange?: (league: League, extras: GMLeagueExtras, newPlayerId?: string) => void;
}

function inchesToFeetInches(inches: number): string {
  const ft = Math.floor(inches / 12);
  const inch = Math.round(inches % 12);
  return `${ft}'${inch}"`;
}

function topPosition(positions: PlayerSeason['positions']): string {
  const entries = Object.entries(positions) as [string, number][];
  return entries.sort((a, b) => b[1] - a[1])[0][0];
}

export function PlayerProfile({ season, teamName, onChange, sandboxMode, league, extras, onLeagueExtrasChange, controlledTeamId = null, activeTab, onTabChange }: Props) {
  const [localTab,setLocalTab] = useState<'overview'|'development'>('overview');
  const profileTab = activeTab ?? localTab;
  const [editMode, setEditMode] = useState(false);
  const ratings = calculateRatings(season);
  const badgeNames = season.badges.map((id) => [...NORMAL_BADGES, ...EXPERIMENTAL_BADGES].find((b) => b.id === id)?.name ?? id);
  const awardsHistory = league ? getPlayerAwardsHistory(league, season.playerId) : [];
  // Draft prospects keep their true potential hidden outside sandbox mode: show the user's scouting range instead.
  const prospect = !sandboxMode && league && extras ? extras.draftClass.find(p => p.playerId === season.playerId) : undefined;
  const scouted = prospect && league && extras ? scoutingReport(prospect, league, extras, controlledTeamId) : null;

  return (
    <div className="player-profile">
      <div className="profile-header">
        <div className="profile-avatar-block">
          <span className="sprite-stage-label">PLAYER FILE / {season.jerseyNumber ?? 'FA'}</span>
          <PlayerAvatar playerId={season.playerId} teamId={season.teamId} jerseyNumber={season.jerseyNumber} heightInches={season.attributes.physical.heightInches} age={season.age} mode="full" size={160} />
          <PixelBall size={32} />
          <span className="sprite-stage-position">{topPosition(season.positions)} · {inchesToFeetInches(season.attributes.physical.heightInches)}</span>
        </div>
        <div className="profile-header-main">
          <div className="profile-identity">
            <span className="pixel-eyebrow">SCOUTING REPORT</span>
            <h2>{season.playerId}</h2>
            <p className="profile-meta">
              <TeamLink name={teamName} /> - {topPosition(season.positions)} - {inchesToFeetInches(season.attributes.physical.heightInches)} -{' '}
              {season.attributes.physical.weightLbs} lbs - Age {season.age}
            </p>
            <span className="profile-source-tag" tabIndex={0} title={season.source === 'historical' ? 'Based on historical player data.' : season.source === 'generated' ? 'Fictional player generated by Court Vision; not an official athlete record.' : 'Player created or imported by you.'}>{season.source === 'historical' ? 'Historical' : season.source === 'generated' ? 'Generated' : 'Custom'}</span>
            {season.archetypeLabel && <p className="profile-archetype">{season.archetypeLabel}</p>}
          </div>
          <div className="profile-quickstats-grid">
            <div><span className="qs-label">OVR</span><span className="qs-value">{ratings.overall}</span></div>
            <div title={scouted ? `Scouted range (${scouted.confidence.toLowerCase()} confidence)` : undefined}><span className="qs-label">POT</span><span className="qs-value">{scouted ? (scouted.potLow === scouted.potHigh ? scouted.potLow : `${scouted.potLow}–${scouted.potHigh}`) : season.development.potential.toFixed(0)}</span></div>
            <div><span className="qs-label">POS</span><span className="qs-value">{topPosition(season.positions)}</span></div>
            <div><span className="qs-label">#</span><span className="qs-value">{season.jerseyNumber ?? '—'}</span></div>
            <div><span className="qs-label">3PT</span><span className="qs-value">{season.attributes.offense.threePoint.toFixed(0)}</span></div>
            <div><span className="qs-label">DEF</span><span className="qs-value">{season.attributes.defense.perimeterDefense.toFixed(0)}</span></div>
            <div><span className="qs-label">Age</span><span className="qs-value">{season.age}</span></div>

          </div>
        </div>
        <div className="profile-header-actions">
          {league && extras && onLeagueExtrasChange && (
            <button
              className={(extras.watchList ?? []).includes(season.playerId) ? 'active' : ''}
              onClick={() => onLeagueExtrasChange(league, toggleWatchList(extras, season.playerId))}
              title="Track this player on your Watch List"
            >
              <PixelIcon name="star" /> {(extras.watchList ?? []).includes(season.playerId) ? 'Watching' : 'Watch'}
            </button>
          )}
          {sandboxMode && <button className="primary edit-toggle" onClick={() => setEditMode((v) => !v)}>
            {editMode ? 'Done Editing' : 'Edit Player'}
          </button>}
        </div>
      </div>

      {league && <div className="code-mode-actions" role="group" aria-label="Player profile sections">{(['overview','development'] as const).map(view=><button key={view} aria-pressed={profileTab===view} className={profileTab===view?'active':''} onClick={()=>{setLocalTab(view);onTabChange?.(view);setEditMode(false)}}>{view==='overview'?'Overview':'Development'}</button>)}</div>}
      {profileTab === 'development' && league ? <PlayerDevelopmentPanel player={season} league={league} controlledTeamId={controlledTeamId} sandboxMode={sandboxMode} onChange={onLeagueExtrasChange && extras ? l => onLeagueExtrasChange(l,extras) : undefined} /> : sandboxMode && editMode ? (
        <FullPlayerEditor
          season={season} sandboxMode={sandboxMode} onChange={onChange}
          league={league} extras={extras} onLeagueExtrasChange={onLeagueExtrasChange}
        />
      ) : (
        <>{league && extras && !prospect && <PersonalityPanel p={season} league={league} extras={extras} />}
        <PlayerCard season={season} ratings={ratings} badgeNames={badgeNames} awardsHistory={awardsHistory} league={league} /></>
      )}
    </div>
  );
}

function StatLineRow({ label, totals, perGame, view, summary }: {
  label: string; totals: SeasonStatTotals; perGame: PerGameAverages; view: 'totals' | 'perGame';
  /** Career line: marks stats some imported seasons did not record ("*") or none did ("—"). */
  summary?: CareerSummary;
}) {
  const mark = (f: MissingStat, text: string | number) => careerCell(summary, f, text);
  const v = view === 'totals'
    ? { min: totals.minutes.toFixed(0), pts: totals.points, reb: totals.oreb + totals.dreb, ast: totals.ast, stl: totals.stl, blk: totals.blk, tov: totals.tov, pf: totals.pf,
        fg: `${totals.fgm}-${totals.fga}`, tp: `${totals.tpm}-${totals.tpa}`, ft: `${totals.ftm}-${totals.fta}` }
    : { min: fx(perGame.mpg), pts: fx(perGame.ppg), reb: fx(perGame.rpg), ast: fx(perGame.apg), stl: fx(perGame.spg, 2), blk: fx(perGame.bpg, 2), tov: fx(perGame.tovPg), pf: fx(perGame.pfPg),
        fg: `${fx(perGame.fgmPg)}-${fx(perGame.fgaPg)}`, tp: `${fx(perGame.tpmPg)}-${fx(perGame.tpaPg)}`, ft: `${fx(perGame.ftmPg)}-${fx(perGame.ftaPg)}` };
  return (
    <tr>
      <td className="col-name">{label}</td>
      <td>{totals.gamesPlayed}</td>
      <td>{mark('minutes', v.min)}</td>
      <td>{mark('points', v.pts)}</td>
      <td>{mark('dreb', v.reb)}</td>
      <td>{mark('ast', v.ast)}</td>
      <td>{mark('stl', v.stl)}</td>
      <td>{mark('blk', v.blk)}</td>
      <td>{mark('tov', v.tov)}</td>
      <td>{mark('pf', v.pf)}</td>
      <td>{mark('fga', v.fg)}</td>
      <td>{mark('fga', fpct(perGame.fgPct))}</td>
      <td>{mark('tpa', v.tp)}</td>
      <td>{mark('tpa', fpct(perGame.tpPct))}</td>
      <td>{mark('fta', v.ft)}</td>
      <td>{mark('fta', fpct(perGame.ftPct))}</td>
    </tr>
  );
}

/** A career-total cell: "—" when no season recorded the stat, a trailing "*" when only some did. */
function careerCell(summary: CareerSummary | undefined, f: MissingStat, text: string | number) {
  if (!summary || !summary.partial[f]) return text;
  if (careerStatUnavailable(summary, f)) return <span className="stat-na" title="Not recorded in his seasons' era">{NA}</span>;
  return <span title={`Not recorded in ${summary.partial[f]} of his ${summary.seasonsPlayed} seasons; totals and averages use the seasons that recorded it`}>{text}*</span>;
}
/** A season cell: "—" when that season's era did not record the stat. */
function seasonCell(missing: MissingStat[] | undefined, f: MissingStat, text: string | number) {
  return missing?.includes(f) ? <span className="stat-na" title="Not recorded that season">{NA}</span> : text;
}

function AdvancedStatRow({ label, advanced, milestones, summary }: { label: string; advanced: AdvancedStats; milestones: SeasonMilestones; summary?: CareerSummary }) {
  if (summary && Object.keys(summary.partial).length) return <PartialAdvancedStatRow label={label} advanced={advanced} milestones={milestones} summary={summary} />;
  return (
    <tr>
      <td className="col-name">{label}</td>
      <td>{(advanced.efgPct * 100).toFixed(1)}</td>
      <td>{(advanced.tsPct * 100).toFixed(1)}</td>
      <td>{advanced.astToRatio.toFixed(2)}</td>
      <td>{advanced.stlToRatio.toFixed(2)}</td>
      <td>{(advanced.ftRate * 100).toFixed(1)}</td>
      <td>{(advanced.threePointRate * 100).toFixed(1)}</td>
      <td>{(advanced.blockSuccessPct * 100).toFixed(1)}</td>
      <td>{advanced.pointsPerShot.toFixed(2)}</td>
      <td>{(advanced.turnoverPct * 100).toFixed(1)}</td>
      <td>{milestones.doubleDoubles}</td>
      <td>{milestones.tripleDoubles}</td>
      <td>{milestones.quadrupleDoubles}</td>
      <td>{milestones.quintupleDoubles}</td>
    </tr>
  );
}

/** Career advanced line when some seasons are imported history: ratios that need an unrecorded stat read "—". */
function PartialAdvancedStatRow({ label, advanced, milestones, summary }: { label: string; advanced: AdvancedStats; milestones: SeasonMilestones; summary: CareerSummary }) {
  const gap = (...f: MissingStat[]) => f.some(x => summary.partial[x]);
  const na = <span className="stat-na" title="Needs a stat that some of his seasons did not record">{NA}</span>;
  return (
    <tr>
      <td className="col-name">{label}</td>
      <td>{fpct(advanced.efgPct)}</td>
      <td>{gap('fta', 'points') ? na : fpct(advanced.tsPct)}</td>
      <td>{gap('ast', 'tov') ? na : fx(advanced.astToRatio, 2)}</td>
      <td>{gap('stl', 'tov') ? na : fx(advanced.stlToRatio, 2)}</td>
      <td>{gap('fta') ? na : fpct(advanced.ftRate)}</td>
      <td>{careerCell(summary, 'tpa', fpct(advanced.threePointRate))}</td>
      <td>{gap('blkAtt', 'blk') ? na : fpct(advanced.blockSuccessPct)}</td>
      <td>{fx(advanced.pointsPerShot, 2)}</td>
      <td>{gap('tov') ? na : fpct(advanced.turnoverPct)}</td>
      <td>{careerCell(summary, 'doubleDoubles', milestones.doubleDoubles)}</td>
      <td>{careerCell(summary, 'tripleDoubles', milestones.tripleDoubles)}</td>
      <td>{careerCell(summary, 'gameHighs', milestones.quadrupleDoubles)}</td>
      <td>{careerCell(summary, 'gameHighs', milestones.quintupleDoubles)}</td>
    </tr>
  );
}

interface TeamStint { teamName: string; fromSeason: string; toSeason: string; }

/** Collapses a season-by-season list into contiguous team stints, e.g. "Knicks: 2024-25 to 2026-27". */
function buildTeamHistory(season: PlayerSeason, teamNameFor: (teamId: string | null) => string): TeamStint[] {
  const entries: { season: string; teamId: string | null }[] = [
    ...(season.careerHistory ?? []).map((h) => ({ season: h.season, teamId: h.teamId })),
  ];
  if (season.seasonStats || entries.length === 0) entries.push({ season: season.season, teamId: season.teamId });

  const stints: TeamStint[] = [];
  for (const e of entries) {
    const name = teamNameFor(e.teamId);
    const last = stints[stints.length - 1];
    if (last && last.teamName === name) last.toSeason = e.season;
    else stints.push({ teamName: name, fromSeason: e.season, toSeason: e.season });
  }
  return stints;
}

function PlayerCard({ season, ratings, badgeNames, awardsHistory, league }: {
  season: PlayerSeason; ratings: ReturnType<typeof calculateRatings>; badgeNames: string[];
  awardsHistory: PlayerAwardEntry[]; league?: League;
}) {
  const [view, setView] = useState<'totals' | 'perGame' | 'advanced' | 'playoffs'>('perGame');
  const currentAdvanced = useMemo(() => league ? currentSeasonAdvanced(league).get(season.playerId) : undefined, [league, season.playerId]);
  const avg = perGameAverages(season.seasonStats);
  const advanced = computeAdvancedStats(season.seasonStats);
  const milestones = season.seasonMilestones;
  const hasStats = (season.seasonStats?.gamesPlayed ?? 0) > 0;
  const summary = careerSummary(season);
  const rows = careerYearRows(season, currentAdvanced);
  const teamNameFor = (teamId: string | null) => (teamId ? league?.teams.find((t) => t.teamId === teamId)?.name ?? teamId : 'Free Agent');
  const teamHistory = buildTeamHistory(season, teamNameFor);
  const history = [...(season.history ?? [])].reverse(); // most recent first
  const placements = useMemo(
    () => (league ? placementsForPlayer(computeSeasonAwards(league, awardOptions(league.awardSettings)), season.playerId) : []),
    [league, season.playerId],
  );
  const raceHistory = useMemo(
    () => (league ? getPlayerAwardRaceHistory(league, season.playerId) : []),
    [league, season.playerId],
  );
  const groupedAwards = useMemo(() => {
    const byLabel = new Map<string, string[]>();
    for (const a of awardsHistory) {
      const years = byLabel.get(a.label) ?? [];
      years.push(a.season);
      byLabel.set(a.label, years);
    }
    return [...byLabel.entries()].map(([label, years]) => ({ label, years }));
  }, [awardsHistory]);

  return (
    <div className="player-card">
      <section>
        <div className="stats-section-header">
          <h4>Stats</h4>
          <div className="stats-view-toggle">
            <button className={view === 'perGame' ? 'active' : ''} onClick={() => setView('perGame')}>Per Game</button>
            <button className={view === 'totals' ? 'active' : ''} onClick={() => setView('totals')}>Totals</button>
          </div>
        </div>

        {hasStats ? (
          <>
            <table className="db-table stat-line-table">
              <thead>
                <tr>
                  <th className="col-name">&nbsp;</th><th>GP</th><th>MIN</th><th>PTS</th><th>REB</th><th>AST</th>
                  <th>STL</th><th>BLK</th><th>TOV</th><th>PF</th><th>FG</th><th>FG%</th><th>3P</th><th>3P%</th><th>FT</th><th>FT%</th>
                </tr>
              </thead>
              <tbody>
                <StatLineRow label="This Season" totals={season.seasonStats!} perGame={avg} view={view === 'totals' ? 'totals' : 'perGame'} />
                {summary.seasonsPlayed > 0 && <StatLineRow label="Career" totals={summary.totals} perGame={summary.perGame} view={view === 'totals' ? 'totals' : 'perGame'} summary={summary} />}
              </tbody>
            </table>

            <h5 className="stats-subheading">Advanced</h5>
            <table className="db-table stat-line-table">
              <thead>
                <tr>
                  <th className="col-name">&nbsp;</th><th>eFG%</th><th>TS%</th><th>AST/TO</th><th>STL/TO</th><th>FT Rate</th>
                  <th>3PT Rate</th><th>BLK%</th><th>PTS/Shot</th><th>TOV%</th><th>DD</th><th>TD</th><th>4D</th><th>5D</th>
                </tr>
              </thead>
              <tbody>
                <AdvancedStatRow label="This Season" advanced={advanced} milestones={milestones ?? summary.milestones} />
                {summary.seasonsPlayed > 0 && <AdvancedStatRow label="Career" advanced={summary.advanced} milestones={summary.milestones} summary={summary} />}
              </tbody>
            </table>
            {milestones && (
              <p className="hint-text stats-highs">
                Season highs: {milestones.gameHighPoints} PTS · {milestones.gameHighRebounds} REB · {milestones.gameHighAssists} AST ·{' '}
                {milestones.gameHighSteals} STL · {milestones.gameHighBlocks} BLK
                {' — '}Career highs: {summary.milestones.gameHighPoints} PTS · {summary.milestones.gameHighRebounds} REB ·{' '}
                {summary.milestones.gameHighAssists} AST · {summary.milestones.gameHighSteals} STL · {summary.milestones.gameHighBlocks} BLK
                {summary.partial.gameHighs ? ' (games in this league only; game highs are not in the imported history)' : ''}
              </p>
            )}
          </>
        ) : (
          <p className="hint-text">No games played yet this season.</p>
        )}
      </section>

      <section>
        <h4>Ratings</h4>
        <table className="db-table">
          <tbody>
            <tr><td>Overall</td><td>{ratings.overall}</td></tr>
            <tr><td>Offensive Rating</td><td>{ratings.offensiveRating.toFixed(1)}</td></tr>
            <tr><td>Defensive Rating</td><td>{ratings.defensiveRating.toFixed(1)}</td></tr>
            <tr><td>Shooting Rating</td><td>{ratings.shootingRating.toFixed(1)}</td></tr>
            <tr><td>Playmaking Rating</td><td>{ratings.playmakingRating.toFixed(1)}</td></tr>
            <tr><td>Rebounding Rating</td><td>{ratings.reboundingRating.toFixed(1)}</td></tr>
            <tr><td>Physical Rating</td><td>{ratings.physicalRating.toFixed(1)}</td></tr>
          </tbody>
        </table>
        {season.real && <RealPlayerFacts player={season} league={league} />}
      </section>

      <section>
        <h4>Badges</h4>
        {badgeNames.length > 0 ? (
          <div className="badge-grid">{badgeNames.map((n) => <span key={n} className="badge-chip" tabIndex={0} title={[...NORMAL_BADGES, ...EXPERIMENTAL_BADGES].find(b => b.name === n)?.description}>{n}</span>)}</div>
        ) : (
          <p className="hint-text">No badges equipped.</p>
        )}
      </section>

      <section>
        <div className="stats-section-header">
          <h4>Season by Season</h4>
          <div className="stats-view-toggle">
            <button className={view === 'perGame' ? 'active' : ''} onClick={() => setView('perGame')}>Per Game</button>
            <button className={view === 'totals' ? 'active' : ''} onClick={() => setView('totals')}>Totals</button>
            <button className={view === 'advanced' ? 'active' : ''} onClick={() => setView('advanced')}>Advanced</button>
            <button className={view === 'playoffs' ? 'active' : ''} onClick={() => setView('playoffs')}>Playoffs</button>
          </div>
        </div>
        {rows.length > 0 && view === 'advanced' ? <CareerAdvancedTable rows={rows} />
        : rows.length > 0 && view === 'playoffs' ? <CareerPlayoffTable rows={rows} />
        : rows.length === 0 ? (
          <p className="hint-text">No completed prior seasons on record yet.</p>
        ) : (
          <table className="db-table stat-line-table">
            <thead>
              <tr>
                <th>Season</th><th>Team</th><th>Age</th><th>OVR</th><th>GP</th><th>MIN</th><th>PTS</th><th>REB</th><th>AST</th>
                <th>STL</th><th>BLK</th><th>TOV</th><th>FG%</th><th>3P%</th><th>FT%</th><th>DD</th><th>TD</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((r) => { const m = r.missing; return (<Fragment key={r.season}>
                <tr className={r.isCurrent ? 'current-season-row' : r.imported ? 'imported-row' : undefined}>
                  <td title={r.imported ? 'Real NBA season (imported)' : undefined}>{formatSeasonYear(r.season)}{r.isCurrent && ' *'}</td>
                  <td title={r.splits ? 'Total across teams' : r.teamLabel ? `${r.teamLabel} (today: ${r.teamId})` : undefined}>{r.splits ? 'TOT' : r.teamLabel ?? r.teamId ?? '—'}</td>
                  <td>{r.age || '—'}</td>
                  <td title={r.rating ? `Start-of-season Overall ${r.rating.ovr}: ${ratingSourceLabel(r.rating.source)}` : r.imported ? 'No rating on record' : undefined}>{r.overall || '—'}</td>
                  <td>{r.totals.gamesPlayed}</td>
                  <td>{seasonCell(m, 'minutes', view === 'totals' ? r.totals.minutes.toFixed(0) : fx(r.perGame.mpg))}</td>
                  <td>{seasonCell(m, 'points', view === 'totals' ? r.totals.points : fx(r.perGame.ppg))}</td>
                  <td>{seasonCell(m, 'dreb', view === 'totals' ? r.totals.oreb + r.totals.dreb : fx(r.perGame.rpg))}</td>
                  <td>{seasonCell(m, 'ast', view === 'totals' ? r.totals.ast : fx(r.perGame.apg))}</td>
                  <td>{seasonCell(m, 'stl', view === 'totals' ? r.totals.stl : fx(r.perGame.spg, 2))}</td>
                  <td>{seasonCell(m, 'blk', view === 'totals' ? r.totals.blk : fx(r.perGame.bpg, 2))}</td>
                  <td>{seasonCell(m, 'tov', view === 'totals' ? r.totals.tov : fx(r.perGame.tovPg))}</td>
                  <td>{seasonCell(m, 'fga', fpct(r.perGame.fgPct))}</td>
                  <td>{seasonCell(m, 'tpa', fpct(r.perGame.tpPct))}</td>
                  <td>{seasonCell(m, 'fta', fpct(r.perGame.ftPct))}</td>
                  <td>{seasonCell(m, 'doubleDoubles', r.milestones.doubleDoubles)}</td>
                  <td>{seasonCell(m, 'tripleDoubles', r.milestones.tripleDoubles)}</td>
                </tr>
                {r.splits?.map((sp, i) => <tr key={`${r.season}-${i}`} className="split-row">
                  <td>↳</td><td title={sp.teamLabel ? `${sp.teamLabel} (today: ${sp.teamId})` : undefined}>{sp.teamLabel ?? sp.teamId}</td><td /><td />
                  <td>{sp.totals.gamesPlayed}</td>
                  <td>{seasonCell(m, 'minutes', view === 'totals' ? sp.totals.minutes.toFixed(0) : fx(sp.perGame.mpg))}</td>
                  <td>{seasonCell(m, 'points', view === 'totals' ? sp.totals.points : fx(sp.perGame.ppg))}</td>
                  <td>{seasonCell(m, 'dreb', view === 'totals' ? sp.totals.oreb + sp.totals.dreb : fx(sp.perGame.rpg))}</td>
                  <td>{seasonCell(m, 'ast', view === 'totals' ? sp.totals.ast : fx(sp.perGame.apg))}</td>
                  <td>{seasonCell(m, 'stl', view === 'totals' ? sp.totals.stl : fx(sp.perGame.spg, 2))}</td>
                  <td>{seasonCell(m, 'blk', view === 'totals' ? sp.totals.blk : fx(sp.perGame.bpg, 2))}</td>
                  <td>{seasonCell(m, 'tov', view === 'totals' ? sp.totals.tov : fx(sp.perGame.tovPg))}</td>
                  <td>{seasonCell(m, 'fga', fpct(sp.perGame.fgPct))}</td><td>{seasonCell(m, 'tpa', fpct(sp.perGame.tpPct))}</td><td>{seasonCell(m, 'fta', fpct(sp.perGame.ftPct))}</td><td /><td />
                </tr>)}
              </Fragment>); })}
              {summary.seasonsPlayed > 1 && (
                <tr className="totals-row">
                  <td className="col-name">Career</td><td /><td /><td />
                  <td>{summary.totals.gamesPlayed}</td>
                  <td>{careerCell(summary, 'minutes', view === 'totals' ? summary.totals.minutes.toFixed(0) : fx(summary.perGame.mpg))}</td>
                  <td>{careerCell(summary, 'points', view === 'totals' ? summary.totals.points : fx(summary.perGame.ppg))}</td>
                  <td>{careerCell(summary, 'dreb', view === 'totals' ? summary.totals.oreb + summary.totals.dreb : fx(summary.perGame.rpg))}</td>
                  <td>{careerCell(summary, 'ast', view === 'totals' ? summary.totals.ast : fx(summary.perGame.apg))}</td>
                  <td>{careerCell(summary, 'stl', view === 'totals' ? summary.totals.stl : fx(summary.perGame.spg, 2))}</td>
                  <td>{careerCell(summary, 'blk', view === 'totals' ? summary.totals.blk : fx(summary.perGame.bpg, 2))}</td>
                  <td>{careerCell(summary, 'tov', view === 'totals' ? summary.totals.tov : fx(summary.perGame.tovPg))}</td>
                  <td>{careerCell(summary, 'fga', fpct(summary.perGame.fgPct))}</td>
                  <td>{careerCell(summary, 'tpa', fpct(summary.perGame.tpPct))}</td>
                  <td>{careerCell(summary, 'fta', fpct(summary.perGame.ftPct))}</td>
                  <td>{careerCell(summary, 'doubleDoubles', summary.milestones.doubleDoubles)}</td>
                  <td>{careerCell(summary, 'tripleDoubles', summary.milestones.tripleDoubles)}</td>
                </tr>
              )}
            </tbody>
          </table>
        )}
        {rows.some(r => r.imported) && <p className="hint-text">Shaded seasons are real NBA regular seasons imported from history; later seasons are simulated in this league. — = not recorded in that era (e.g. steals and blocks before 1973–74, three-pointers before 1979–80). * = career figure from the seasons that recorded it.</p>}
      </section>

      <section>
        <h4>Bio</h4>
        <table className="db-table">
          <tbody>
            <tr><td>Build</td><td>{season.archetypeLabel ?? '—'}</td></tr>
            <tr><td>Jersey</td><td>{season.jerseyNumber ?? '—'}</td></tr>
            <tr><td>Height / Weight</td><td>{Math.floor(season.attributes.physical.heightInches / 12)}'{season.attributes.physical.heightInches % 12}" · {season.attributes.physical.weightLbs} lbs</td></tr>
            <tr><td>College</td><td>{season.college || '—'}</td></tr>
            <tr><td>Nationality</td><td>{season.nationality || '—'}</td></tr>
            <tr>
              <td>Draft</td>
              <td>
                {season.draftYear ? <>{season.draftYear} — Round {season.draftRound ?? '?'}, Pick {season.draftPick ?? '?'}{season.draftTeamId && <> (<TeamLink teamId={season.draftTeamId} name={league?.teams.find(t => t.teamId === season.draftTeamId)?.name ?? season.draftTeamId} />)</>}</> : 'Undrafted'}
              </td>
            </tr>
          </tbody>
        </table>
      </section>

      <section>
        <h4>Team History</h4>
        {teamHistory.length === 0 ? (
          <p className="hint-text">No team history on record yet.</p>
        ) : (
          <table className="db-table">
            <thead><tr><th>Team</th><th>Seasons</th></tr></thead>
            <tbody>
              {teamHistory.map((s, i) => (
                <tr key={i}>
                  <td className="col-name"><TeamLink name={s.teamName} /></td>
                  <td>{formatSeasonYear(s.fromSeason) === formatSeasonYear(s.toSeason) ? formatSeasonYear(s.fromSeason) : `${formatSeasonYear(s.fromSeason)} to ${formatSeasonYear(s.toSeason)}`}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </section>

      <section>
        <h4>Full History</h4>
        {history.length === 0 ? (
          <p className="hint-text">No history recorded yet — trades, signings, waives, and injuries will appear here as they happen.</p>
        ) : (
          <ul className="history-log">
            {history.map((e, i) => (
              <li key={i} className={`history-entry history-${e.type}`}>
                <span className="history-season">{formatSeasonYear(e.season)}</span>
                <span className="history-desc">{e.description}</span>
              </li>
            ))}
          </ul>
        )}
      </section>

      <section>
        <h4>Award Races (This Season)</h4>
        {placements.length === 0 ? (
          <p className="hint-text">Not currently in the top 10 of any award ballot.</p>
        ) : (
          <div className="award-placements">
            {placements.map((p) => (
              <span
                key={p.award}
                className={`award-placement-chip ${p.place === 1 ? 'place-1' : p.place <= 3 ? 'place-podium' : ''}`}
                title={`${p.label}: ${p.place}${p.place === 1 ? 'st' : p.place === 2 ? 'nd' : p.place === 3 ? 'rd' : 'th'} place`}
              >
                {p.label}-{p.place}
              </span>
            ))}
          </div>
        )}
      </section>

      <section>
        <h4>Award Races by Year</h4>
        {raceHistory.length === 0 ? (
          <p className="hint-text">No archived award-ballot finishes yet — these accumulate as full seasons are completed.</p>
        ) : (
          <div className="award-placements">
            {raceHistory.map((p, i) => (
              <span
                key={i}
                className={`award-placement-chip ${p.place === 1 ? 'place-1' : p.place <= 3 ? 'place-podium' : ''}`}
                title={`${formatSeasonYear(p.season)}: ${p.label}, ${p.place}${p.place === 1 ? 'st' : p.place === 2 ? 'nd' : p.place === 3 ? 'rd' : 'th'} place`}
              >
                {formatSeasonYear(p.season)} {p.label}-{p.place}
              </span>
            ))}
          </div>
        )}
      </section>

      <section>
        <h4>Awards</h4>
        {awardsHistory.length > 0 && <TrophyShelf entries={awardsHistory} />}
        {league?.historical || season.historicalAwards?.length ? <AwardsByOrigin player={season} league={league} awardsHistory={awardsHistory} /> : awardsHistory.length === 0 ? (
          <p className="hint-text">No awards on record yet. Awards are archived automatically once you advance past a season's playoffs.</p>
        ) : (
          <details className="trophy-list-details"><summary>Every honor, season by season</summary>
            <div className="badge-grid">
              {groupedAwards.map((g) => (
                <span key={g.label} className="badge-chip" title={g.years.map(formatSeasonYear).join(', ')}>
                  {g.label}{g.years.length > 1 ? ` ×${g.years.length}` : ''}
                </span>
              ))}
            </div>
          </details>
        )}
      </section>
    </div>
  );
}

/** PER, shooting efficiency, usage, rebound/assist/steal/block rates, ratings and win shares, season by season. */
function CareerAdvancedTable({ rows }: { rows: CareerYearRow[] }) {
  const f1 = (v?: number) => fx(v), pct = (v?: number) => fpct(v);
  const sum = (k: 'ows' | 'dws' | 'ws') => finiteSum(rows.map(r => r.adv?.[k]));
  const minutes = rows.reduce((n, r) => n + (r.adv && Number.isFinite(r.adv.ws) && !r.missing?.includes('minutes') ? r.totals.minutes : 0), 0);
  return <div className="stat-table-scroll"><table className="db-table stat-line-table">
    <thead><tr><th>Season</th><th>Age</th><th>GP</th><th title="Player Efficiency Rating">PER</th><th>TS%</th><th>USG%</th><th>ORB%</th><th>DRB%</th><th>TRB%</th><th>AST%</th><th>STL%</th><th>BLK%</th><th>TOV%</th><th>ORtg</th><th>DRtg</th><th>OWS</th><th>DWS</th><th>WS</th><th>WS/48</th></tr></thead>
    <tbody>{rows.map(r => <Fragment key={r.season}><tr className={r.isCurrent ? 'current-season-row' : undefined}>
      <td>{formatSeasonYear(r.season)}{r.isCurrent && ' *'}</td><td>{r.age || '—'}</td><td>{r.totals.gamesPlayed}</td>
      <td>{f1(r.adv?.per)}</td><td>{pct(r.adv?.tsPct ?? r.advanced.tsPct)}</td><td>{f1(r.adv?.usgPct)}</td><td>{f1(r.adv?.orbPct)}</td><td>{f1(r.adv?.drbPct)}</td><td>{f1(r.adv?.trbPct)}</td>
      <td>{f1(r.adv?.astPct)}</td><td>{f1(r.adv?.stlPct)}</td><td>{f1(r.adv?.blkPct)}</td><td>{f1(r.adv?.tovPct)}</td><td>{f1(r.adv?.ortg)}</td><td>{f1(r.adv?.drtg)}</td>
      <td>{f1(r.adv?.ows)}</td><td>{f1(r.adv?.dws)}</td><td><b>{f1(r.adv?.ws)}</b></td><td>{fx(r.adv?.ws48, 3)}</td></tr>
      {r.splits?.map((sp, i) => <tr key={`${r.season}-${i}`} className="split-row"><td>↳ {sp.teamId}</td><td /><td>{sp.totals.gamesPlayed}</td><td>{f1(sp.adv?.per)}</td><td>{pct(sp.adv?.tsPct)}</td><td>{f1(sp.adv?.usgPct)}</td>
        <td>{f1(sp.adv?.orbPct)}</td><td>{f1(sp.adv?.drbPct)}</td><td>{f1(sp.adv?.trbPct)}</td><td>{f1(sp.adv?.astPct)}</td><td>{f1(sp.adv?.stlPct)}</td><td>{f1(sp.adv?.blkPct)}</td><td>{f1(sp.adv?.tovPct)}</td>
        <td>{f1(sp.adv?.ortg)}</td><td>{f1(sp.adv?.drtg)}</td><td>{f1(sp.adv?.ows)}</td><td>{f1(sp.adv?.dws)}</td><td>{f1(sp.adv?.ws)}</td><td>{fx(sp.adv?.ws48, 3)}</td></tr>)}</Fragment>)}
      <tr className="totals-row"><td className="col-name">Career</td><td /><td>{rows.reduce((n, r) => n + r.totals.gamesPlayed, 0)}</td><td colSpan={12} /><td>{sum('ows').toFixed(1)}</td><td>{sum('dws').toFixed(1)}</td><td><b>{sum('ws').toFixed(1)}</b></td><td>{minutes > 0 ? (sum('ws') * 48 / minutes).toFixed(3) : '—'}</td></tr>
    </tbody></table>
    <p className="hint-text">— means the stat was not recorded that season (older eras), or the season was played before advanced stats were archived. Real NBA seasons show Basketball-Reference advanced stats; ORtg/DRtg are not in the imported data.</p></div>;
}
function CareerPlayoffTable({ rows }: { rows: CareerYearRow[] }) {
  const played = rows.filter(r => (r.playoffs?.gamesPlayed ?? 0) > 0);
  const importedNote = rows.some(r => r.imported) ? <p className="hint-text">Real NBA playoff statistics from before this league's start are not in the imported data; only playoffs played in this league are listed.</p> : null;
  if (!played.length) return <>{<p className="hint-text">No playoff games on record yet.</p>}{importedNote}</>;
  const pg = (n: number, g: number) => (n / Math.max(1, g)).toFixed(1);
  return <div className="stat-table-scroll"><table className="db-table stat-line-table">
    <thead><tr><th>Season</th><th>GP</th><th>MIN</th><th>PTS</th><th>REB</th><th>AST</th><th>STL</th><th>BLK</th><th>FG%</th><th>3P%</th><th>FT%</th></tr></thead>
    <tbody>{played.map(r => { const p = r.playoffs!; return <tr key={r.season}><td>{formatSeasonYear(r.season)}</td><td>{p.gamesPlayed}</td><td>{pg(p.minutes, p.gamesPlayed)}</td><td>{pg(p.points, p.gamesPlayed)}</td>
      <td>{pg(p.oreb + p.dreb, p.gamesPlayed)}</td><td>{pg(p.ast, p.gamesPlayed)}</td><td>{pg(p.stl, p.gamesPlayed)}</td><td>{pg(p.blk, p.gamesPlayed)}</td>
      <td>{p.fga ? (p.fgm / p.fga * 100).toFixed(1) : '—'}</td><td>{p.tpa ? (p.tpm / p.tpa * 100).toFixed(1) : '—'}</td><td>{p.fta ? (p.ftm / p.fta * 100).toFixed(1) : '—'}</td></tr>; })}</tbody>
  </table>{importedNote}</div>;
}
