import { useState } from 'react';
import type { League } from '../simulation/league';
import type { CoachIdentity } from '../simulation/coaching';
import { STAFF_ROLES, STAFF_LABELS, COACH_ATTRIBUTES, type StaffRole } from '../simulation/coachingModel';
import { enrichCoach, staffMembers, staffSalary, staffBudget, staffOfferAssessment, interviewCoach, hireStaff, fireStaff, promoteStaff } from '../simulation/staffManagement';
import { TeamLink } from './TeamLink';
import { ConfirmationDialog } from './ConfirmationDialog';

export function CoachProfile({coach,role='head'}:{coach:CoachIdentity;role?:StaffRole}){
 const c=enrichCoach(coach,role),p=c.profile!;
 return <article className="coach-profile"><h3>{c.coachId}</h3><p>Age {c.age} · {p.experience} tracked seasons · Career {c.careerWins}–{c.careerLosses} · Playoffs {p.playoffWins}–{p.playoffLosses}</p><p>{c.championships} championships · {p.coyAwards} Coach of the Year awards{p.formerPlayerId?' · Former player':''}</p>
  <p>{p.personality} {p.leadership} · {p.offense} offense / {p.defense} defense · Specialties: {p.specialties.join(', ')}</p>
  <p>Contract: ${(c.contract.annualSalary/1e6).toFixed(2)}M per year · {c.contract.yearsRemaining} years remaining</p>
  <div className="staff-attribute-grid">{COACH_ATTRIBUTES.map(k=><div key={k}><span>{k.replace(/([A-Z])/g,' $1')}</span><meter min={0} max={100} value={p.attributes[k]} /><strong>{Math.round(p.attributes[k])}</strong></div>)}</div>
  <details><summary>Career and relationships</summary><p className="hint-text">Tracking begins when the staff system is introduced; prior employment is not invented.</p><ul>{p.history.map((h,i)=><li key={i}><TeamLink teamId={h.teamId} /> · {STAFF_LABELS[h.role]} · {h.from}–{h.to??'present'}</li>)}</ul><h4>Player relationships</h4><div className="staff-relationship-list">{Object.entries(c.relationships).map(([name,n])=><span key={name}>{name}: {Math.round(n)}/100</span>)}</div><h4>Staff relationships</h4>{Object.entries(p.staffRelationships).length?Object.entries(p.staffRelationships).map(([name,n])=><p key={name}>{name}: {Math.round(n)}/100</p>):<p>No shared games recorded yet.</p>}<h4>Development record</h4>{p.developmentHistory.length?<div className="feature-table-scroll"><table className="db-table"><thead><tr><th>Player</th><th>Season</th><th>Before</th><th>After</th></tr></thead><tbody>{p.developmentHistory.slice(-100).reverse().map((h,i)=><tr key={i}><td>{h.playerId}</td><td>{h.season}</td><td>{h.before.toFixed(1)}</td><td>{h.after.toFixed(1)}</td></tr>)}</tbody></table></div>:<p>Offseason player progress will be recorded here.</p>}</details>
 </article>;
}
export function StaffPage({league,controlledTeamId,sandboxMode,onChange}:{league:League;controlledTeamId:string|null;sandboxMode:boolean;onChange:(l:League)=>void}){
 const [selectedTeam,setSelectedTeam]=useState(controlledTeamId??league.teams[0]?.teamId??'');
 const team=league.teams.find(t=>t.teamId===(sandboxMode?selectedTeam:controlledTeamId));
 const [selectedId,setSelectedId]=useState(''),[role,setRole]=useState<StaffRole>('head'),[salary,setSalary]=useState(3000000),[years,setYears]=useState(3),[interview,setInterview]=useState(false),[message,setMessage]=useState(''),[firing,setFiring]=useState<StaffRole|null>(null);
 if(!team)return <p className="empty-state">Control a team to manage staff. Other teams’ staff can be inspected through team profiles.</p>;
 const employed=staffMembers(team).find(s=>s.coach.coachId===selectedId),candidate=league.staffMarket?.find(c=>c.coachId===selectedId),selected=candidate??employed?.coach;
 const assessmentTeam=employed&&employed.role!=='head'?{...team,staff:Object.fromEntries(Object.entries(team.staff??{}).filter(([key])=>key!==employed.role))}:team;
 const assessment=selected?staffOfferAssessment(assessmentTeam,selected,role,salary,years,league):null;
 const open=(coach:CoachIdentity,currentRole:StaffRole)=>{setSelectedId(coach.coachId);setRole((league.staffMarket??[]).some(c=>c.coachId===coach.coachId)?currentRole:'head');setSalary(coach.contract.annualSalary*((league.staffMarket??[]).some(c=>c.coachId===coach.coachId)||currentRole==='head'?1:2.5));setYears(3);setInterview(false);setMessage('');};
 return <div className="staff-page"><div className="season-feature-header"><div><span className="pixel-eyebrow">THE FRONT OFFICE</span><h2>Staff & Contracts</h2><TeamLink teamId={team.teamId}/></div>{sandboxMode&&<label>Manage staff for<select aria-label="Staff team" value={team.teamId} onChange={e=>{setSelectedTeam(e.target.value);setSelectedId('')}}>{league.teams.map(t=><option key={t.teamId} value={t.teamId}>{t.name}</option>)}</select></label>}</div>
 <p>Staff payroll ${(staffSalary(team)/1e6).toFixed(2)}M · Budget ${(staffBudget(team)/1e6).toFixed(2)}M · Current-season payouts ${((team.coachingControl?.payout??0)/1e6).toFixed(2)}M</p><p className="hint-text">Vacant positions provide less support. Assistants may be left empty to reduce costs. Staff costs and firing payouts count in team finances.</p>
 <div className="feature-table-scroll"><table className="db-table"><thead><tr><th>Role</th><th>Coach</th><th>Salary</th><th>Years</th><th>Actions</th></tr></thead><tbody>{STAFF_ROLES.map(r=>{const coach=staffMembers(team).find(s=>s.role===r)?.coach;return <tr key={r}><td>{STAFF_LABELS[r]}</td><td>{coach?<button className="link-button" onClick={()=>open(coach,r)}>{coach.coachId}</button>:'Vacant'}</td><td>{coach?`$${(coach.contract.annualSalary/1e6).toFixed(2)}M`:'—'}</td><td>{coach?.contract.yearsRemaining??'—'}</td><td>{coach&&<button onClick={()=>setFiring(r)}>Release {STAFF_LABELS[r]}</button>}</td></tr>})}</tbody></table></div>
 {message&&<p role="status">{message}</p>}
 {selected&&<section className="staff-offer" aria-label="Coach details"><CoachProfile coach={selected} role={employed?.role??role}/><button onClick={()=>setInterview(!interview)}>{interview?'Close Interview':'Interview Coach'}</button>{interview&&<ul>{interviewCoach(team,selected).map(a=><li key={a}>{a}</li>)}</ul>}
 {(candidate||employed?.role!=='head')&&<><div className="development-controls"><label>Offered role<select aria-label="Offered staff role" value={role} onChange={e=>setRole(e.target.value as StaffRole)}>{(candidate?STAFF_ROLES:['head'] as const).map(r=><option key={r} value={r}>{STAFF_LABELS[r]}</option>)}</select></label><label>Annual salary<input aria-label="Staff annual salary" type="number" min="1" step="50000" value={salary} onChange={e=>setSalary(+e.target.value)}/></label><label>Contract years<input aria-label="Staff contract years" type="number" min="1" max="5" value={years} onChange={e=>setYears(+e.target.value)}/></label></div><p>Interest {assessment?.interest}/100 · Demand ${assessment?.demand.toLocaleString()} · Replacing this position costs ${assessment?.payout.toLocaleString()}.</p>{assessment?.reason&&<p className="hint-text">{assessment.reason}</p>}<button className="primary" disabled={!assessment?.accepted||(!candidate&&role!=='head')} onClick={()=>{const r=candidate?hireStaff(league,team.teamId,selected.coachId,role,salary,years,controlledTeamId,sandboxMode):promoteStaff(league,team.teamId,selected.coachId,salary,years,controlledTeamId,sandboxMode);onChange(r.league);setMessage(r.message);if(r.league!==league)setSelectedId('');}}>Offer Contract</button></>}
 </section>}
 <section><h3>Staff Market</h3><p>Candidates weigh salary, term, competitiveness, roster fit, facilities, role and relationships. The market is saved with the league; reopening it does not reroll candidates.</p><div className="feature-table-scroll"><table className="db-table"><thead><tr><th>Candidate</th><th>Preferred role</th><th>Specialty</th><th>Teaching</th><th>Demand</th></tr></thead><tbody>{(league.staffMarket??[]).map(c=>{const p=enrichCoach(c,'head').profile!;return <tr key={c.coachId}><td><button className="link-button" onClick={()=>open(c,p.preferredRole)}>{c.coachId}</button></td><td>{STAFF_LABELS[p.preferredRole]}</td><td>{p.specialties.join(', ')}</td><td>{Math.round(p.attributes.teaching)}</td><td>${(c.contract.annualSalary/1e6).toFixed(2)}M</td></tr>})}</tbody></table></div></section>
 {firing&&<ConfirmationDialog title={`Release ${STAFF_LABELS[firing]}?`} confirmLabel="Release Staff" onCancel={()=>setFiring(null)} onConfirm={()=>{const r=fireStaff(league,team.teamId,firing,controlledTeamId,sandboxMode);onChange(r.league);setMessage(r.message);setFiring(null);setSelectedId('')}}><p>The remaining contract payout is ${((staffMembers(team).find(s=>s.role===firing)?.coach.contract.annualSalary??0)*(staffMembers(team).find(s=>s.role===firing)?.coach.contract.yearsRemaining??0)).toLocaleString()}. The team needs five games to adjust. Automatic staff management can fill the vacancy.</p></ConfirmationDialog>}
 </div>;
}
