// Bundles each Vercel Function in server/ into one self-contained file in api/ (committed, like the Windows zip),
// so the deployed function never depends on how Vercel resolves TypeScript imports.
import { build } from 'rolldown';
import { writeFileSync, readFileSync, mkdirSync } from 'node:fs';

mkdirSync('api', { recursive: true });
const functions = { 'api/sync.js': 'server/api-sync.ts', 'api/pvp.js': 'server/api-pvp.ts' };
for (const [out, input] of Object.entries(functions)) {
  const result = await build({ input, platform: 'node', write: false, output: { format: 'esm' }, logLevel: 'silent' });
  const code = `// Generated by scripts/build-api.mjs from ${input}. Do not edit; run npm run build:api.\n${result.output[0].code}`;
  let old = '';
  try { old = readFileSync(out, 'utf8'); } catch { /* new */ }
  if (old !== code) writeFileSync(out, code);
  console.log(`${out}: ${(code.length / 1024).toFixed(1)} KB${old === code ? ' (unchanged)' : ''}`);
}
