// Generated by scripts/build-api.mjs from server/api-billing.ts. Do not edit; run npm run build:api.
//#region server/supabase.ts
const pick = (env, ...names) => names.map((n) => env[n]).find((v) => !!v);
function supaEnv(env = globalThis.process?.env ?? {}) {
	const url = pick(env, "SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_URL", "VITE_SUPABASE_URL");
	const serviceKey = pick(env, "SUPABASE_SERVICE_ROLE_KEY", "SUPABASE_SECRET_KEY");
	const publicKey = pick(env, "SUPABASE_ANON_KEY", "NEXT_PUBLIC_SUPABASE_ANON_KEY", "SUPABASE_PUBLISHABLE_KEY", "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_ANON_KEY") ?? serviceKey;
	return url && serviceKey && publicKey ? {
		url: url.replace(/\/$/, ""),
		serviceKey,
		publicKey
	} : null;
}
/** New-style keys (sb_…) go in the apikey header only; legacy JWT keys also as the bearer token. */
const keyHeaders = (key) => key.startsWith("sb_") ? { apikey: key } : {
	apikey: key,
	Authorization: `Bearer ${key}`
};
/** A PostgREST call with the service key (row level security does not apply). */
async function rest(env, method, path, body, prefer, f = fetch) {
	const res = await f(`${env.url}/rest/v1/${path}`, {
		method,
		headers: {
			...keyHeaders(env.serviceKey),
			"Content-Type": "application/json",
			...prefer ? { Prefer: prefer } : {}
		},
		...body !== void 0 ? { body: JSON.stringify(body) } : {}
	});
	if (!res.ok) throw new Error(`${method} ${path.split("?")[0]}: ${res.status} ${(await res.text()).slice(0, 200)}`);
	const text = await res.text();
	return text ? JSON.parse(text) : null;
}
const upsert = (env, table, rows, onConflict, f) => rows.length ? rest(env, "POST", `${table}?on_conflict=${onConflict}`, rows, "resolution=merge-duplicates,return=minimal", f) : Promise.resolve(null);
const json = (body, status = 200) => new Response(JSON.stringify(body), {
	status,
	headers: {
		"Content-Type": "application/json",
		"Cache-Control": "no-store"
	}
});
//#endregion
//#region server/billing.ts
const ids = (v) => (v ?? "").split(",").map((s) => s.trim()).filter(Boolean);
function billingEnv(env = globalThis.process?.env ?? {}) {
	const secret = env.LEMONSQUEEZY_WEBHOOK_SECRET;
	return secret ? {
		secret,
		noAds: ids(env.LEMONSQUEEZY_NO_ADS_VARIANT_ID),
		supporter: ids(env.LEMONSQUEEZY_SUPPORTER_VARIANT_ID)
	} : null;
}
const enc = new TextEncoder();
const hex = (buf) => [...new Uint8Array(buf)].map((b) => b.toString(16).padStart(2, "0")).join("");
async function signBody(secret, body) {
	const key = await crypto.subtle.importKey("raw", enc.encode(secret), {
		name: "HMAC",
		hash: "SHA-256"
	}, false, ["sign"]);
	return hex(await crypto.subtle.sign("HMAC", key, enc.encode(body)));
}
/** Compares in constant time, so the check leaks nothing about how close a forged signature came. */
function sameHex(a, b) {
	if (a.length !== b.length) return false;
	let diff = 0;
	for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
	return diff === 0;
}
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
/** A subscription is paid through its renewal date (plus a few days for a late renewal webhook). */
const GRACE_MS = 2592e5;
const LIVE = /* @__PURE__ */ new Set([
	"active",
	"on_trial",
	"past_due"
]);
/** How long a Supporter subscription in this state keeps its perks (null: none). */
function supporterUntil(a, now = Date.now()) {
	const t = (s) => s ? Date.parse(s) : NaN;
	if (LIVE.has(a.status ?? "")) {
		const renew = t(a.renews_at);
		return new Date((Number.isFinite(renew) ? renew : now + 26784e5) + GRACE_MS).toISOString();
	}
	if (a.status === "cancelled" && Number.isFinite(t(a.ends_at))) return new Date(t(a.ends_at)).toISOString();
	return null;
}
async function handleBilling(req, supa, bill, f = fetch, now = Date.now()) {
	try {
		return await record(req, supa, bill, f, now);
	} catch (e) {
		if (e instanceof Error && e.message.includes("23503")) return json({
			ok: true,
			ignored: "no such account"
		});
		return json({ error: "Could not record the purchase." }, 500);
	}
}
async function record(req, supa, bill, f, now) {
	if (req.method !== "POST") return json({ error: "POST only" }, 405);
	if (!supa || !bill) return json({ error: "Billing is not set up on this server." }, 503);
	const body = await req.text();
	const sig = (req.headers.get("x-signature") ?? "").toLowerCase();
	if (!sig || !sameHex(sig, await signBody(bill.secret, body))) return json({ error: "Bad signature" }, 401);
	let p;
	try {
		p = JSON.parse(body);
	} catch {
		return json({ error: "Bad JSON" }, 400);
	}
	const event = p.meta?.event_name ?? "";
	const userId = p.meta?.custom_data?.user_id ?? "";
	const a = p.data?.attributes ?? {};
	if (!UUID.test(userId)) return json({
		ok: true,
		ignored: "no user_id on the checkout"
	});
	const variant = String(a.first_order_item?.variant_id ?? a.variant_id ?? "");
	const base = {
		user_id: userId,
		customer_id: a.customer_id != null ? String(a.customer_id) : null,
		updated_at: new Date(now).toISOString()
	};
	if (event === "order_created" || event === "order_refunded") {
		if (!bill.noAds.includes(variant)) return json({
			ok: true,
			ignored: "not the No-Ads Pass"
		});
		const owned = event === "order_created" && a.status !== "refunded";
		await upsert(supa, "entitlements", [{
			...base,
			no_ads: owned,
			no_ads_order: p.data?.id ?? null
		}], "user_id", f);
		return json({
			ok: true,
			noAds: owned
		});
	}
	if (event.startsWith("subscription_")) {
		if (!bill.supporter.includes(variant)) return json({
			ok: true,
			ignored: "not the Supporter Pass"
		});
		if (p.data?.type !== "subscriptions") return json({
			ok: true,
			ignored: "not a subscription object"
		});
		const stamp = a.updated_at ?? new Date(now).toISOString();
		const seen = (await rest(supa, "GET", `entitlements?user_id=eq.${userId}&select=subscription_updated_at`, void 0, void 0, f))?.[0]?.subscription_updated_at;
		if (seen && Date.parse(seen) > Date.parse(stamp)) return json({
			ok: true,
			ignored: "stale"
		});
		const until = supporterUntil(a, now);
		await upsert(supa, "entitlements", [{
			...base,
			supporter_until: until,
			supporter_status: a.status ?? null,
			subscription_id: p.data?.id ?? null,
			subscription_updated_at: stamp,
			portal_url: a.urls?.customer_portal ?? null
		}], "user_id", f);
		return json({
			ok: true,
			supporterUntil: until
		});
	}
	return json({
		ok: true,
		ignored: event || "no event"
	});
}
//#endregion
//#region server/api-billing.ts
const POST = (request) => handleBilling(request, supaEnv(), billingEnv());
//#endregion
export { POST };
