// Generated by scripts/build-api.mjs from server/api-leaderboard.ts. Do not edit; run npm run build:api.
//#region src/retention/week.ts
/** ISO week in UTC, e.g. "2026-W39". Weeks start on Monday. */
function weekKey(now = /* @__PURE__ */ new Date()) {
	const d = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
	const day = d.getUTCDay() || 7;
	d.setUTCDate(d.getUTCDate() + 4 - day);
	const yearStart = Date.UTC(d.getUTCFullYear(), 0, 1);
	const week = Math.ceil(((d.getTime() - yearStart) / 864e5 + 1) / 7);
	return `${d.getUTCFullYear()}-W${String(week).padStart(2, "0")}`;
}
function weeklySeed(kind, week) {
	let h = 2166136261;
	for (const ch of `courtvision-weekly|${kind}|${week}`) {
		h ^= ch.charCodeAt(0);
		h = Math.imul(h, 16777619);
	}
	return (h >>> 0) % 1e9;
}
//#endregion
//#region src/simulation/rebuildScenarios.ts
const SCENARIOS = [
	{
		id: "bulls99",
		title: "Life After Michael",
		team: "CHI",
		startYear: 1998,
		seasons: 6,
		difficulty: "Very hard",
		blurb: "Jordan, Pippen and Phil are gone. Six rings on the wall, 13 wins on the way. Bring a seventh banner."
	},
	{
		id: "celtics97",
		title: "Celtics in Ruins",
		team: "BOS",
		startYear: 1996,
		seasons: 6,
		difficulty: "Hard",
		blurb: "The most decorated franchise in the league just went 15-67. Restore the pride."
	},
	{
		id: "clippers99",
		title: "The Clipper Curse",
		team: "LAC",
		startYear: 1998,
		seasons: 8,
		difficulty: "Brutal",
		blurb: "9-41 in a lockout year, and nobody wants to play here. Win the first title in franchise history."
	},
	{
		id: "warriors01",
		title: "Before the Dynasty",
		team: "GSW",
		startYear: 2e3,
		seasons: 8,
		difficulty: "Brutal",
		blurb: "17-65, no plan and no stars. Build the Warriors a decade early."
	},
	{
		id: "wolves10",
		title: "Wolves in the Wilderness",
		team: "MIN",
		startYear: 2009,
		seasons: 7,
		difficulty: "Brutal",
		blurb: "Garnett is long gone and the lottery keeps coming. Make Minnesota a champion."
	},
	{
		id: "cavs11",
		title: "The Decision, Undone",
		team: "CLE",
		startYear: 2010,
		seasons: 5,
		difficulty: "Very hard",
		blurb: "LeBron took his talents to South Beach. From 61 wins to 19. Five years to win it without him."
	},
	{
		id: "bobcats13",
		title: "After 7-59",
		team: "CHA",
		startYear: 2012,
		seasons: 7,
		difficulty: "Brutal",
		blurb: "The worst winning percentage in NBA history, one season ago. Take Charlotte all the way."
	},
	{
		id: "sixers14",
		title: "Trust the Process",
		team: "PHI",
		startYear: 2013,
		seasons: 6,
		difficulty: "Very hard",
		blurb: "Tear it down, stack the picks, and see if the process ends with a parade."
	},
	{
		id: "knicks15",
		title: "Garden of Despair",
		team: "NYK",
		startYear: 2014,
		seasons: 6,
		difficulty: "Very hard",
		blurb: "17-65 in the Mecca. Every free agent says no. Make them say yes."
	},
	{
		id: "lakers17",
		title: "The Post-Kobe Lakers",
		team: "LAL",
		startYear: 2016,
		seasons: 5,
		difficulty: "Hard",
		blurb: "Kobe said Mamba out. Five years to bring a ring back to Los Angeles."
	},
	{
		id: "kings17",
		title: "The Longest Drought",
		team: "SAC",
		startYear: 2016,
		seasons: 7,
		difficulty: "Brutal",
		blurb: "Ten straight years without the playoffs, and counting. Break it, then win it all."
	},
	{
		id: "mavs94",
		title: "Eleven and Seventy-One",
		team: "DAL",
		startYear: 1993,
		seasons: 7,
		difficulty: "Brutal",
		blurb: "The worst team in basketball, two years running. Jim Jackson and Jamal Mashburn are a start. Finish it."
	},
	{
		id: "nuggets99",
		title: "Mile-High Misery",
		team: "DEN",
		startYear: 1998,
		seasons: 6,
		difficulty: "Brutal",
		blurb: "11-71 and a 23-game losing streak. McDyess, Van Exel and a young Billups. Make Denver matter."
	},
	{
		id: "heat09",
		title: "Wade Alone",
		team: "MIA",
		startYear: 2008,
		seasons: 5,
		difficulty: "Hard",
		blurb: "Two years after the title, 15-67. Wade is healthy again and the second pick is in. Get him help, fast."
	},
	{
		id: "hawks06",
		title: "Up From 13-69",
		team: "ATL",
		startYear: 2005,
		seasons: 6,
		difficulty: "Very hard",
		blurb: "Joe Johnson just arrived, Josh Smith can fly, and the arena is empty. Fill it with a banner."
	},
	{
		id: "orlando05",
		title: "Orlando After T-Mac",
		team: "ORL",
		startYear: 2004,
		seasons: 6,
		difficulty: "Very hard",
		blurb: "21-61, McGrady traded, and an 18-year-old Dwight Howard in the middle. Build around him."
	},
	{
		id: "nets11",
		title: "Twelve and Seventy",
		team: "NJN",
		startYear: 2010,
		seasons: 6,
		difficulty: "Brutal",
		blurb: "A 0-18 start, a 12-70 finish, and a move to Brooklyn coming. Arrive with a contender."
	},
	{
		id: "bucks15",
		title: "The Greek Freak Project",
		team: "MIL",
		startYear: 2014,
		seasons: 6,
		difficulty: "Hard",
		blurb: "15-67 last year, but a skinny 19-year-old named Giannis is on the roster. Speed up history."
	},
	{
		id: "pistons21",
		title: "Motor City Reset",
		team: "DET",
		startYear: 2020,
		seasons: 5,
		difficulty: "Very hard",
		blurb: "Twenty wins and a blank slate. Five seasons to bring back the Bad Boys."
	}
];
const FINISH_POINTS = {
	"Play-In": 5,
	"First Round": 20,
	Playoffs: 20,
	"Second Round": 40,
	"Conference Finals": 70,
	Finals: 120,
	Champion: 200
};
const MADE_PLAYOFFS = /* @__PURE__ */ new Set([
	"First Round",
	"Playoffs",
	"Second Round",
	"Conference Finals",
	"Finals",
	"Champion"
]);
/** Scores a challenge's seasons: seasons after a title don't count; a title scores 1,000 plus 250 per season to spare. */
function scoreResults(results, seasons) {
	const titleAt = results.findIndex((r) => r.finish === "Champion");
	const counted = titleAt >= 0 ? results.slice(0, titleAt + 1) : results;
	return {
		counted,
		titleAt,
		score: counted.reduce((n, r) => n + r.wins * 2 + (FINISH_POINTS[r.finish] ?? 0), 0) + (titleAt >= 0 ? 1e3 + (seasons - (titleAt + 1)) * 250 : 0),
		stars: titleAt >= 0 ? 3 : counted.some((r) => r.finish === "Finals") ? 2 : counted.some((r) => MADE_PLAYOFFS.has(r.finish)) ? 1 : 0
	};
}
//#endregion
//#region src/retention/weekly.ts
const TWISTS = [
	{
		id: "standard",
		label: "Standard rules",
		blurb: "The scenario as written.",
		seasonsDelta: 0,
		hardTrades: false
	},
	{
		id: "shortClock",
		label: "Short clock",
		blurb: "One season less than usual. Win faster.",
		seasonsDelta: -1,
		hardTrades: false
	},
	{
		id: "hardTrades",
		label: "Tough GMs",
		blurb: "Trades need tightly matched value. No fleecing the AI.",
		seasonsDelta: 0,
		hardTrades: true
	},
	{
		id: "gauntlet",
		label: "Short clock, tough GMs",
		blurb: "One season less, and trades need tightly matched value.",
		seasonsDelta: -1,
		hardTrades: true
	}
];
function weeklyRebuild(week = weekKey()) {
	const seed = weeklySeed("rebuild", week);
	const scenario = SCENARIOS[seed % SCENARIOS.length];
	const twist = TWISTS[Math.floor(seed / 97) % TWISTS.length];
	return {
		week,
		seed,
		scenario,
		twist,
		seasons: Math.max(3, scenario.seasons + twist.seasonsDelta)
	};
}
//#endregion
//#region server/leaderboard.ts
function upstash(url, token) {
	return { async run(commands) {
		const res = await fetch(`${url.replace(/\/$/, "")}/pipeline`, {
			method: "POST",
			headers: {
				Authorization: `Bearer ${token}`,
				"Content-Type": "application/json"
			},
			body: JSON.stringify(commands)
		});
		if (!res.ok) throw new Error(`Redis ${res.status}`);
		return (await res.json()).map((r) => {
			if (r.error) throw new Error(r.error);
			return r.result;
		});
	} };
}
const TTL = 7776e3;
const key = (b, w) => `lb:${b}:${w}`;
const WEEK_RE = /^\d{4}-W\d{2}$/;
const ID_RE = /^[a-z0-9]{16,40}$/;
const BLOCKED = [
	"fuck",
	"shit",
	"cunt",
	"nigg",
	"fag",
	"bitch",
	"whore",
	"rape",
	"nazi",
	"hitler",
	"slut",
	"retard"
];
function cleanName(raw, max = 18) {
	if (typeof raw !== "string") return null;
	const name = raw.normalize("NFC").replace(/\s+/g, " ").trim();
	if (!/^[\p{L}\p{N}][\p{L}\p{N} ._'-]*$/u.test(name) || name.length < 2 || name.length > max) return null;
	const flat = name.toLowerCase().replace(/[^a-z]/g, "");
	return BLOCKED.some((w) => flat.includes(w)) ? null : name;
}
/** The weeks that still take entries: this one and the three before (a long rebuild can finish after Monday). */
function openWeeks(now = /* @__PURE__ */ new Date()) {
	return Array.from({ length: 4 }, (_, i) => weekKey(/* @__PURE__ */ new Date(now.getTime() - i * 7 * 864e5)));
}
const FINISHES = /* @__PURE__ */ new Set([...Object.keys(FINISH_POINTS), "Missed Playoffs"]);
const int = (v, lo, hi) => typeof v === "number" && Number.isInteger(v) && v >= lo && v <= hi;
/** Checks a submission and works out its score and the line shown on the board. */
function checkSubmission(s, now = /* @__PURE__ */ new Date()) {
	if (s.board !== "rebuild" && s.board !== "career") return {
		ok: false,
		error: "Unknown board."
	};
	if (typeof s.week !== "string" || !WEEK_RE.test(s.week) || !openWeeks(now).includes(s.week)) return {
		ok: false,
		error: "That week's board is closed."
	};
	if (typeof s.id !== "string" || !ID_RE.test(s.id)) return {
		ok: false,
		error: "Bad player id."
	};
	if (!cleanName(s.name)) return {
		ok: false,
		error: "Pick a name of 2-18 letters or numbers (and keep it clean)."
	};
	if (s.board === "rebuild") {
		const w = weeklyRebuild(s.week);
		const r = s.results;
		if (!Array.isArray(r) || !r.length || r.length > w.seasons) return {
			ok: false,
			error: "Bad season results."
		};
		for (const x of r) if (!x || !int(x.wins, 0, 82) || !int(x.losses, 0, 82) || x.wins + x.losses < 20 || x.wins + x.losses > 82 || !FINISHES.has(x.finish)) return {
			ok: false,
			error: "Bad season results."
		};
		const { titleAt, score, stars, counted } = scoreResults(r, w.seasons);
		if (titleAt < 0 && r.length < w.seasons) return {
			ok: false,
			error: "Finish the challenge first."
		};
		const best = [...counted].sort((a, b) => b.wins - a.wins)[0];
		return {
			ok: true,
			score,
			detail: `${"★".repeat(stars)}${"☆".repeat(3 - stars)} · ${titleAt >= 0 ? `title in year ${titleAt + 1}` : `best ${best.wins}-${best.losses}`}`
		};
	}
	const c = s.career;
	if (!c || !cleanName(c.player, 24) || !int(c.legacy, 0, 400) || !int(c.seasons, 1, 25) || !int(c.titles, 0, c.seasons) || !int(c.mvps, 0, c.seasons) || ![
		"no",
		"yes",
		"first-ballot"
	].includes(c.hof)) return {
		ok: false,
		error: "Bad career."
	};
	const p = (n, w) => `${n} ${w}${n === 1 ? "" : "s"}`;
	return {
		ok: true,
		score: c.legacy,
		detail: `${cleanName(c.player, 24)} · ${p(c.seasons, "season")} · ${p(c.titles, "title")} · ${p(c.mvps, "MVP")}${c.hof !== "no" ? " · Hall of Fame" : ""}`
	};
}
async function readBoard(redis, board, week, id, limit = 100) {
	const k = key(board, week);
	const [range, total, rank, score] = await redis.run([
		[
			"ZREVRANGE",
			k,
			0,
			limit - 1,
			"WITHSCORES"
		],
		["ZCARD", k],
		[
			"ZREVRANK",
			k,
			id ?? "-"
		],
		[
			"ZSCORE",
			k,
			id ?? "-"
		]
	]);
	const ids = [], scores = [];
	for (let i = 0; i < (range?.length ?? 0); i += 2) {
		ids.push(range[i]);
		scores.push(Number(range[i + 1]));
	}
	const meta = ids.length ? (await redis.run([[
		"HMGET",
		`${k}:meta`,
		...ids
	]]))[0] : [];
	return {
		board,
		week,
		entries: ids.map((m, i) => {
			let info = {};
			try {
				info = JSON.parse(meta[i] ?? "{}");
			} catch {}
			return {
				rank: i + 1,
				name: info.name ?? "Anonymous",
				score: scores[i],
				detail: info.detail ?? "",
				...m === id ? { you: true } : {}
			};
		}),
		total: Number(total ?? 0),
		you: id && rank != null ? {
			rank: Number(rank) + 1,
			score: Number(score)
		} : null
	};
}
async function sha(text) {
	const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
	return [...new Uint8Array(buf)].slice(0, 12).map((b) => b.toString(16).padStart(2, "0")).join("");
}
/** Stores a checked entry, keeping each player's best score. Returns false if the rate limit is hit. */
async function submit(redis, s, checked, ip, now = /* @__PURE__ */ new Date()) {
	const rl = `lb:rl:${await sha(`${ip}|${Math.floor(now.getTime() / 36e5)}|court-vision`)}`;
	const [count] = await redis.run([["INCR", rl], [
		"EXPIRE",
		rl,
		3600
	]]);
	if (count > 12) return false;
	const k = key(s.board, s.week);
	const [prev] = await redis.run([[
		"ZSCORE",
		k,
		s.id
	]]);
	if (prev != null && Number(prev) > checked.score) return true;
	await redis.run([
		[
			"ZADD",
			k,
			checked.score,
			s.id
		],
		[
			"HSET",
			`${k}:meta`,
			s.id,
			JSON.stringify({
				name: cleanName(s.name),
				detail: checked.detail,
				at: now.toISOString()
			})
		],
		[
			"EXPIRE",
			k,
			TTL
		],
		[
			"EXPIRE",
			`${k}:meta`,
			TTL
		]
	]);
	return true;
}
const json = (body, status = 200, cache = false) => new Response(JSON.stringify(body), {
	status,
	headers: {
		"Content-Type": "application/json",
		"Cache-Control": cache ? "public, s-maxage=20, stale-while-revalidate=60" : "no-store"
	}
});
/** The whole endpoint: GET reads a board, POST submits to one. */
async function handle(request, redis, now = /* @__PURE__ */ new Date()) {
	if (!redis) return json({ error: "Online boards are not set up yet." }, 503);
	try {
		if (request.method === "GET") {
			const u = new URL(request.url);
			const board = u.searchParams.get("board");
			const week = u.searchParams.get("week") ?? weekKey(now);
			const id = u.searchParams.get("id");
			if (board !== "rebuild" && board !== "career" || !WEEK_RE.test(week) || id && !ID_RE.test(id)) return json({ error: "Bad request." }, 400);
			return json(await readBoard(redis, board, week, id), 200, !id);
		}
		if (request.method === "POST") {
			const text = await request.text();
			if (text.length > 4e3) return json({ error: "Too large." }, 413);
			let s;
			try {
				s = JSON.parse(text);
			} catch {
				return json({ error: "Bad request." }, 400);
			}
			const checked = checkSubmission(s, now);
			if (!checked.ok) return json({ error: checked.error }, 400);
			const ip = request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || request.headers.get("x-real-ip") || "unknown";
			if (!await submit(redis, s, checked, ip, now)) return json({ error: "Too many submissions: try again in an hour." }, 429);
			return json(await readBoard(redis, s.board, s.week, s.id));
		}
		return json({ error: "Method not allowed." }, 405);
	} catch {
		return json({ error: "The leaderboard is having trouble. Try again soon." }, 502);
	}
}
//#endregion
//#region server/api-leaderboard.ts
const env = (name) => globalThis.process?.env[name];
function fromEnv() {
	const url = env("KV_REST_API_URL") ?? env("UPSTASH_REDIS_REST_URL"), token = env("KV_REST_API_TOKEN") ?? env("UPSTASH_REDIS_REST_TOKEN");
	return url && token ? upstash(url, token) : null;
}
const GET = (request) => handle(request, fromEnv());
const POST = (request) => handle(request, fromEnv());
//#endregion
export { GET, POST };
