// Generated by scripts/build-api.mjs from server/api-pvp.ts. Do not edit; run npm run build:api.
//#endregion
//#region src/simulation/badges.ts
const NORMAL_BADGES = [
	{
		"id": "deep_range",
		"name": "Deep Range",
		"category": "shooting",
		"description": "+6 three point; +5 above-the-break threes.",
		"effect": { "attributeModifiers": {
			"offense.threePoint": 6,
			"offense.aboveBreak3": 5
		} },
		"stackable": false
	},
	{
		"id": "deadeye",
		"name": "Deadeye",
		"category": "shooting",
		"description": "+7 shot IQ; +3 offensive consistency.",
		"effect": { "attributeModifiers": {
			"offense.shotIQ": 7,
			"offense.offensiveConsistency": 3
		} },
		"stackable": false
	},
	{
		"id": "quick_release",
		"name": "Quick Release",
		"category": "shooting",
		"description": "+5 catch and shoot; +5 offensive IQ.",
		"effect": { "attributeModifiers": {
			"offense.catchAndShoot": 5,
			"offense.offensiveIQ": 5
		} },
		"stackable": false
	},
	{
		"id": "catch_and_shoot",
		"name": "Catch & Shoot",
		"category": "shooting",
		"description": "+8 catch and shoot; +4 corner threes.",
		"effect": { "attributeModifiers": {
			"offense.catchAndShoot": 8,
			"offense.corner3": 4
		} },
		"stackable": false
	},
	{
		"id": "difficult_shots",
		"name": "Difficult Shots",
		"category": "shooting",
		"description": "+6 midrange; +5 post fade; +3 shot IQ.",
		"effect": { "attributeModifiers": {
			"offense.midrange": 6,
			"offense.postFade": 5,
			"offense.shotIQ": 3
		} },
		"stackable": false
	},
	{
		"id": "pullup_specialist",
		"name": "Pull-Up Specialist",
		"category": "shooting",
		"description": "+8 pull-up threes; +4 long midrange.",
		"effect": { "attributeModifiers": {
			"offense.pullUp3": 8,
			"offense.longMidrange": 4
		} },
		"stackable": false
	},
	{
		"id": "handles",
		"name": "Handles",
		"category": "ballhandling",
		"description": "+7 ball handling; +3 speed with ball.",
		"effect": { "attributeModifiers": {
			"offense.ballHandling": 7,
			"offense.speedWithBall": 3
		} },
		"stackable": false
	},
	{
		"id": "unpluckable",
		"name": "Unpluckable",
		"category": "ballhandling",
		"description": "+8 ball security.",
		"effect": { "attributeModifiers": { "offense.ballSecurity": 8 } },
		"stackable": false
	},
	{
		"id": "tight_handle",
		"name": "Tight Handle",
		"category": "ballhandling",
		"description": "+4 ball handling; +5 decision making.",
		"effect": { "attributeModifiers": {
			"offense.ballHandling": 4,
			"offense.decisionMaking": 5
		} },
		"stackable": false
	},
	{
		"id": "speed_booster",
		"name": "Speed Booster",
		"category": "ballhandling",
		"description": "+7 speed with ball; +3 acceleration.",
		"effect": { "attributeModifiers": {
			"offense.speedWithBall": 7,
			"physical.acceleration": 3
		} },
		"stackable": false
	},
	{
		"id": "rim_protector",
		"name": "Rim Protector",
		"category": "defense",
		"description": "+6 rim protection; +5 block.",
		"effect": { "attributeModifiers": {
			"defense.rimProtection": 6,
			"defense.block": 5
		} },
		"stackable": false
	},
	{
		"id": "lockdown",
		"name": "Lockdown",
		"category": "defense",
		"description": "+7 perimeter defense; +4 contest.",
		"effect": { "attributeModifiers": {
			"defense.perimeterDefense": 7,
			"defense.contest": 4
		} },
		"stackable": false
	},
	{
		"id": "interceptor",
		"name": "Interceptor",
		"category": "defense",
		"description": "+7 passing lane steal; +4 steal IQ.",
		"effect": { "attributeModifiers": {
			"defense.passingLaneSteal": 7,
			"defense.stealIQ": 4
		} },
		"stackable": false
	},
	{
		"id": "pick_pocket",
		"name": "Pick Pocket",
		"category": "defense",
		"description": "+7 on ball steal; +4 steal.",
		"effect": { "attributeModifiers": {
			"defense.onBallSteal": 7,
			"defense.steal": 4
		} },
		"stackable": false
	},
	{
		"id": "chase_down",
		"name": "Chase Down",
		"category": "defense",
		"description": "+6 block timing; +3 speed; +3 vertical.",
		"effect": { "attributeModifiers": {
			"defense.blockTiming": 6,
			"physical.speed": 3,
			"physical.vertical": 3
		} },
		"stackable": false
	},
	{
		"id": "contact_finisher",
		"name": "Contact Finisher",
		"category": "finishing",
		"description": "+6 finishing; +4 strength.",
		"effect": { "attributeModifiers": {
			"offense.finishing": 6,
			"physical.strength": 4
		} },
		"stackable": false
	},
	{
		"id": "acrobat",
		"name": "Acrobat",
		"category": "finishing",
		"description": "+7 driving layup; +4 touch.",
		"effect": { "attributeModifiers": {
			"offense.drivingLayup": 7,
			"offense.touch": 4
		} },
		"stackable": false
	},
	{
		"id": "posterizer",
		"name": "Posterizer",
		"category": "finishing",
		"description": "+7 driving dunk; +4 vertical.",
		"effect": { "attributeModifiers": {
			"offense.drivingDunk": 7,
			"physical.vertical": 4
		} },
		"stackable": false
	},
	{
		"id": "dimer",
		"name": "Dimer",
		"category": "passing",
		"description": "+6 passing IQ; +4 passing.",
		"effect": { "attributeModifiers": {
			"offense.passingIQ": 6,
			"offense.passing": 4
		} },
		"stackable": false
	},
	{
		"id": "needle_threader",
		"name": "Needle Threader",
		"category": "passing",
		"description": "+7 passing accuracy; +3 passing.",
		"effect": { "attributeModifiers": {
			"offense.passingAccuracy": 7,
			"offense.passing": 3
		} },
		"stackable": false
	},
	{
		"id": "bail_out",
		"name": "Bail Out",
		"category": "passing",
		"description": "+6 decision making; +4 passing accuracy.",
		"effect": { "attributeModifiers": {
			"offense.decisionMaking": 6,
			"offense.passingAccuracy": 4
		} },
		"stackable": false
	},
	{
		"id": "glass_cleaner",
		"name": "Glass Cleaner",
		"category": "defense",
		"description": "+7 defensive rebounding; +5 offensive rebounding.",
		"effect": { "attributeModifiers": {
			"defense.defensiveRebounding": 7,
			"offense.offensiveRebounding": 5
		} },
		"stackable": false
	},
	{
		"id": "post_craft",
		"name": "Post Craft",
		"category": "finishing",
		"description": "+6 post control; +5 post hook; +4 post fade.",
		"effect": { "attributeModifiers": {
			"offense.postControl": 6,
			"offense.postHook": 5,
			"offense.postFade": 4
		} },
		"stackable": false
	},
	{
		"id": "corner_specialist",
		"name": "Corner Specialist",
		"category": "shooting",
		"description": "+8 corner threes; +3 catch and shoot.",
		"effect": { "attributeModifiers": {
			"offense.corner3": 8,
			"offense.catchAndShoot": 3
		} },
		"stackable": false
	},
	{
		"id": "iron_man",
		"name": "Iron Man",
		"category": "defense",
		"description": "+6 stamina; +5 durability.",
		"effect": { "attributeModifiers": {
			"physical.stamina": 6,
			"physical.durability": 5
		} },
		"stackable": false
	},
	{
		"id": "switchable",
		"name": "Switchable",
		"category": "defense",
		"description": "+6 pick and roll defense; +4 perimeter defense; +4 interior defense.",
		"effect": { "attributeModifiers": {
			"defense.pickAndRollDefense": 6,
			"defense.perimeterDefense": 4,
			"defense.interiorDefense": 4
		} },
		"stackable": false
	},
	{
		"id": "floor_general",
		"name": "Floor General",
		"category": "passing",
		"description": "+5 passing IQ; +5 decision making; +3 ball security.",
		"effect": { "attributeModifiers": {
			"offense.passingIQ": 5,
			"offense.decisionMaking": 5,
			"offense.ballSecurity": 3
		} },
		"stackable": false
	}
];
const EXPERIMENTAL_BADGES = [
	{
		id: "perfect_shooter",
		name: "Perfect Shooter",
		category: "experimental",
		description: "Eligible shots always go in.",
		effect: { flags: { perfectShooter: true } }
	},
	{
		id: "perfect_blocker",
		name: "Perfect Blocker",
		category: "experimental",
		description: "Eligible block attempts always succeed.",
		effect: { flags: { perfectBlocker: true } }
	},
	{
		id: "perfect_steal",
		name: "Perfect Steal",
		category: "experimental",
		description: "Eligible steal attempts always succeed.",
		effect: { flags: { perfectStealer: true } }
	},
	{
		id: "never_turnover",
		name: "Never Turnover",
		category: "experimental",
		description: "Player cannot lose the ball.",
		effect: { flags: { neverTurnover: true } }
	},
	{
		id: "infinite_stamina",
		name: "Infinite Stamina",
		category: "experimental",
		description: "Fatigue never increases.",
		effect: { flags: { infiniteStamina: true } }
	},
	{
		id: "unlimited_range",
		name: "Unlimited Range",
		category: "experimental",
		description: "Distance does not negatively affect shooting.",
		effect: { flags: { unlimitedRange: true } }
	},
	{
		id: "god_speed",
		name: "God Speed",
		category: "experimental",
		description: "Extreme speed multiplier.",
		effect: { flags: { speedMultiplier: 5 } }
	},
	{
		id: "clutch_god",
		name: "Clutch God",
		category: "experimental",
		description: "Massive clutch boost.",
		effect: { attributeModifiers: { "mental.clutch": 100 } }
	},
	{
		id: "playoff_god",
		name: "Playoff God",
		category: "experimental",
		description: "Massive playoff boost.",
		effect: { attributeModifiers: { "mental.playoffPerformance": 100 } }
	},
	{
		id: "no_injury",
		name: "No Injury",
		category: "experimental",
		description: "Player cannot become injured.",
		effect: { flags: { noInjury: true } }
	},
	{
		id: "no_foul",
		name: "No Foul",
		category: "experimental",
		description: "Player cannot commit fouls.",
		effect: { flags: { noFoul: true } }
	},
	{
		id: "automatic_assist",
		name: "Automatic Assist",
		category: "experimental",
		description: "Eligible passes automatically create high-quality assists.",
		effect: { flags: { automaticAssist: true } }
	},
	{
		id: "rebound_god",
		name: "Rebound God",
		category: "experimental",
		description: "Extreme rebounding success.",
		effect: { flags: { reboundMultiplier: 8 } }
	},
	{
		id: "gravity",
		name: "Gravity",
		category: "experimental",
		description: "Defenders are strongly attracted to the player.",
		effect: { flags: { gravityMultiplier: 6 } }
	},
	{
		id: "unblockable_shot",
		name: "Unblockable Shot",
		category: "experimental",
		description: "Shot cannot be blocked.",
		effect: { flags: { unblockableShot: true } }
	},
	{
		id: "unstealable_ball",
		name: "Unstealable Ball",
		category: "experimental",
		description: "Ball cannot be stolen.",
		effect: { flags: { unstealableBall: true } }
	},
	{
		id: "infinite_vertical",
		name: "Infinite Vertical",
		category: "experimental",
		description: "Extreme jumping ability.",
		effect: { flags: { verticalMultiplier: 8 } }
	}
];
[...NORMAL_BADGES, ...EXPERIMENTAL_BADGES];
//#endregion
//#region src/simulation/types.ts
function emptySeasonStatTotals() {
	return {
		gamesPlayed: 0,
		minutes: 0,
		points: 0,
		fgm: 0,
		fga: 0,
		tpm: 0,
		tpa: 0,
		ftm: 0,
		fta: 0,
		oreb: 0,
		dreb: 0,
		ast: 0,
		stl: 0,
		blk: 0,
		tov: 0,
		pf: 0,
		ba: 0,
		blkAtt: 0,
		clutchPoints: 0
	};
}
Object.keys(emptySeasonStatTotals());
//#endregion
//#region src/simulation/archetypes.ts
const P = (PG, SG, SF, PF, C) => ({
	PG,
	SG,
	SF,
	PF,
	C
});
/** 1.0 is "at the player's overall caliber"; >1 is a strength, <1 is a real weakness. */
const ARCHETYPES = [
	{
		key: "twoWayStar",
		label: "Two-Way Star",
		weight: 4,
		groups: {
			finishing: 1.15,
			postGame: .95,
			midrange: 1.1,
			threePoint: 1.05,
			freeThrow: 1.05,
			handling: 1.1,
			passing: 1.05,
			offBall: 1.1,
			perimeterD: 1.15,
			interiorD: 1,
			steals: 1.1,
			blocks: 1,
			rebounding: 1,
			defensiveIQ: 1.15,
			athleticism: 1.15,
			strength: 1.05,
			size: 1.02
		},
		positions: P(25, 70, 80, 40, 5),
		roleHints: {
			shotCreator: 78,
			primaryBallHandler: 60,
			perimeterDefender: 80
		},
		ballDominance: 72,
		ballHandlerPriority: 78,
		minutesBand: [32, 38]
	},
	{
		key: "threeLevelScorer",
		label: "Three-Level Scorer",
		weight: 6,
		groups: {
			finishing: 1.15,
			postGame: 1,
			midrange: 1.2,
			threePoint: 1.15,
			freeThrow: 1.1,
			handling: 1.15,
			passing: .9,
			offBall: 1.05,
			perimeterD: .85,
			interiorD: .8,
			steals: .9,
			blocks: .8,
			rebounding: .85,
			defensiveIQ: .85,
			athleticism: 1.1,
			strength: .95,
			size: 1
		},
		positions: P(30, 80, 65, 20, 0),
		roleHints: {
			shotCreator: 88,
			isolationScorer: 85,
			primaryBallHandler: 55
		},
		ballDominance: 80,
		ballHandlerPriority: 80,
		minutesBand: [30, 37]
	},
	{
		key: "floorGeneral",
		label: "Floor General",
		weight: 6,
		groups: {
			finishing: .95,
			postGame: .8,
			midrange: 1,
			threePoint: 1,
			freeThrow: 1.1,
			handling: 1.25,
			passing: 1.3,
			offBall: 1.15,
			perimeterD: .95,
			interiorD: .75,
			steals: 1.1,
			blocks: .7,
			rebounding: .8,
			defensiveIQ: 1.05,
			athleticism: 1,
			strength: .85,
			size: .88
		},
		positions: P(90, 40, 10, 0, 0),
		roleHints: {
			primaryBallHandler: 92,
			playmaker: 90,
			pnrBallHandler: 85
		},
		ballDominance: 82,
		ballHandlerPriority: 90,
		minutesBand: [29, 36]
	},
	{
		key: "threeAndD",
		label: "3&D Wing",
		weight: 9,
		groups: {
			finishing: .95,
			postGame: .8,
			midrange: .9,
			threePoint: 1.25,
			freeThrow: 1.05,
			handling: .85,
			passing: .85,
			offBall: 1.25,
			perimeterD: 1.25,
			interiorD: .9,
			steals: 1.15,
			blocks: .9,
			rebounding: .9,
			defensiveIQ: 1.2,
			athleticism: 1.05,
			strength: 1,
			size: 1
		},
		positions: P(10, 60, 85, 35, 0),
		roleHints: {
			spotUpShooter: 88,
			catchAndShoot: 88,
			perimeterDefender: 88
		},
		ballDominance: 30,
		ballHandlerPriority: 25,
		minutesBand: [26, 34]
	},
	{
		key: "defensiveSpecialist",
		label: "Defensive Specialist",
		weight: 6,
		groups: {
			finishing: .85,
			postGame: .75,
			midrange: .75,
			threePoint: .75,
			freeThrow: .85,
			handling: .85,
			passing: .9,
			offBall: .95,
			perimeterD: 1.35,
			interiorD: 1.15,
			steals: 1.3,
			blocks: 1.05,
			rebounding: 1,
			defensiveIQ: 1.35,
			athleticism: 1.15,
			strength: 1.1,
			size: 1
		},
		positions: P(45, 70, 60, 20, 0),
		roleHints: {
			perimeterDefender: 95,
			pointOfAttackDefender: 92
		},
		ballDominance: 22,
		ballHandlerPriority: 20,
		minutesBand: [22, 31]
	},
	{
		key: "rimProtector",
		label: "Rim Protector",
		weight: 7,
		groups: {
			finishing: 1.05,
			postGame: .95,
			midrange: .7,
			threePoint: .55,
			freeThrow: .75,
			handling: .6,
			passing: .75,
			offBall: .9,
			perimeterD: .75,
			interiorD: 1.35,
			steals: .8,
			blocks: 1.45,
			rebounding: 1.3,
			defensiveIQ: 1.2,
			athleticism: .95,
			strength: 1.25,
			size: 1.2
		},
		positions: P(0, 0, 5, 45, 92),
		roleHints: {
			rimProtector: 95,
			pnrScreener: 82,
			interiorDefender: 92
		},
		ballDominance: 20,
		ballHandlerPriority: 10,
		minutesBand: [24, 33]
	},
	{
		key: "stretchBig",
		label: "Stretch Big",
		weight: 6,
		groups: {
			finishing: 1,
			postGame: .95,
			midrange: 1.1,
			threePoint: 1.2,
			freeThrow: 1.05,
			handling: .8,
			passing: .95,
			offBall: 1.15,
			perimeterD: .8,
			interiorD: .95,
			steals: .85,
			blocks: 1,
			rebounding: 1.1,
			defensiveIQ: .95,
			athleticism: .9,
			strength: 1.1,
			size: 1.15
		},
		positions: P(0, 5, 25, 80, 60),
		roleHints: {
			spotUpShooter: 82,
			pnrScreener: 75,
			stretchBig: 90
		},
		ballDominance: 28,
		ballHandlerPriority: 15,
		minutesBand: [24, 33]
	},
	{
		key: "glassCleaner",
		label: "Glass Cleaner",
		weight: 5,
		groups: {
			finishing: 1.1,
			postGame: 1.05,
			midrange: .7,
			threePoint: .5,
			freeThrow: .7,
			handling: .6,
			passing: .75,
			offBall: .9,
			perimeterD: .7,
			interiorD: 1.2,
			steals: .85,
			blocks: 1.1,
			rebounding: 1.45,
			defensiveIQ: 1,
			athleticism: 1.05,
			strength: 1.3,
			size: 1.18
		},
		positions: P(0, 0, 8, 65, 85),
		roleHints: {
			rebounder: 95,
			pnrScreener: 78,
			interiorDefender: 85
		},
		ballDominance: 20,
		ballHandlerPriority: 8,
		minutesBand: [22, 31]
	},
	{
		key: "slasher",
		label: "Slasher",
		weight: 7,
		groups: {
			finishing: 1.3,
			postGame: .9,
			midrange: .95,
			threePoint: .7,
			freeThrow: .95,
			handling: 1.1,
			passing: .95,
			offBall: 1,
			perimeterD: 1,
			interiorD: .9,
			steals: 1.05,
			blocks: .9,
			rebounding: .95,
			defensiveIQ: .95,
			athleticism: 1.3,
			strength: 1.05,
			size: .98
		},
		positions: P(20, 65, 80, 30, 0),
		roleHints: {
			slasher: 92,
			cutter: 85,
			shotCreator: 65
		},
		ballDominance: 58,
		ballHandlerPriority: 55,
		minutesBand: [26, 34]
	},
	{
		key: "sharpshooter",
		label: "Sharpshooter",
		weight: 7,
		groups: {
			finishing: .85,
			postGame: .7,
			midrange: 1.15,
			threePoint: 1.35,
			freeThrow: 1.2,
			handling: .9,
			passing: .9,
			offBall: 1.3,
			perimeterD: .8,
			interiorD: .7,
			steals: .9,
			blocks: .7,
			rebounding: .8,
			defensiveIQ: .9,
			athleticism: .95,
			strength: .9,
			size: .95
		},
		positions: P(25, 85, 55, 10, 0),
		roleHints: {
			spotUpShooter: 92,
			catchAndShoot: 95,
			movementShooter: 88
		},
		ballDominance: 32,
		ballHandlerPriority: 28,
		minutesBand: [24, 33]
	},
	{
		key: "pointForward",
		label: "Point Forward",
		weight: 4,
		groups: {
			finishing: 1.1,
			postGame: 1,
			midrange: 1.05,
			threePoint: .95,
			freeThrow: 1,
			handling: 1.15,
			passing: 1.25,
			offBall: 1.1,
			perimeterD: 1,
			interiorD: .95,
			steals: 1,
			blocks: .9,
			rebounding: 1.1,
			defensiveIQ: 1.05,
			athleticism: 1.05,
			strength: 1.1,
			size: 1.08
		},
		positions: P(35, 45, 85, 60, 10),
		roleHints: {
			primaryBallHandler: 78,
			playmaker: 85,
			shotCreator: 70
		},
		ballDominance: 70,
		ballHandlerPriority: 72,
		minutesBand: [28, 36]
	},
	{
		key: "sixthMan",
		label: "Sixth Man",
		weight: 8,
		groups: {
			finishing: 1.05,
			postGame: .85,
			midrange: 1.1,
			threePoint: 1.1,
			freeThrow: 1.05,
			handling: 1.1,
			passing: 1,
			offBall: 1.05,
			perimeterD: .9,
			interiorD: .8,
			steals: .95,
			blocks: .8,
			rebounding: .85,
			defensiveIQ: .9,
			athleticism: 1.05,
			strength: .95,
			size: .97
		},
		positions: P(45, 75, 55, 15, 0),
		roleHints: {
			shotCreator: 72,
			spotUpShooter: 65,
			sparkPlug: 88
		},
		ballDominance: 58,
		ballHandlerPriority: 52,
		minutesBand: [18, 26]
	},
	{
		key: "energyBig",
		label: "Energy Big",
		weight: 6,
		groups: {
			finishing: 1.15,
			postGame: .85,
			midrange: .65,
			threePoint: .45,
			freeThrow: .7,
			handling: .6,
			passing: .7,
			offBall: .9,
			perimeterD: .75,
			interiorD: 1.1,
			steals: .85,
			blocks: 1.05,
			rebounding: 1.25,
			defensiveIQ: .95,
			athleticism: 1.15,
			strength: 1.2,
			size: 1.12
		},
		positions: P(0, 0, 10, 70, 75),
		roleHints: {
			rebounder: 85,
			cutter: 80,
			pnrScreener: 80
		},
		ballDominance: 18,
		ballHandlerPriority: 8,
		minutesBand: [14, 24]
	},
	{
		key: "connector",
		label: "Connector",
		weight: 8,
		groups: {
			finishing: 1,
			postGame: .85,
			midrange: 1,
			threePoint: 1.05,
			freeThrow: 1,
			handling: 1,
			passing: 1.15,
			offBall: 1.15,
			perimeterD: 1.05,
			interiorD: .95,
			steals: 1.05,
			blocks: .9,
			rebounding: 1,
			defensiveIQ: 1.15,
			athleticism: 1,
			strength: 1,
			size: 1
		},
		positions: P(30, 55, 75, 45, 5),
		roleHints: {
			spotUpShooter: 72,
			playmaker: 70,
			perimeterDefender: 72
		},
		ballDominance: 40,
		ballHandlerPriority: 38,
		minutesBand: [22, 30]
	},
	{
		key: "rawProspect",
		label: "Raw Prospect",
		weight: 7,
		groups: {
			finishing: .95,
			postGame: .8,
			midrange: .8,
			threePoint: .8,
			freeThrow: .85,
			handling: .9,
			passing: .85,
			offBall: .85,
			perimeterD: .9,
			interiorD: .9,
			steals: .9,
			blocks: .95,
			rebounding: .95,
			defensiveIQ: .75,
			athleticism: 1.25,
			strength: .95,
			size: 1.05
		},
		positions: P(25, 55, 60, 40, 15),
		roleHints: {
			slasher: 60,
			cutter: 60
		},
		ballDominance: 35,
		ballHandlerPriority: 30,
		minutesBand: [10, 20]
	},
	{
		key: "journeyman",
		label: "Journeyman",
		weight: 10,
		groups: {
			finishing: .92,
			postGame: .88,
			midrange: .92,
			threePoint: .9,
			freeThrow: .95,
			handling: .9,
			passing: .92,
			offBall: .95,
			perimeterD: .92,
			interiorD: .9,
			steals: .92,
			blocks: .88,
			rebounding: .92,
			defensiveIQ: .95,
			athleticism: .9,
			strength: .95,
			size: 1
		},
		positions: P(35, 55, 60, 40, 15),
		roleHints: {},
		ballDominance: 30,
		ballHandlerPriority: 25,
		minutesBand: [8, 18]
	}
];
{
	const base = ARCHETYPES.find((a) => a.key === "floorGeneral");
	ARCHETYPES.push({
		...base,
		key: "deepRangeCreator",
		label: "Deep Range Creator",
		weight: 4,
		groups: {
			...base.groups,
			threePoint: 1.38,
			handling: 1.28,
			passing: 1.12,
			finishing: .92,
			perimeterD: .82
		},
		positions: P(90, 70, 15, 0, 0),
		roleHints: {
			...base.roleHints,
			shotCreator: 95,
			pnrBallHandler: 92,
			primaryBallHandler: 92
		},
		ballDominance: 88,
		ballHandlerPriority: 94,
		minutesBand: [30, 37]
	});
}
{
	const base = ARCHETYPES.find((a) => a.key === "stretchBig");
	ARCHETYPES.push({
		...base,
		key: "pointCenter",
		label: "Point Center",
		weight: 3,
		groups: {
			...base.groups,
			passing: 1.38,
			postGame: 1.2,
			handling: .98,
			rebounding: 1.18,
			athleticism: .82
		},
		positions: P(15, 0, 15, 65, 95),
		roleHints: {
			...base.roleHints,
			playmaker: 95,
			postScorer: 82,
			pnrScreener: 80
		},
		ballDominance: 75,
		ballHandlerPriority: 76,
		minutesBand: [29, 36]
	});
}
{
	const base = ARCHETYPES.find((a) => a.key === "rimProtector");
	ARCHETYPES.push({
		...base,
		key: "switchBig",
		label: "Switch Defender",
		weight: 5,
		groups: {
			...base.groups,
			perimeterD: 1.25,
			interiorD: 1.25,
			athleticism: 1.18,
			blocks: 1.15,
			threePoint: .72,
			strength: 1.12
		},
		positions: P(0, 10, 55, 92, 75),
		roleHints: {
			...base.roleHints,
			perimeterDefender: 88,
			interiorDefender: 90,
			pointOfAttackDefender: 80
		},
		ballDominance: 25,
		ballHandlerPriority: 18,
		minutesBand: [24, 32]
	});
}
{
	const base = ARCHETYPES.find((a) => a.key === "glassCleaner");
	ARCHETYPES.push({
		...base,
		key: "postTechnician",
		label: "Post Technician",
		weight: 4,
		groups: {
			...base.groups,
			postGame: 1.4,
			finishing: 1.2,
			midrange: 1.18,
			passing: 1.05,
			rebounding: 1.12,
			athleticism: .78
		},
		positions: P(0, 0, 20, 90, 80),
		roleHints: {
			...base.roleHints,
			postScorer: 96,
			isolationScorer: 78,
			pnrScreener: 70
		},
		ballDominance: 67,
		ballHandlerPriority: 45,
		minutesBand: [26, 34]
	});
}
{
	const base = ARCHETYPES.find((a) => a.key === "sharpshooter");
	ARCHETYPES.push({
		...base,
		key: "movementSniper",
		label: "Movement Sniper",
		weight: 5,
		groups: {
			...base.groups,
			offBall: 1.42,
			threePoint: 1.3,
			athleticism: 1.15,
			handling: .82,
			passing: .85
		},
		positions: P(15, 95, 65, 5, 0),
		roleHints: {
			...base.roleHints,
			movementShooter: 99,
			catchAndShoot: 96,
			spotUpShooter: 75,
			cutter: 80
		},
		ballDominance: 34,
		ballHandlerPriority: 20,
		minutesBand: [23, 32]
	});
}
{
	const base = ARCHETYPES.find((a) => a.key === "connector");
	ARCHETYPES.push({
		...base,
		key: "defensivePlaymaker",
		label: "Defensive Playmaker",
		weight: 4,
		groups: {
			...base.groups,
			passing: 1.26,
			defensiveIQ: 1.32,
			perimeterD: 1.22,
			steals: 1.22,
			threePoint: .85,
			midrange: .88
		},
		positions: P(70, 60, 75, 35, 0),
		roleHints: {
			...base.roleHints,
			playmaker: 87,
			pointOfAttackDefender: 90,
			perimeterDefender: 88
		},
		ballDominance: 46,
		ballHandlerPriority: 60,
		minutesBand: [24, 33]
	});
}
//#endregion
//#region src/simulation/awards.ts
const DEFAULT_MVP_WEIGHTS = {
	ppg: 1,
	apg: 1.5,
	rpg: 1.2,
	spg: 1.5,
	bpg: 1.5,
	tov: -.5,
	teamWinPct: 10,
	efficiency: 0,
	winShares: 1.2
};
const DEFAULT_DPOY_WEIGHTS = {
	spg: 3,
	bpg: 3,
	rpg: .3,
	defensiveIQ: .1,
	defensiveWinShares: 1.8
};
({ ...DEFAULT_MVP_WEIGHTS }), { ...DEFAULT_DPOY_WEIGHTS };
//#endregion
//#region src/simulation/leagueRules.ts
const DEFAULT_LEAGUE_RULES = {
	minutesVariance: 50,
	rotationStintMinutes: 5,
	blowoutBenchThreshold: 22,
	personalFoulLimit: 6,
	coachingImpact: 100,
	allStarEnabled: true,
	allStarBreakPercent: 58,
	allStarFanWeight: 50,
	allStarPlayerWeight: 25,
	allStarCoachWeight: 25,
	teamsPerConference: 15,
	numberOfConferences: 2,
	divisionsEnabled: true,
	teamsPerDivision: 5,
	numberOfDivisions: 6,
	expansionEnabled: false,
	expansionFrequencyYears: 5,
	expansionTeamCount: 1,
	relocationEnabled: false,
	relocationFrequencyYears: 10,
	contractionEnabled: false,
	contractionFrequencyYears: 10,
	minimumTeams: 4,
	maximumTeams: 32,
	conferenceAlignment: "geographic",
	divisionAlignment: "geographic",
	protectedRivalries: true,
	rivalryScheduleFrequency: 50,
	leagueRealignmentFrequencyYears: 0,
	gamesPerSeason: 82,
	minimumGamesPerTeam: 82,
	maximumGamesPerTeam: 82,
	homeAwayBalance: 50,
	divisionGameFrequency: 50,
	conferenceGameFrequency: 60,
	nonConferenceGameFrequency: 40,
	rivalryGameFrequency: 50,
	backToBackFrequency: 50,
	maxConsecutiveRoadGames: 5,
	maxConsecutiveHomeGames: 5,
	restDaysBetweenGames: 1,
	travelDistanceConsideration: false,
	travelFatigue: 30,
	scheduleStrengthWeighting: 50,
	scheduleRandomness: 50,
	christmasGames: true,
	openingNightGames: true,
	rivalryWeek: false,
	finalWeekSchedulingRules: "standard",
	numberOfTimeouts: 7,
	timeoutCarryover: false,
	teamFoulLimit: 5,
	bonusRuleFoulCount: 5,
	doubleBonusFoulCount: 10,
	defensiveThreeSecondsEnabled: true,
	offensiveThreeSecondsEnabled: true,
	fiveSecondInbound: true,
	eightSecondBackcourt: true,
	backcourtViolationEnabled: true,
	goaltendingRules: true,
	basketInterference: true,
	travelingStrictness: 50,
	carryingStrictness: 50,
	illegalScreenFrequency: 50,
	floppingPenalties: true,
	technicalFoulFrequency: 50,
	ejectionRulesStrictness: 50,
	overtimePossessionRules: "jump-ball",
	jumpBallFrequency: 50,
	possessionsPerGame: 100,
	offensiveEfficiency: 50,
	defensiveEfficiency: 50,
	shotFrequency: 50,
	threePointFrequency: 50,
	midrangeFrequency: 50,
	rimFrequency: 50,
	dunkFrequency: 50,
	layupFrequency: 50,
	freeThrowFrequency: 50,
	offensiveReboundFrequency: 50,
	defensiveReboundFrequency: 50,
	assistFrequency: 50,
	stealFrequency: 50,
	blockFrequency: 50,
	fastBreakFrequency: 50,
	transitionFrequency: 50,
	isolationFrequency: 50,
	pickAndRollFrequency: 50,
	postUpFrequency: 50,
	offBallMovement: 50,
	shotClockUsage: 50,
	threePointDifficulty: 50,
	midrangeDifficulty: 50,
	layupDifficulty: 50,
	dunkSuccessRate: 70,
	freeThrowDifficulty: 50,
	contestedShotPenalty: 50,
	openShotBonus: 50,
	wideOpenShotBonus: 60,
	defenderProximityImpact: 50,
	shotCreationDifficulty: 50,
	pullUpShootingDifficulty: 50,
	stepBackShootingDifficulty: 50,
	fadeawayDifficulty: 50,
	catchAndShootBonus: 50,
	cornerThreeBonus: 50,
	aboveBreakThreeDifficulty: 50,
	longTwoFrequency: 30,
	heavilyContestedShotFrequency: 40,
	shotQualityImportance: 50,
	hotColdStreakImpact: 30,
	perimeterDefenseImpact: 50,
	interiorDefenseImpact: 50,
	helpDefense: 50,
	defensiveRotations: 50,
	closeoutEffectiveness: 50,
	contestEffectiveness: 50,
	stealSuccess: 50,
	blockSuccess: 50,
	chargeFrequency: 30,
	deflectionFrequency: 40,
	screenNavigation: 50,
	pickAndRollDefense: 50,
	postDefense: 50,
	rimProtection: 50,
	transitionDefense: 50,
	defensiveCommunication: 50,
	defensiveIQImpact: 50,
	defensiveMatchupImportance: 50,
	positionMismatchPenalty: 50,
	defensiveVersatility: 50,
	developmentSpeed: 100,
	developmentRandomness: 100,
	potentialAccuracy: 70,
	potentialVolatility: 30,
	ageDevelopmentCurve: "standard",
	rookieDevelopmentBonus: 100,
	youngPlayerDevelopment: 100,
	primeDevelopment: 100,
	veteranDevelopment: 100,
	lateCareerDecline: 100,
	athleticDecline: 50,
	shootingDevelopment: 50,
	finishingDevelopment: 50,
	passingDevelopment: 50,
	defenseDevelopment: 50,
	reboundingDevelopment: 50,
	mentalDevelopment: 50,
	developmentFromPlayingTime: 100,
	developmentFromCoaching: 50,
	developmentFromTraining: 50,
	agingRandomness: 50,
	peakAgeShiftYears: 0,
	peakDurationYears: 3,
	declineStartingAgeShiftYears: 0,
	declineSpeed: 100,
	athleticDeclineRate: 50,
	shootingDeclineRate: 40,
	defensiveDeclineRate: 45,
	durabilityDeclineRate: 40,
	injuryRelatedDecline: 50,
	veteranConsistency: 50,
	lateCareerResurgenceChance: 10,
	retirementAgeShiftYears: 0,
	earlyRetirementChance: 0,
	forcedRetirementChance: 0,
	minorInjuryFrequency: 50,
	majorInjuryFrequency: 20,
	careerEndingInjuriesEnabled: false,
	injurySeverityRandomness: 50,
	recoveryTimeMultiplier: 100,
	reinjuryChance: 20,
	injuryProneImpact: 50,
	durabilityAttributeImpact: 50,
	fatigueInjuryImpact: 50,
	overuseInjuryImpact: 50,
	playoffInjuryFrequency: 50,
	practiceInjuryFrequency: 20,
	trainingInjuryFrequency: 20,
	injuryTreatmentEffectiveness: 50,
	medicalStaffImpact: 50,
	injuryRecoveryDevelopment: 30,
	longTermInjuryEffects: false,
	injuryReportingDetail: "detailed",
	minimumTeamSalaryPct: 90,
	maximumContractLengthYears: 5,
	rookieContractLengthYears: 4,
	minimumSalary: 12e5,
	maximumSalary: 55e6,
	veteranMinimum: 25e5,
	birdRightsEnabled: true,
	earlyBirdRightsEnabled: true,
	midLevelExceptionAmount: 128e5,
	biAnnualExceptionAmount: 45e5,
	tradeExceptionsEnabled: true,
	contractInflationPct: 3,
	salaryGrowthPct: 3,
	revenueGrowthPct: 3,
	ticketRevenueWeight: 40,
	merchandiseRevenueWeight: 20,
	tvRevenueWeight: 30,
	sponsorshipRevenueWeight: 10,
	teamProfitabilityImpact: 30,
	tradeFrequency: 50,
	tradeAIAggressiveness: 50,
	tradeDeadlineEnabled: true,
	tradeRestrictionsEnabled: true,
	noTradeClausesEnabled: false,
	playerTradeRequestsEnabled: false,
	playerTradeResistance: 50,
	aiRebuildingTendency: 50,
	aiWinNowTendency: 50,
	aiValueOfDraftPicks: 50,
	aiValueOfProspects: 50,
	aiValueOfVeterans: 50,
	tradeRandomness: 30,
	tradeVetoSystemEnabled: false,
	tradeEvaluationStrictness: 50,
	multiTeamTradesEnabled: false,
	signAndTradesEnabled: false,
	draftPickProtectionsEnabled: false,
	futurePickTradingEnabled: false,
	playerDemandVariance: 50,
	playerLoyalty: 50,
	homeTeamPreference: 50,
	winningPreference: 50,
	moneyPreference: 50,
	playingTimePreference: 50,
	marketSizePreference: 30,
	championshipPreference: 50,
	teamReputationImpact: 30,
	contractNegotiationDifficulty: 50,
	freeAgentRandomness: 50,
	aiFreeAgentAggressiveness: 50,
	aiOverpayTendency: 30,
	freeAgentTamperingEnabled: false,
	signAndTradeFrequency: 20,
	veteranDiscountTendency: 30,
	maxContractFrequency: 20,
	freeAgentRetirementDecisions: true
};
//#endregion
//#region src/simulation/engine/ruleMods.ts
/**
* Every field here defaults to a neutral 1 (or 0 where an additive shift, called out below) when
* `rules` is undefined or a given field is left at ITS OWN default - so a game simulated with no
* rules produces IDENTICAL output to before this file existed. Crucially, the League Rules panel
* does NOT use one universal baseline: development/aging fields default to 100 (proportional,
* `value / 100`), while nearly every Shooting/Defense/Simulation-Engine field defaults to 50 (or
* another field-specific value like 70 or 30) instead. `mult()` below divides by each field's own
* real default from DEFAULT_LEAGUE_RULES rather than assuming 100, so "no rules" and "rules left at
* their shipped defaults" always produce the identical 1x multiplier regardless of which baseline
* that particular field happens to use.
*
* A handful of Shooting/Simulation-Engine/Defense fields are deliberately left out (still inert):
* shotFrequency, offBallMovement, shotClockUsage, hotColdStreakImpact, deflectionFrequency,
* screenNavigation, defensiveCommunication, defensiveMatchupImportance, positionMismatchPenalty,
* defensiveVersatility. Each would need a genuinely new mechanic (shot-clock modeling, per-player
* streak tracking, a deflections stat, discrete screen events, matchup-quality detection) rather
* than a multiplier on something that already exists, so wiring them here would be a fake connection.
*/
function mult(rules, key) {
	const def = DEFAULT_LEAGUE_RULES[key];
	const value = rules?.[key] ?? def;
	return def === 0 ? 1 : value / def;
}
function computeRuleMods(rules) {
	return {
		shot: {
			threePointDifficulty: mult(rules, "threePointDifficulty"),
			midrangeDifficulty: mult(rules, "midrangeDifficulty"),
			layupDifficulty: mult(rules, "layupDifficulty"),
			dunkSuccess: mult(rules, "dunkSuccessRate"),
			pullUpDifficulty: mult(rules, "pullUpShootingDifficulty"),
			stepBackDifficulty: mult(rules, "stepBackShootingDifficulty"),
			fadeawayDifficulty: mult(rules, "fadeawayDifficulty"),
			catchAndShootBonus: mult(rules, "catchAndShootBonus"),
			cornerThreeBonus: mult(rules, "cornerThreeBonus"),
			aboveBreakThreeDifficulty: mult(rules, "aboveBreakThreeDifficulty"),
			contestedShotPenalty: mult(rules, "contestedShotPenalty"),
			openShotBonus: mult(rules, "openShotBonus"),
			wideOpenShotBonus: mult(rules, "wideOpenShotBonus"),
			perimeterDefenseImpact: mult(rules, "perimeterDefenseImpact"),
			interiorDefenseImpact: mult(rules, "interiorDefenseImpact"),
			closeoutEffectiveness: mult(rules, "closeoutEffectiveness"),
			contestEffectiveness: mult(rules, "contestEffectiveness"),
			defenderProximityImpact: mult(rules, "defenderProximityImpact"),
			shotQualityImportance: mult(rules, "shotQualityImportance"),
			shotCreationDifficulty: mult(rules, "shotCreationDifficulty"),
			heavilyContestedShotFrequency: mult(rules, "heavilyContestedShotFrequency"),
			offensiveEfficiency: mult(rules, "offensiveEfficiency"),
			defensiveEfficiency: mult(rules, "defensiveEfficiency"),
			pickAndRollDefense: mult(rules, "pickAndRollDefense"),
			postDefense: mult(rules, "postDefense"),
			transitionDefense: mult(rules, "transitionDefense"),
			defensiveIQImpact: mult(rules, "defensiveIQImpact"),
			freeThrowDifficulty: mult(rules, "freeThrowDifficulty")
		},
		turnover: {
			stealFrequency: mult(rules, "stealFrequency"),
			stealSuccess: mult(rules, "stealSuccess"),
			chargeFrequency: mult(rules, "chargeFrequency"),
			perimeterDefenseImpact: mult(rules, "perimeterDefenseImpact")
		},
		shotTypeWeight: {
			three: mult(rules, "threePointFrequency"),
			mid: mult(rules, "midrangeFrequency"),
			rim: mult(rules, "rimFrequency"),
			dunk: mult(rules, "dunkFrequency"),
			layup: mult(rules, "layupFrequency"),
			longTwo: mult(rules, "longTwoFrequency")
		},
		action: {
			isolation: mult(rules, "isolationFrequency"),
			pnr: mult(rules, "pickAndRollFrequency"),
			postUp: mult(rules, "postUpFrequency"),
			transition: mult(rules, "fastBreakFrequency") * mult(rules, "transitionFrequency")
		},
		reboundOffense: mult(rules, "offensiveReboundFrequency"),
		reboundDefense: mult(rules, "defensiveReboundFrequency"),
		assistFrequency: mult(rules, "assistFrequency"),
		blockFrequency: mult(rules, "blockFrequency"),
		blockSuccess: mult(rules, "blockSuccess"),
		rimProtection: mult(rules, "rimProtection"),
		freeThrowFrequency: mult(rules, "freeThrowFrequency"),
		doubleTeamFrequency: mult(rules, "helpDefense") * mult(rules, "defensiveRotations"),
		paceMultiplier: mult(rules, "possessionsPerGame")
	};
}
computeRuleMods(void 0);
//#endregion
//#region src/hunt/eras.ts
const ERAS = [
	{
		id: "60s",
		label: "The 1960s",
		from: 1955,
		to: 1969,
		pace: 85,
		threes: "none",
		handCheck: true,
		blurb: "No three-point line. Run, rebound, run again. Big men rule."
	},
	{
		id: "70s",
		label: "The 1970s",
		from: 1970,
		to: 1979,
		pace: 70,
		threes: "none",
		handCheck: true,
		blurb: "Still no three. Physical, fast, and all about the paint."
	},
	{
		id: "80s",
		label: "The 1980s",
		from: 1980,
		to: 1989,
		pace: 68,
		threes: "rare",
		handCheck: true,
		blurb: "The three arrives but nobody trusts it. Showtime and Celtic pride."
	},
	{
		id: "90s",
		label: "The 1990s",
		from: 1990,
		to: 1999,
		pace: 42,
		threes: "rare",
		handCheck: true,
		blurb: "Hand-checking, elbows, grind-it-out half-court. Defense wins."
	},
	{
		id: "00s",
		label: "The 2000s",
		from: 2e3,
		to: 2009,
		pace: 45,
		threes: "normal",
		handCheck: false,
		blurb: "Hand-checking gone in 2004-05; the drive-and-kick era begins."
	},
	{
		id: "10s",
		label: "The 2010s",
		from: 2010,
		to: 2019,
		pace: 60,
		threes: "heavy",
		handCheck: false,
		blurb: "Pace and space. Threes rain down; shooters are gold."
	},
	{
		id: "20s",
		label: "Today",
		from: 2020,
		to: 2030,
		pace: 66,
		threes: "heavy",
		handCheck: false,
		blurb: "Everyone shoots. Fast, spaced and relentless."
	}
];
//#endregion
//#region src/hunt/coaches.ts
const c = (id, name, bonus, style, franchises, blurb) => ({
	id,
	name,
	bonus,
	style,
	franchises,
	blurb
});
const COACHES = [
	c("jackson", "Phil Jackson", 5, "triangle", ["CHI", "LAL"], "Eleven rings and the triangle."),
	c("auerbach", "Red Auerbach", 5, "pace", ["BOS"], "Nine titles and a victory cigar."),
	c("popovich", "Gregg Popovich", 5, "defense", ["SAS"], "Five titles, two decades of winning."),
	c("riley", "Pat Riley", 4, "defense", [
		"LAL",
		"NYK",
		"MIA"
	], "Showtime, then elbows in New York."),
	c("kerr", "Steve Kerr", 4, "threes", ["GSW"], "Motion, splash and four titles."),
	c("daly", "Chuck Daly", 4, "defense", ["DET"], "The Bad Boys and the Dream Team."),
	c("spoelstra", "Erik Spoelstra", 4, "balanced", ["MIA"], "Any roster, any system."),
	c("holzman", "Red Holzman", 3, "triangle", ["NYK"], "Hit the open man."),
	c("sloan", "Jerry Sloan", 3, "balanced", ["UTA", "CHI"], "Pick-and-roll, every night, for 23 years."),
	c("lbrown", "Larry Brown", 3, "defense", [
		"DET",
		"PHI",
		"IND",
		"DEN",
		"SAS"
	], "Play the right way."),
	c("kcjones", "K.C. Jones", 3, "balanced", ["BOS"], "Let the 80s Celtics be the 80s Celtics."),
	c("rudyt", "Rudy Tomjanovich", 3, "threes", ["HOU"], "Never underestimate the heart of a champion."),
	c("heinsohn", "Tom Heinsohn", 3, "pace", ["BOS"], "Run, press, run."),
	c("rivers", "Doc Rivers", 3, "defense", [
		"BOS",
		"LAC",
		"ORL",
		"PHI"
	], "Ubuntu."),
	c("carlisle", "Rick Carlisle", 2, "balanced", [
		"DAL",
		"IND",
		"DET"
	], "Beat the Heatles in 2011."),
	c("wilkens", "Lenny Wilkens", 2, "balanced", [
		"SEA",
		"ATL",
		"CLE"
	], "More wins than almost anyone."),
	c("nelson", "Don Nelson", 2, "pace", [
		"MIL",
		"GSW",
		"DAL"
	], "Nellie Ball: small, fast, weird."),
	c("dantoni", "Mike D'Antoni", 2, "pace", ["PHO", "HOU"], "Seven seconds or less."),
	c("nurse", "Nick Nurse", 2, "defense", ["TOR"], "Box-and-one in the Finals."),
	c("budenholzer", "Mike Budenholzer", 2, "threes", ["MIL", "ATL"], "Spread it out around a giant."),
	c("thibodeau", "Tom Thibodeau", 2, "defense", [
		"CHI",
		"NYK",
		"MIN"
	], "Load up the strong side."),
	c("karl", "George Karl", 2, "pace", [
		"SEA",
		"DEN",
		"MIL"
	], "Push it, press it."),
	c("fitch", "Bill Fitch", 2, "balanced", [
		"BOS",
		"HOU",
		"CLE"
	], "Turned the Celtics around in one year."),
	c("lue", "Tyronn Lue", 2, "balanced", ["CLE", "LAC"], "Came back from 3-1."),
	c("hannum", "Alex Hannum", 2, "defense", [
		"PHI",
		"STL",
		"SFW"
	], "The coach who beat Russell."),
	c("cunningham", "Billy Cunningham", 2, "pace", ["PHI"], "Fo, fi, fo."),
	c("malone", "Michael Malone", 2, "balanced", ["DEN"], "Built around a passing center."),
	c("hbrown", "Hubie Brown", 1, "balanced", [
		"ATL",
		"NYK",
		"MEM"
	], "Explains the game better than anyone."),
	c("jvg", "Jeff Van Gundy", 1, "defense", ["NYK", "HOU"], "Grind it out."),
	c("svg", "Stan Van Gundy", 1, "threes", [
		"ORL",
		"MIA",
		"DET"
	], "One big and four shooters."),
	c("collins", "Doug Collins", 1, "balanced", [
		"CHI",
		"DET",
		"WAS",
		"PHI"
	], "Young teams, fast turnarounds."),
	c("motta", "Dick Motta", 1, "balanced", [
		"WSB",
		"CHI",
		"DAL"
	], "The opera ain't over till the fat lady sings."),
	c("ramsay", "Jack Ramsay", 1, "pace", [
		"POR",
		"PHI",
		"IND"
	], "Blazermania."),
	c("fitzsimmons", "Cotton Fitzsimmons", 1, "balanced", [
		"PHO",
		"KCK",
		"ATL"
	], "Always got the most out of a roster."),
	c("westhead", "Paul Westhead", 1, "pace", ["LAL", "DEN"], "Fastest offense ever run."),
	c("vogel", "Frank Vogel", 1, "defense", [
		"IND",
		"LAL",
		"ORL"
	], "Size and defense."),
	c("mazzulla", "Joe Mazzulla", 1, "threes", ["BOS"], "Math: threes are worth more."),
	c("playercoach", "Player-Coach Gary", 0, "balanced", [], "Plays 10 minutes, coaches the other 38."),
	c("legend", "The Local High School Legend", 0, "pace", [], "Won state in 1987 and never stopped talking about it."),
	c("interim", "The Interim Coach", -1, "balanced", [], "Nobody told him how long \"interim\" is."),
	c("promoted", "The Assistant Promoted Tuesday", -1, "balanced", [], "Still learning where the timeout button is."),
	c("nephew", "The Owner's Nephew", -2, "threes", [], "Read a blog post about analytics.")
];
new Map(COACHES.map((x) => [x.id, x]));
//#endregion
//#region src/hunt/pvp.ts
/** Elo: the expected score and the change for the challenger (K = 32). */
function eloDelta(challenger, defender, won, k = 32) {
	const expected = 1 / (1 + 10 ** ((defender - challenger) / 400));
	return Math.round(k * ((won ? 1 : 0) - expected));
}
//#endregion
//#region server/supabase.ts
const pick = (env, ...names) => names.map((n) => env[n]).find((v) => !!v);
function supaEnv(env = globalThis.process?.env ?? {}) {
	const url = pick(env, "SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_URL", "VITE_SUPABASE_URL");
	const serviceKey = pick(env, "SUPABASE_SERVICE_ROLE_KEY", "SUPABASE_SECRET_KEY");
	const publicKey = pick(env, "SUPABASE_ANON_KEY", "NEXT_PUBLIC_SUPABASE_ANON_KEY", "SUPABASE_PUBLISHABLE_KEY", "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_ANON_KEY") ?? serviceKey;
	return url && serviceKey && publicKey ? {
		url: url.replace(/\/$/, ""),
		serviceKey,
		publicKey
	} : null;
}
/** New-style keys (sb_…) go in the apikey header only; legacy JWT keys also as the bearer token. */
const keyHeaders = (key) => key.startsWith("sb_") ? { apikey: key } : {
	apikey: key,
	Authorization: `Bearer ${key}`
};
/** The signed-in user behind an access token, or null. */
async function getUser(env, token, f = fetch) {
	const res = await f(`${env.url}/auth/v1/user`, { headers: {
		apikey: env.publicKey,
		Authorization: `Bearer ${token}`
	} });
	if (!res.ok) return null;
	const u = await res.json();
	return u.id ? {
		id: u.id,
		email: u.email
	} : null;
}
/** A PostgREST call with the service key (row level security does not apply). */
async function rest(env, method, path, body, prefer, f = fetch) {
	const res = await f(`${env.url}/rest/v1/${path}`, {
		method,
		headers: {
			...keyHeaders(env.serviceKey),
			"Content-Type": "application/json",
			...prefer ? { Prefer: prefer } : {}
		},
		...body !== void 0 ? { body: JSON.stringify(body) } : {}
	});
	if (!res.ok) throw new Error(`${method} ${path.split("?")[0]}: ${res.status} ${(await res.text()).slice(0, 200)}`);
	const text = await res.text();
	return text ? JSON.parse(text) : null;
}
const upsert = (env, table, rows, onConflict, f) => rows.length ? rest(env, "POST", `${table}?on_conflict=${onConflict}`, rows, "resolution=merge-duplicates,return=minimal", f) : Promise.resolve(null);
const json = (body, status = 200) => new Response(JSON.stringify(body), {
	status,
	headers: {
		"Content-Type": "application/json",
		"Cache-Control": "no-store"
	}
});
const bearer = (req) => req.headers.get("authorization")?.match(/^Bearer\s+(.+)$/i)?.[1] ?? null;
//#endregion
//#region server/pvp.ts
const STALE_MS = 12e5;
function ghostShapeOk(g) {
	const x = g;
	return !!x && Array.isArray(x.squad) && x.squad.length === 6 && x.squad.every((id) => typeof id === "string" && id.length < 80) && Array.isArray(x.items) && x.items.length <= 6 && Array.isArray(x.boosts) && x.boosts.length <= 3 && typeof x.growth === "object" && typeof x.training === "object" && JSON.stringify(g).length < 4e3;
}
async function ghost(env, id, f) {
	return (await rest(env, "GET", `hunt_ghosts?user_id=eq.${id}&select=*`, void 0, void 0, f))[0] ?? null;
}
async function settle(env, m, won, games, f) {
	const [me, them] = await Promise.all([ghost(env, m.challenger, f), ghost(env, m.defender, f)]);
	const delta = eloDelta(me?.rating ?? 1e3, them?.rating ?? 1e3, won);
	await rest(env, "PATCH", `pvp_matches?id=eq.${m.id}&status=eq.pending`, {
		status: won ? "won" : "lost",
		games,
		delta
	}, "return=minimal", f);
	if (me) await rest(env, "PATCH", `hunt_ghosts?user_id=eq.${m.challenger}`, {
		rating: me.rating + delta,
		wins: me.wins + (won ? 1 : 0),
		losses: me.losses + (won ? 0 : 1)
	}, "return=minimal", f);
	if (them) await rest(env, "PATCH", `hunt_ghosts?user_id=eq.${m.defender}`, {
		rating: them.rating - delta,
		wins: them.wins + (won ? 0 : 1),
		losses: them.losses + (won ? 1 : 0)
	}, "return=minimal", f);
	return delta;
}
async function handlePvp(req, env, now = /* @__PURE__ */ new Date(), f = fetch, random = Math.random) {
	if (!env) return json({ error: "Accounts are not set up on this site yet." }, 503);
	const token = bearer(req);
	const user = token ? await getUser(env, token, f).catch(() => null) : null;
	if (!user) return json({ error: "Please sign in again." }, 401);
	if (req.method !== "POST") return json({ error: "Method not allowed." }, 405);
	let body;
	try {
		body = JSON.parse(await req.text());
	} catch {
		return json({ error: "Bad request." }, 400);
	}
	const me = user.id;
	try {
		if (body.action === "publish") {
			if (!ghostShapeOk(body.ghost)) return json({ error: "That squad cannot be published." }, 400);
			await upsert(env, "hunt_ghosts", [{
				user_id: me,
				squad: body.ghost,
				updated_at: now.toISOString()
			}], "user_id", f);
			return json({ ok: true });
		}
		if (body.action === "find") {
			const mine = await ghost(env, me, f);
			if (!mine) return json({ error: "Finish a League Hunt first: your squad becomes your PvP team." }, 400);
			const pending = await rest(env, "GET", `pvp_matches?challenger=eq.${me}&status=eq.pending&select=*&order=created_at.desc`, void 0, void 0, f);
			for (const m of pending) if (now.getTime() - Date.parse(m.created_at) > STALE_MS) await settle(env, m, false, null, f);
			let match = pending.find((m) => now.getTime() - Date.parse(m.created_at) <= STALE_MS) ?? null;
			if (!match) {
				const r = mine.rating;
				const [up, down] = await Promise.all([rest(env, "GET", `hunt_ghosts?user_id=neq.${me}&rating=gte.${r}&select=user_id,rating&order=rating.asc&limit=15`, void 0, void 0, f), rest(env, "GET", `hunt_ghosts?user_id=neq.${me}&rating=lt.${r}&select=user_id,rating&order=rating.desc&limit=15`, void 0, void 0, f)]);
				const recent = await rest(env, "GET", `pvp_matches?challenger=eq.${me}&select=defender&order=created_at.desc&limit=3`, void 0, void 0, f);
				let pool = [...up, ...down].filter((g) => !recent.some((x) => x.defender === g.user_id));
				if (!pool.length) pool = [...up, ...down];
				if (!pool.length) return json({ error: "No opponents yet. Invite a friend: their finished hunt becomes a ghost to play." }, 404);
				const opp = pool[Math.floor(random() * pool.length)];
				match = (await rest(env, "POST", "pvp_matches", [{
					challenger: me,
					defender: opp.user_id,
					seed: Math.floor(random() * 1e9),
					era: ERAS[Math.floor(random() * ERAS.length)].id,
					created_at: now.toISOString()
				}], "return=representation", f))[0];
			}
			const [opp] = await rest(env, "GET", `lb_pvp?user_id=eq.${match.defender}&select=user_id,username,title,rating,wins,losses,squad`, void 0, void 0, f);
			if (!opp) {
				await settle(env, match, false, null, f);
				return json({ error: "That opponent is gone. Try again." }, 409);
			}
			return json({
				match: {
					id: match.id,
					seed: Number(match.seed),
					era: match.era
				},
				you: {
					rating: mine.rating,
					squad: mine.squad
				},
				opponent: opp
			});
		}
		if (body.action === "result") {
			const [m] = await rest(env, "GET", `pvp_matches?id=eq.${encodeURIComponent(String(body.matchId))}&challenger=eq.${me}&select=*`, void 0, void 0, f);
			if (!m || m.status !== "pending") return json({ error: "That match is already settled." }, 409);
			const games = Array.isArray(body.games) ? body.games.slice(0, 7) : [];
			const wins = games.filter((g) => g?.won).length, losses = games.length - wins;
			if (!(games.length >= 4 && (body.won ? wins === 4 && losses <= 3 : losses === 4 && wins <= 3))) return json({ error: "That result does not add up." }, 400);
			const delta = await settle(env, m, !!body.won, games, f);
			return json({
				ok: true,
				delta
			});
		}
		return json({ error: "Unknown action." }, 400);
	} catch {
		return json({ error: "PvP is having trouble. Try again soon." }, 502);
	}
}
//#endregion
//#region server/api-pvp.ts
const POST = (request) => handlePvp(request, supaEnv());
//#endregion
export { POST };
