// Generated by scripts/build-api.mjs from server/api-sync.ts. Do not edit; run npm run build:api.
//#region src/lib/kv.ts
const localRead = (key) => {
	try {
		return localStorage.getItem(key);
	} catch {
		return null;
	}
};
const objectRead = (data) => (key) => Object.prototype.hasOwnProperty.call(data, key) ? data[key] : null;
//#endregion
//#region src/lib/names.ts
const BLOCKED = [
	"fuck",
	"shit",
	"cunt",
	"nigg",
	"fag",
	"bitch",
	"whore",
	"rape",
	"nazi",
	"hitler",
	"slut",
	"retard",
	"penis",
	"vagina",
	"porn"
];
const isClean = (s) => {
	const flat = s.toLowerCase().replace(/[^a-z]/g, "");
	return !BLOCKED.some((w) => flat.includes(w));
};
/** A created player's name for the public boards: letters, digits, spaces and . \' - (2-24), or null. */
function cleanName(raw, max = 24) {
	if (typeof raw !== "string") return null;
	const name = raw.normalize("NFC").replace(/\s+/g, " ").trim();
	if (!/^[\p{L}\p{N}][\p{L}\p{N} ._'-]*$/u.test(name) || name.length < 2 || name.length > max) return null;
	return isClean(name) ? name : null;
}
//#endregion
//#region src/simulation/badges.ts
const NORMAL_BADGES = [
	{
		"id": "deep_range",
		"name": "Deep Range",
		"category": "shooting",
		"description": "+6 three point; +5 above-the-break threes.",
		"effect": { "attributeModifiers": {
			"offense.threePoint": 6,
			"offense.aboveBreak3": 5
		} },
		"stackable": false
	},
	{
		"id": "deadeye",
		"name": "Deadeye",
		"category": "shooting",
		"description": "+7 shot IQ; +3 offensive consistency.",
		"effect": { "attributeModifiers": {
			"offense.shotIQ": 7,
			"offense.offensiveConsistency": 3
		} },
		"stackable": false
	},
	{
		"id": "quick_release",
		"name": "Quick Release",
		"category": "shooting",
		"description": "+5 catch and shoot; +5 offensive IQ.",
		"effect": { "attributeModifiers": {
			"offense.catchAndShoot": 5,
			"offense.offensiveIQ": 5
		} },
		"stackable": false
	},
	{
		"id": "catch_and_shoot",
		"name": "Catch & Shoot",
		"category": "shooting",
		"description": "+8 catch and shoot; +4 corner threes.",
		"effect": { "attributeModifiers": {
			"offense.catchAndShoot": 8,
			"offense.corner3": 4
		} },
		"stackable": false
	},
	{
		"id": "difficult_shots",
		"name": "Difficult Shots",
		"category": "shooting",
		"description": "+6 midrange; +5 post fade; +3 shot IQ.",
		"effect": { "attributeModifiers": {
			"offense.midrange": 6,
			"offense.postFade": 5,
			"offense.shotIQ": 3
		} },
		"stackable": false
	},
	{
		"id": "pullup_specialist",
		"name": "Pull-Up Specialist",
		"category": "shooting",
		"description": "+8 pull-up threes; +4 long midrange.",
		"effect": { "attributeModifiers": {
			"offense.pullUp3": 8,
			"offense.longMidrange": 4
		} },
		"stackable": false
	},
	{
		"id": "handles",
		"name": "Handles",
		"category": "ballhandling",
		"description": "+7 ball handling; +3 speed with ball.",
		"effect": { "attributeModifiers": {
			"offense.ballHandling": 7,
			"offense.speedWithBall": 3
		} },
		"stackable": false
	},
	{
		"id": "unpluckable",
		"name": "Unpluckable",
		"category": "ballhandling",
		"description": "+8 ball security.",
		"effect": { "attributeModifiers": { "offense.ballSecurity": 8 } },
		"stackable": false
	},
	{
		"id": "tight_handle",
		"name": "Tight Handle",
		"category": "ballhandling",
		"description": "+4 ball handling; +5 decision making.",
		"effect": { "attributeModifiers": {
			"offense.ballHandling": 4,
			"offense.decisionMaking": 5
		} },
		"stackable": false
	},
	{
		"id": "speed_booster",
		"name": "Speed Booster",
		"category": "ballhandling",
		"description": "+7 speed with ball; +3 acceleration.",
		"effect": { "attributeModifiers": {
			"offense.speedWithBall": 7,
			"physical.acceleration": 3
		} },
		"stackable": false
	},
	{
		"id": "rim_protector",
		"name": "Rim Protector",
		"category": "defense",
		"description": "+6 rim protection; +5 block.",
		"effect": { "attributeModifiers": {
			"defense.rimProtection": 6,
			"defense.block": 5
		} },
		"stackable": false
	},
	{
		"id": "lockdown",
		"name": "Lockdown",
		"category": "defense",
		"description": "+7 perimeter defense; +4 contest.",
		"effect": { "attributeModifiers": {
			"defense.perimeterDefense": 7,
			"defense.contest": 4
		} },
		"stackable": false
	},
	{
		"id": "interceptor",
		"name": "Interceptor",
		"category": "defense",
		"description": "+7 passing lane steal; +4 steal IQ.",
		"effect": { "attributeModifiers": {
			"defense.passingLaneSteal": 7,
			"defense.stealIQ": 4
		} },
		"stackable": false
	},
	{
		"id": "pick_pocket",
		"name": "Pick Pocket",
		"category": "defense",
		"description": "+7 on ball steal; +4 steal.",
		"effect": { "attributeModifiers": {
			"defense.onBallSteal": 7,
			"defense.steal": 4
		} },
		"stackable": false
	},
	{
		"id": "chase_down",
		"name": "Chase Down",
		"category": "defense",
		"description": "+6 block timing; +3 speed; +3 vertical.",
		"effect": { "attributeModifiers": {
			"defense.blockTiming": 6,
			"physical.speed": 3,
			"physical.vertical": 3
		} },
		"stackable": false
	},
	{
		"id": "contact_finisher",
		"name": "Contact Finisher",
		"category": "finishing",
		"description": "+6 finishing; +4 strength.",
		"effect": { "attributeModifiers": {
			"offense.finishing": 6,
			"physical.strength": 4
		} },
		"stackable": false
	},
	{
		"id": "acrobat",
		"name": "Acrobat",
		"category": "finishing",
		"description": "+7 driving layup; +4 touch.",
		"effect": { "attributeModifiers": {
			"offense.drivingLayup": 7,
			"offense.touch": 4
		} },
		"stackable": false
	},
	{
		"id": "posterizer",
		"name": "Posterizer",
		"category": "finishing",
		"description": "+7 driving dunk; +4 vertical.",
		"effect": { "attributeModifiers": {
			"offense.drivingDunk": 7,
			"physical.vertical": 4
		} },
		"stackable": false
	},
	{
		"id": "dimer",
		"name": "Dimer",
		"category": "passing",
		"description": "+6 passing IQ; +4 passing.",
		"effect": { "attributeModifiers": {
			"offense.passingIQ": 6,
			"offense.passing": 4
		} },
		"stackable": false
	},
	{
		"id": "needle_threader",
		"name": "Needle Threader",
		"category": "passing",
		"description": "+7 passing accuracy; +3 passing.",
		"effect": { "attributeModifiers": {
			"offense.passingAccuracy": 7,
			"offense.passing": 3
		} },
		"stackable": false
	},
	{
		"id": "bail_out",
		"name": "Bail Out",
		"category": "passing",
		"description": "+6 decision making; +4 passing accuracy.",
		"effect": { "attributeModifiers": {
			"offense.decisionMaking": 6,
			"offense.passingAccuracy": 4
		} },
		"stackable": false
	},
	{
		"id": "glass_cleaner",
		"name": "Glass Cleaner",
		"category": "defense",
		"description": "+7 defensive rebounding; +5 offensive rebounding.",
		"effect": { "attributeModifiers": {
			"defense.defensiveRebounding": 7,
			"offense.offensiveRebounding": 5
		} },
		"stackable": false
	},
	{
		"id": "post_craft",
		"name": "Post Craft",
		"category": "finishing",
		"description": "+6 post control; +5 post hook; +4 post fade.",
		"effect": { "attributeModifiers": {
			"offense.postControl": 6,
			"offense.postHook": 5,
			"offense.postFade": 4
		} },
		"stackable": false
	},
	{
		"id": "corner_specialist",
		"name": "Corner Specialist",
		"category": "shooting",
		"description": "+8 corner threes; +3 catch and shoot.",
		"effect": { "attributeModifiers": {
			"offense.corner3": 8,
			"offense.catchAndShoot": 3
		} },
		"stackable": false
	},
	{
		"id": "iron_man",
		"name": "Iron Man",
		"category": "defense",
		"description": "+6 stamina; +5 durability.",
		"effect": { "attributeModifiers": {
			"physical.stamina": 6,
			"physical.durability": 5
		} },
		"stackable": false
	},
	{
		"id": "switchable",
		"name": "Switchable",
		"category": "defense",
		"description": "+6 pick and roll defense; +4 perimeter defense; +4 interior defense.",
		"effect": { "attributeModifiers": {
			"defense.pickAndRollDefense": 6,
			"defense.perimeterDefense": 4,
			"defense.interiorDefense": 4
		} },
		"stackable": false
	},
	{
		"id": "floor_general",
		"name": "Floor General",
		"category": "passing",
		"description": "+5 passing IQ; +5 decision making; +3 ball security.",
		"effect": { "attributeModifiers": {
			"offense.passingIQ": 5,
			"offense.decisionMaking": 5,
			"offense.ballSecurity": 3
		} },
		"stackable": false
	}
];
const EXPERIMENTAL_BADGES = [
	{
		id: "perfect_shooter",
		name: "Perfect Shooter",
		category: "experimental",
		description: "Eligible shots always go in.",
		effect: { flags: { perfectShooter: true } }
	},
	{
		id: "perfect_blocker",
		name: "Perfect Blocker",
		category: "experimental",
		description: "Eligible block attempts always succeed.",
		effect: { flags: { perfectBlocker: true } }
	},
	{
		id: "perfect_steal",
		name: "Perfect Steal",
		category: "experimental",
		description: "Eligible steal attempts always succeed.",
		effect: { flags: { perfectStealer: true } }
	},
	{
		id: "never_turnover",
		name: "Never Turnover",
		category: "experimental",
		description: "Player cannot lose the ball.",
		effect: { flags: { neverTurnover: true } }
	},
	{
		id: "infinite_stamina",
		name: "Infinite Stamina",
		category: "experimental",
		description: "Fatigue never increases.",
		effect: { flags: { infiniteStamina: true } }
	},
	{
		id: "unlimited_range",
		name: "Unlimited Range",
		category: "experimental",
		description: "Distance does not negatively affect shooting.",
		effect: { flags: { unlimitedRange: true } }
	},
	{
		id: "god_speed",
		name: "God Speed",
		category: "experimental",
		description: "Extreme speed multiplier.",
		effect: { flags: { speedMultiplier: 5 } }
	},
	{
		id: "clutch_god",
		name: "Clutch God",
		category: "experimental",
		description: "Massive clutch boost.",
		effect: { attributeModifiers: { "mental.clutch": 100 } }
	},
	{
		id: "playoff_god",
		name: "Playoff God",
		category: "experimental",
		description: "Massive playoff boost.",
		effect: { attributeModifiers: { "mental.playoffPerformance": 100 } }
	},
	{
		id: "no_injury",
		name: "No Injury",
		category: "experimental",
		description: "Player cannot become injured.",
		effect: { flags: { noInjury: true } }
	},
	{
		id: "no_foul",
		name: "No Foul",
		category: "experimental",
		description: "Player cannot commit fouls.",
		effect: { flags: { noFoul: true } }
	},
	{
		id: "automatic_assist",
		name: "Automatic Assist",
		category: "experimental",
		description: "Eligible passes automatically create high-quality assists.",
		effect: { flags: { automaticAssist: true } }
	},
	{
		id: "rebound_god",
		name: "Rebound God",
		category: "experimental",
		description: "Extreme rebounding success.",
		effect: { flags: { reboundMultiplier: 8 } }
	},
	{
		id: "gravity",
		name: "Gravity",
		category: "experimental",
		description: "Defenders are strongly attracted to the player.",
		effect: { flags: { gravityMultiplier: 6 } }
	},
	{
		id: "unblockable_shot",
		name: "Unblockable Shot",
		category: "experimental",
		description: "Shot cannot be blocked.",
		effect: { flags: { unblockableShot: true } }
	},
	{
		id: "unstealable_ball",
		name: "Unstealable Ball",
		category: "experimental",
		description: "Ball cannot be stolen.",
		effect: { flags: { unstealableBall: true } }
	},
	{
		id: "infinite_vertical",
		name: "Infinite Vertical",
		category: "experimental",
		description: "Extreme jumping ability.",
		effect: { flags: { verticalMultiplier: 8 } }
	}
];
[...NORMAL_BADGES, ...EXPERIMENTAL_BADGES];
//#endregion
//#region src/simulation/types.ts
function emptySeasonStatTotals() {
	return {
		gamesPlayed: 0,
		minutes: 0,
		points: 0,
		fgm: 0,
		fga: 0,
		tpm: 0,
		tpa: 0,
		ftm: 0,
		fta: 0,
		oreb: 0,
		dreb: 0,
		ast: 0,
		stl: 0,
		blk: 0,
		tov: 0,
		pf: 0,
		ba: 0,
		blkAtt: 0,
		clutchPoints: 0
	};
}
Object.keys(emptySeasonStatTotals());
//#endregion
//#region src/simulation/archetypes.ts
const P = (PG, SG, SF, PF, C) => ({
	PG,
	SG,
	SF,
	PF,
	C
});
/** 1.0 is "at the player's overall caliber"; >1 is a strength, <1 is a real weakness. */
const ARCHETYPES = [
	{
		key: "twoWayStar",
		label: "Two-Way Star",
		weight: 4,
		groups: {
			finishing: 1.15,
			postGame: .95,
			midrange: 1.1,
			threePoint: 1.05,
			freeThrow: 1.05,
			handling: 1.1,
			passing: 1.05,
			offBall: 1.1,
			perimeterD: 1.15,
			interiorD: 1,
			steals: 1.1,
			blocks: 1,
			rebounding: 1,
			defensiveIQ: 1.15,
			athleticism: 1.15,
			strength: 1.05,
			size: 1.02
		},
		positions: P(25, 70, 80, 40, 5),
		roleHints: {
			shotCreator: 78,
			primaryBallHandler: 60,
			perimeterDefender: 80
		},
		ballDominance: 72,
		ballHandlerPriority: 78,
		minutesBand: [32, 38]
	},
	{
		key: "threeLevelScorer",
		label: "Three-Level Scorer",
		weight: 6,
		groups: {
			finishing: 1.15,
			postGame: 1,
			midrange: 1.2,
			threePoint: 1.15,
			freeThrow: 1.1,
			handling: 1.15,
			passing: .9,
			offBall: 1.05,
			perimeterD: .85,
			interiorD: .8,
			steals: .9,
			blocks: .8,
			rebounding: .85,
			defensiveIQ: .85,
			athleticism: 1.1,
			strength: .95,
			size: 1
		},
		positions: P(30, 80, 65, 20, 0),
		roleHints: {
			shotCreator: 88,
			isolationScorer: 85,
			primaryBallHandler: 55
		},
		ballDominance: 80,
		ballHandlerPriority: 80,
		minutesBand: [30, 37]
	},
	{
		key: "floorGeneral",
		label: "Floor General",
		weight: 6,
		groups: {
			finishing: .95,
			postGame: .8,
			midrange: 1,
			threePoint: 1,
			freeThrow: 1.1,
			handling: 1.25,
			passing: 1.3,
			offBall: 1.15,
			perimeterD: .95,
			interiorD: .75,
			steals: 1.1,
			blocks: .7,
			rebounding: .8,
			defensiveIQ: 1.05,
			athleticism: 1,
			strength: .85,
			size: .88
		},
		positions: P(90, 40, 10, 0, 0),
		roleHints: {
			primaryBallHandler: 92,
			playmaker: 90,
			pnrBallHandler: 85
		},
		ballDominance: 82,
		ballHandlerPriority: 90,
		minutesBand: [29, 36]
	},
	{
		key: "threeAndD",
		label: "3&D Wing",
		weight: 9,
		groups: {
			finishing: .95,
			postGame: .8,
			midrange: .9,
			threePoint: 1.25,
			freeThrow: 1.05,
			handling: .85,
			passing: .85,
			offBall: 1.25,
			perimeterD: 1.25,
			interiorD: .9,
			steals: 1.15,
			blocks: .9,
			rebounding: .9,
			defensiveIQ: 1.2,
			athleticism: 1.05,
			strength: 1,
			size: 1
		},
		positions: P(10, 60, 85, 35, 0),
		roleHints: {
			spotUpShooter: 88,
			catchAndShoot: 88,
			perimeterDefender: 88
		},
		ballDominance: 30,
		ballHandlerPriority: 25,
		minutesBand: [26, 34]
	},
	{
		key: "defensiveSpecialist",
		label: "Defensive Specialist",
		weight: 6,
		groups: {
			finishing: .85,
			postGame: .75,
			midrange: .75,
			threePoint: .75,
			freeThrow: .85,
			handling: .85,
			passing: .9,
			offBall: .95,
			perimeterD: 1.35,
			interiorD: 1.15,
			steals: 1.3,
			blocks: 1.05,
			rebounding: 1,
			defensiveIQ: 1.35,
			athleticism: 1.15,
			strength: 1.1,
			size: 1
		},
		positions: P(45, 70, 60, 20, 0),
		roleHints: {
			perimeterDefender: 95,
			pointOfAttackDefender: 92
		},
		ballDominance: 22,
		ballHandlerPriority: 20,
		minutesBand: [22, 31]
	},
	{
		key: "rimProtector",
		label: "Rim Protector",
		weight: 7,
		groups: {
			finishing: 1.05,
			postGame: .95,
			midrange: .7,
			threePoint: .55,
			freeThrow: .75,
			handling: .6,
			passing: .75,
			offBall: .9,
			perimeterD: .75,
			interiorD: 1.35,
			steals: .8,
			blocks: 1.45,
			rebounding: 1.3,
			defensiveIQ: 1.2,
			athleticism: .95,
			strength: 1.25,
			size: 1.2
		},
		positions: P(0, 0, 5, 45, 92),
		roleHints: {
			rimProtector: 95,
			pnrScreener: 82,
			interiorDefender: 92
		},
		ballDominance: 20,
		ballHandlerPriority: 10,
		minutesBand: [24, 33]
	},
	{
		key: "stretchBig",
		label: "Stretch Big",
		weight: 6,
		groups: {
			finishing: 1,
			postGame: .95,
			midrange: 1.1,
			threePoint: 1.2,
			freeThrow: 1.05,
			handling: .8,
			passing: .95,
			offBall: 1.15,
			perimeterD: .8,
			interiorD: .95,
			steals: .85,
			blocks: 1,
			rebounding: 1.1,
			defensiveIQ: .95,
			athleticism: .9,
			strength: 1.1,
			size: 1.15
		},
		positions: P(0, 5, 25, 80, 60),
		roleHints: {
			spotUpShooter: 82,
			pnrScreener: 75,
			stretchBig: 90
		},
		ballDominance: 28,
		ballHandlerPriority: 15,
		minutesBand: [24, 33]
	},
	{
		key: "glassCleaner",
		label: "Glass Cleaner",
		weight: 5,
		groups: {
			finishing: 1.1,
			postGame: 1.05,
			midrange: .7,
			threePoint: .5,
			freeThrow: .7,
			handling: .6,
			passing: .75,
			offBall: .9,
			perimeterD: .7,
			interiorD: 1.2,
			steals: .85,
			blocks: 1.1,
			rebounding: 1.45,
			defensiveIQ: 1,
			athleticism: 1.05,
			strength: 1.3,
			size: 1.18
		},
		positions: P(0, 0, 8, 65, 85),
		roleHints: {
			rebounder: 95,
			pnrScreener: 78,
			interiorDefender: 85
		},
		ballDominance: 20,
		ballHandlerPriority: 8,
		minutesBand: [22, 31]
	},
	{
		key: "slasher",
		label: "Slasher",
		weight: 7,
		groups: {
			finishing: 1.3,
			postGame: .9,
			midrange: .95,
			threePoint: .7,
			freeThrow: .95,
			handling: 1.1,
			passing: .95,
			offBall: 1,
			perimeterD: 1,
			interiorD: .9,
			steals: 1.05,
			blocks: .9,
			rebounding: .95,
			defensiveIQ: .95,
			athleticism: 1.3,
			strength: 1.05,
			size: .98
		},
		positions: P(20, 65, 80, 30, 0),
		roleHints: {
			slasher: 92,
			cutter: 85,
			shotCreator: 65
		},
		ballDominance: 58,
		ballHandlerPriority: 55,
		minutesBand: [26, 34]
	},
	{
		key: "sharpshooter",
		label: "Sharpshooter",
		weight: 7,
		groups: {
			finishing: .85,
			postGame: .7,
			midrange: 1.15,
			threePoint: 1.35,
			freeThrow: 1.2,
			handling: .9,
			passing: .9,
			offBall: 1.3,
			perimeterD: .8,
			interiorD: .7,
			steals: .9,
			blocks: .7,
			rebounding: .8,
			defensiveIQ: .9,
			athleticism: .95,
			strength: .9,
			size: .95
		},
		positions: P(25, 85, 55, 10, 0),
		roleHints: {
			spotUpShooter: 92,
			catchAndShoot: 95,
			movementShooter: 88
		},
		ballDominance: 32,
		ballHandlerPriority: 28,
		minutesBand: [24, 33]
	},
	{
		key: "pointForward",
		label: "Point Forward",
		weight: 4,
		groups: {
			finishing: 1.1,
			postGame: 1,
			midrange: 1.05,
			threePoint: .95,
			freeThrow: 1,
			handling: 1.15,
			passing: 1.25,
			offBall: 1.1,
			perimeterD: 1,
			interiorD: .95,
			steals: 1,
			blocks: .9,
			rebounding: 1.1,
			defensiveIQ: 1.05,
			athleticism: 1.05,
			strength: 1.1,
			size: 1.08
		},
		positions: P(35, 45, 85, 60, 10),
		roleHints: {
			primaryBallHandler: 78,
			playmaker: 85,
			shotCreator: 70
		},
		ballDominance: 70,
		ballHandlerPriority: 72,
		minutesBand: [28, 36]
	},
	{
		key: "sixthMan",
		label: "Sixth Man",
		weight: 8,
		groups: {
			finishing: 1.05,
			postGame: .85,
			midrange: 1.1,
			threePoint: 1.1,
			freeThrow: 1.05,
			handling: 1.1,
			passing: 1,
			offBall: 1.05,
			perimeterD: .9,
			interiorD: .8,
			steals: .95,
			blocks: .8,
			rebounding: .85,
			defensiveIQ: .9,
			athleticism: 1.05,
			strength: .95,
			size: .97
		},
		positions: P(45, 75, 55, 15, 0),
		roleHints: {
			shotCreator: 72,
			spotUpShooter: 65,
			sparkPlug: 88
		},
		ballDominance: 58,
		ballHandlerPriority: 52,
		minutesBand: [18, 26]
	},
	{
		key: "energyBig",
		label: "Energy Big",
		weight: 6,
		groups: {
			finishing: 1.15,
			postGame: .85,
			midrange: .65,
			threePoint: .45,
			freeThrow: .7,
			handling: .6,
			passing: .7,
			offBall: .9,
			perimeterD: .75,
			interiorD: 1.1,
			steals: .85,
			blocks: 1.05,
			rebounding: 1.25,
			defensiveIQ: .95,
			athleticism: 1.15,
			strength: 1.2,
			size: 1.12
		},
		positions: P(0, 0, 10, 70, 75),
		roleHints: {
			rebounder: 85,
			cutter: 80,
			pnrScreener: 80
		},
		ballDominance: 18,
		ballHandlerPriority: 8,
		minutesBand: [14, 24]
	},
	{
		key: "connector",
		label: "Connector",
		weight: 8,
		groups: {
			finishing: 1,
			postGame: .85,
			midrange: 1,
			threePoint: 1.05,
			freeThrow: 1,
			handling: 1,
			passing: 1.15,
			offBall: 1.15,
			perimeterD: 1.05,
			interiorD: .95,
			steals: 1.05,
			blocks: .9,
			rebounding: 1,
			defensiveIQ: 1.15,
			athleticism: 1,
			strength: 1,
			size: 1
		},
		positions: P(30, 55, 75, 45, 5),
		roleHints: {
			spotUpShooter: 72,
			playmaker: 70,
			perimeterDefender: 72
		},
		ballDominance: 40,
		ballHandlerPriority: 38,
		minutesBand: [22, 30]
	},
	{
		key: "rawProspect",
		label: "Raw Prospect",
		weight: 7,
		groups: {
			finishing: .95,
			postGame: .8,
			midrange: .8,
			threePoint: .8,
			freeThrow: .85,
			handling: .9,
			passing: .85,
			offBall: .85,
			perimeterD: .9,
			interiorD: .9,
			steals: .9,
			blocks: .95,
			rebounding: .95,
			defensiveIQ: .75,
			athleticism: 1.25,
			strength: .95,
			size: 1.05
		},
		positions: P(25, 55, 60, 40, 15),
		roleHints: {
			slasher: 60,
			cutter: 60
		},
		ballDominance: 35,
		ballHandlerPriority: 30,
		minutesBand: [10, 20]
	},
	{
		key: "journeyman",
		label: "Journeyman",
		weight: 10,
		groups: {
			finishing: .92,
			postGame: .88,
			midrange: .92,
			threePoint: .9,
			freeThrow: .95,
			handling: .9,
			passing: .92,
			offBall: .95,
			perimeterD: .92,
			interiorD: .9,
			steals: .92,
			blocks: .88,
			rebounding: .92,
			defensiveIQ: .95,
			athleticism: .9,
			strength: .95,
			size: 1
		},
		positions: P(35, 55, 60, 40, 15),
		roleHints: {},
		ballDominance: 30,
		ballHandlerPriority: 25,
		minutesBand: [8, 18]
	}
];
{
	const base = ARCHETYPES.find((a) => a.key === "floorGeneral");
	ARCHETYPES.push({
		...base,
		key: "deepRangeCreator",
		label: "Deep Range Creator",
		weight: 4,
		groups: {
			...base.groups,
			threePoint: 1.38,
			handling: 1.28,
			passing: 1.12,
			finishing: .92,
			perimeterD: .82
		},
		positions: P(90, 70, 15, 0, 0),
		roleHints: {
			...base.roleHints,
			shotCreator: 95,
			pnrBallHandler: 92,
			primaryBallHandler: 92
		},
		ballDominance: 88,
		ballHandlerPriority: 94,
		minutesBand: [30, 37]
	});
}
{
	const base = ARCHETYPES.find((a) => a.key === "stretchBig");
	ARCHETYPES.push({
		...base,
		key: "pointCenter",
		label: "Point Center",
		weight: 3,
		groups: {
			...base.groups,
			passing: 1.38,
			postGame: 1.2,
			handling: .98,
			rebounding: 1.18,
			athleticism: .82
		},
		positions: P(15, 0, 15, 65, 95),
		roleHints: {
			...base.roleHints,
			playmaker: 95,
			postScorer: 82,
			pnrScreener: 80
		},
		ballDominance: 75,
		ballHandlerPriority: 76,
		minutesBand: [29, 36]
	});
}
{
	const base = ARCHETYPES.find((a) => a.key === "rimProtector");
	ARCHETYPES.push({
		...base,
		key: "switchBig",
		label: "Switch Defender",
		weight: 5,
		groups: {
			...base.groups,
			perimeterD: 1.25,
			interiorD: 1.25,
			athleticism: 1.18,
			blocks: 1.15,
			threePoint: .72,
			strength: 1.12
		},
		positions: P(0, 10, 55, 92, 75),
		roleHints: {
			...base.roleHints,
			perimeterDefender: 88,
			interiorDefender: 90,
			pointOfAttackDefender: 80
		},
		ballDominance: 25,
		ballHandlerPriority: 18,
		minutesBand: [24, 32]
	});
}
{
	const base = ARCHETYPES.find((a) => a.key === "glassCleaner");
	ARCHETYPES.push({
		...base,
		key: "postTechnician",
		label: "Post Technician",
		weight: 4,
		groups: {
			...base.groups,
			postGame: 1.4,
			finishing: 1.2,
			midrange: 1.18,
			passing: 1.05,
			rebounding: 1.12,
			athleticism: .78
		},
		positions: P(0, 0, 20, 90, 80),
		roleHints: {
			...base.roleHints,
			postScorer: 96,
			isolationScorer: 78,
			pnrScreener: 70
		},
		ballDominance: 67,
		ballHandlerPriority: 45,
		minutesBand: [26, 34]
	});
}
{
	const base = ARCHETYPES.find((a) => a.key === "sharpshooter");
	ARCHETYPES.push({
		...base,
		key: "movementSniper",
		label: "Movement Sniper",
		weight: 5,
		groups: {
			...base.groups,
			offBall: 1.42,
			threePoint: 1.3,
			athleticism: 1.15,
			handling: .82,
			passing: .85
		},
		positions: P(15, 95, 65, 5, 0),
		roleHints: {
			...base.roleHints,
			movementShooter: 99,
			catchAndShoot: 96,
			spotUpShooter: 75,
			cutter: 80
		},
		ballDominance: 34,
		ballHandlerPriority: 20,
		minutesBand: [23, 32]
	});
}
{
	const base = ARCHETYPES.find((a) => a.key === "connector");
	ARCHETYPES.push({
		...base,
		key: "defensivePlaymaker",
		label: "Defensive Playmaker",
		weight: 4,
		groups: {
			...base.groups,
			passing: 1.26,
			defensiveIQ: 1.32,
			perimeterD: 1.22,
			steals: 1.22,
			threePoint: .85,
			midrange: .88
		},
		positions: P(70, 60, 75, 35, 0),
		roleHints: {
			...base.roleHints,
			playmaker: 87,
			pointOfAttackDefender: 90,
			perimeterDefender: 88
		},
		ballDominance: 46,
		ballHandlerPriority: 60,
		minutesBand: [24, 33]
	});
}
//#endregion
//#region src/simulation/leagueRules.ts
const DEFAULT_LEAGUE_RULES = {
	minutesVariance: 50,
	rotationStintMinutes: 5,
	blowoutBenchThreshold: 22,
	personalFoulLimit: 6,
	coachingImpact: 100,
	allStarEnabled: true,
	allStarBreakPercent: 58,
	allStarFanWeight: 50,
	allStarPlayerWeight: 25,
	allStarCoachWeight: 25,
	teamsPerConference: 15,
	numberOfConferences: 2,
	divisionsEnabled: true,
	teamsPerDivision: 5,
	numberOfDivisions: 6,
	expansionEnabled: false,
	expansionFrequencyYears: 5,
	expansionTeamCount: 1,
	relocationEnabled: false,
	relocationFrequencyYears: 10,
	contractionEnabled: false,
	contractionFrequencyYears: 10,
	minimumTeams: 4,
	maximumTeams: 32,
	conferenceAlignment: "geographic",
	divisionAlignment: "geographic",
	protectedRivalries: true,
	rivalryScheduleFrequency: 50,
	leagueRealignmentFrequencyYears: 0,
	gamesPerSeason: 82,
	minimumGamesPerTeam: 82,
	maximumGamesPerTeam: 82,
	homeAwayBalance: 50,
	divisionGameFrequency: 50,
	conferenceGameFrequency: 60,
	nonConferenceGameFrequency: 40,
	rivalryGameFrequency: 50,
	backToBackFrequency: 50,
	maxConsecutiveRoadGames: 5,
	maxConsecutiveHomeGames: 5,
	restDaysBetweenGames: 1,
	travelDistanceConsideration: false,
	travelFatigue: 30,
	scheduleStrengthWeighting: 50,
	scheduleRandomness: 50,
	christmasGames: true,
	openingNightGames: true,
	rivalryWeek: false,
	finalWeekSchedulingRules: "standard",
	numberOfTimeouts: 7,
	timeoutCarryover: false,
	teamFoulLimit: 5,
	bonusRuleFoulCount: 5,
	doubleBonusFoulCount: 10,
	defensiveThreeSecondsEnabled: true,
	offensiveThreeSecondsEnabled: true,
	fiveSecondInbound: true,
	eightSecondBackcourt: true,
	backcourtViolationEnabled: true,
	goaltendingRules: true,
	basketInterference: true,
	travelingStrictness: 50,
	carryingStrictness: 50,
	illegalScreenFrequency: 50,
	floppingPenalties: true,
	technicalFoulFrequency: 50,
	ejectionRulesStrictness: 50,
	overtimePossessionRules: "jump-ball",
	jumpBallFrequency: 50,
	possessionsPerGame: 100,
	offensiveEfficiency: 50,
	defensiveEfficiency: 50,
	shotFrequency: 50,
	threePointFrequency: 50,
	midrangeFrequency: 50,
	rimFrequency: 50,
	dunkFrequency: 50,
	layupFrequency: 50,
	freeThrowFrequency: 50,
	offensiveReboundFrequency: 50,
	defensiveReboundFrequency: 50,
	assistFrequency: 50,
	stealFrequency: 50,
	blockFrequency: 50,
	fastBreakFrequency: 50,
	transitionFrequency: 50,
	isolationFrequency: 50,
	pickAndRollFrequency: 50,
	postUpFrequency: 50,
	offBallMovement: 50,
	shotClockUsage: 50,
	threePointDifficulty: 50,
	midrangeDifficulty: 50,
	layupDifficulty: 50,
	dunkSuccessRate: 70,
	freeThrowDifficulty: 50,
	contestedShotPenalty: 50,
	openShotBonus: 50,
	wideOpenShotBonus: 60,
	defenderProximityImpact: 50,
	shotCreationDifficulty: 50,
	pullUpShootingDifficulty: 50,
	stepBackShootingDifficulty: 50,
	fadeawayDifficulty: 50,
	catchAndShootBonus: 50,
	cornerThreeBonus: 50,
	aboveBreakThreeDifficulty: 50,
	longTwoFrequency: 30,
	heavilyContestedShotFrequency: 40,
	shotQualityImportance: 50,
	hotColdStreakImpact: 30,
	perimeterDefenseImpact: 50,
	interiorDefenseImpact: 50,
	helpDefense: 50,
	defensiveRotations: 50,
	closeoutEffectiveness: 50,
	contestEffectiveness: 50,
	stealSuccess: 50,
	blockSuccess: 50,
	chargeFrequency: 30,
	deflectionFrequency: 40,
	screenNavigation: 50,
	pickAndRollDefense: 50,
	postDefense: 50,
	rimProtection: 50,
	transitionDefense: 50,
	defensiveCommunication: 50,
	defensiveIQImpact: 50,
	defensiveMatchupImportance: 50,
	positionMismatchPenalty: 50,
	defensiveVersatility: 50,
	developmentSpeed: 100,
	developmentRandomness: 100,
	potentialAccuracy: 70,
	potentialVolatility: 30,
	ageDevelopmentCurve: "standard",
	rookieDevelopmentBonus: 100,
	youngPlayerDevelopment: 100,
	primeDevelopment: 100,
	veteranDevelopment: 100,
	lateCareerDecline: 100,
	athleticDecline: 50,
	shootingDevelopment: 50,
	finishingDevelopment: 50,
	passingDevelopment: 50,
	defenseDevelopment: 50,
	reboundingDevelopment: 50,
	mentalDevelopment: 50,
	developmentFromPlayingTime: 100,
	developmentFromCoaching: 50,
	developmentFromTraining: 50,
	agingRandomness: 50,
	peakAgeShiftYears: 0,
	peakDurationYears: 3,
	declineStartingAgeShiftYears: 0,
	declineSpeed: 100,
	athleticDeclineRate: 50,
	shootingDeclineRate: 40,
	defensiveDeclineRate: 45,
	durabilityDeclineRate: 40,
	injuryRelatedDecline: 50,
	veteranConsistency: 50,
	lateCareerResurgenceChance: 10,
	retirementAgeShiftYears: 0,
	earlyRetirementChance: 0,
	forcedRetirementChance: 0,
	minorInjuryFrequency: 50,
	majorInjuryFrequency: 20,
	careerEndingInjuriesEnabled: false,
	injurySeverityRandomness: 50,
	recoveryTimeMultiplier: 100,
	reinjuryChance: 20,
	injuryProneImpact: 50,
	durabilityAttributeImpact: 50,
	fatigueInjuryImpact: 50,
	overuseInjuryImpact: 50,
	playoffInjuryFrequency: 50,
	practiceInjuryFrequency: 20,
	trainingInjuryFrequency: 20,
	injuryTreatmentEffectiveness: 50,
	medicalStaffImpact: 50,
	injuryRecoveryDevelopment: 30,
	longTermInjuryEffects: false,
	injuryReportingDetail: "detailed",
	minimumTeamSalaryPct: 90,
	maximumContractLengthYears: 5,
	rookieContractLengthYears: 4,
	minimumSalary: 12e5,
	maximumSalary: 55e6,
	veteranMinimum: 25e5,
	birdRightsEnabled: true,
	earlyBirdRightsEnabled: true,
	midLevelExceptionAmount: 128e5,
	biAnnualExceptionAmount: 45e5,
	tradeExceptionsEnabled: true,
	contractInflationPct: 3,
	salaryGrowthPct: 3,
	revenueGrowthPct: 3,
	ticketRevenueWeight: 40,
	merchandiseRevenueWeight: 20,
	tvRevenueWeight: 30,
	sponsorshipRevenueWeight: 10,
	teamProfitabilityImpact: 30,
	tradeFrequency: 50,
	tradeAIAggressiveness: 50,
	tradeDeadlineEnabled: true,
	tradeRestrictionsEnabled: true,
	noTradeClausesEnabled: false,
	playerTradeRequestsEnabled: false,
	playerTradeResistance: 50,
	aiRebuildingTendency: 50,
	aiWinNowTendency: 50,
	aiValueOfDraftPicks: 50,
	aiValueOfProspects: 50,
	aiValueOfVeterans: 50,
	tradeRandomness: 30,
	tradeVetoSystemEnabled: false,
	tradeEvaluationStrictness: 50,
	multiTeamTradesEnabled: false,
	signAndTradesEnabled: false,
	draftPickProtectionsEnabled: false,
	futurePickTradingEnabled: false,
	playerDemandVariance: 50,
	playerLoyalty: 50,
	homeTeamPreference: 50,
	winningPreference: 50,
	moneyPreference: 50,
	playingTimePreference: 50,
	marketSizePreference: 30,
	championshipPreference: 50,
	teamReputationImpact: 30,
	contractNegotiationDifficulty: 50,
	freeAgentRandomness: 50,
	aiFreeAgentAggressiveness: 50,
	aiOverpayTendency: 30,
	freeAgentTamperingEnabled: false,
	signAndTradeFrequency: 20,
	veteranDiscountTendency: 30,
	maxContractFrequency: 20,
	freeAgentRetirementDecisions: true
};
//#endregion
//#region src/simulation/engine/ruleMods.ts
/**
* Every field here defaults to a neutral 1 (or 0 where an additive shift, called out below) when
* `rules` is undefined or a given field is left at ITS OWN default - so a game simulated with no
* rules produces IDENTICAL output to before this file existed. Crucially, the League Rules panel
* does NOT use one universal baseline: development/aging fields default to 100 (proportional,
* `value / 100`), while nearly every Shooting/Defense/Simulation-Engine field defaults to 50 (or
* another field-specific value like 70 or 30) instead. `mult()` below divides by each field's own
* real default from DEFAULT_LEAGUE_RULES rather than assuming 100, so "no rules" and "rules left at
* their shipped defaults" always produce the identical 1x multiplier regardless of which baseline
* that particular field happens to use.
*
* A handful of Shooting/Simulation-Engine/Defense fields are deliberately left out (still inert):
* shotFrequency, offBallMovement, shotClockUsage, hotColdStreakImpact, deflectionFrequency,
* screenNavigation, defensiveCommunication, defensiveMatchupImportance, positionMismatchPenalty,
* defensiveVersatility. Each would need a genuinely new mechanic (shot-clock modeling, per-player
* streak tracking, a deflections stat, discrete screen events, matchup-quality detection) rather
* than a multiplier on something that already exists, so wiring them here would be a fake connection.
*/
function mult(rules, key) {
	const def = DEFAULT_LEAGUE_RULES[key];
	const value = rules?.[key] ?? def;
	return def === 0 ? 1 : value / def;
}
function computeRuleMods(rules) {
	return {
		shot: {
			threePointDifficulty: mult(rules, "threePointDifficulty"),
			midrangeDifficulty: mult(rules, "midrangeDifficulty"),
			layupDifficulty: mult(rules, "layupDifficulty"),
			dunkSuccess: mult(rules, "dunkSuccessRate"),
			pullUpDifficulty: mult(rules, "pullUpShootingDifficulty"),
			stepBackDifficulty: mult(rules, "stepBackShootingDifficulty"),
			fadeawayDifficulty: mult(rules, "fadeawayDifficulty"),
			catchAndShootBonus: mult(rules, "catchAndShootBonus"),
			cornerThreeBonus: mult(rules, "cornerThreeBonus"),
			aboveBreakThreeDifficulty: mult(rules, "aboveBreakThreeDifficulty"),
			contestedShotPenalty: mult(rules, "contestedShotPenalty"),
			openShotBonus: mult(rules, "openShotBonus"),
			wideOpenShotBonus: mult(rules, "wideOpenShotBonus"),
			perimeterDefenseImpact: mult(rules, "perimeterDefenseImpact"),
			interiorDefenseImpact: mult(rules, "interiorDefenseImpact"),
			closeoutEffectiveness: mult(rules, "closeoutEffectiveness"),
			contestEffectiveness: mult(rules, "contestEffectiveness"),
			defenderProximityImpact: mult(rules, "defenderProximityImpact"),
			shotQualityImportance: mult(rules, "shotQualityImportance"),
			shotCreationDifficulty: mult(rules, "shotCreationDifficulty"),
			heavilyContestedShotFrequency: mult(rules, "heavilyContestedShotFrequency"),
			offensiveEfficiency: mult(rules, "offensiveEfficiency"),
			defensiveEfficiency: mult(rules, "defensiveEfficiency"),
			pickAndRollDefense: mult(rules, "pickAndRollDefense"),
			postDefense: mult(rules, "postDefense"),
			transitionDefense: mult(rules, "transitionDefense"),
			defensiveIQImpact: mult(rules, "defensiveIQImpact"),
			freeThrowDifficulty: mult(rules, "freeThrowDifficulty")
		},
		turnover: {
			stealFrequency: mult(rules, "stealFrequency"),
			stealSuccess: mult(rules, "stealSuccess"),
			chargeFrequency: mult(rules, "chargeFrequency"),
			perimeterDefenseImpact: mult(rules, "perimeterDefenseImpact")
		},
		shotTypeWeight: {
			three: mult(rules, "threePointFrequency"),
			mid: mult(rules, "midrangeFrequency"),
			rim: mult(rules, "rimFrequency"),
			dunk: mult(rules, "dunkFrequency"),
			layup: mult(rules, "layupFrequency"),
			longTwo: mult(rules, "longTwoFrequency")
		},
		action: {
			isolation: mult(rules, "isolationFrequency"),
			pnr: mult(rules, "pickAndRollFrequency"),
			postUp: mult(rules, "postUpFrequency"),
			transition: mult(rules, "fastBreakFrequency") * mult(rules, "transitionFrequency")
		},
		reboundOffense: mult(rules, "offensiveReboundFrequency"),
		reboundDefense: mult(rules, "defensiveReboundFrequency"),
		assistFrequency: mult(rules, "assistFrequency"),
		blockFrequency: mult(rules, "blockFrequency"),
		blockSuccess: mult(rules, "blockSuccess"),
		rimProtection: mult(rules, "rimProtection"),
		freeThrowFrequency: mult(rules, "freeThrowFrequency"),
		doubleTeamFrequency: mult(rules, "helpDefense") * mult(rules, "defensiveRotations"),
		paceMultiplier: mult(rules, "possessionsPerGame")
	};
}
computeRuleMods(void 0);
//#endregion
//#region src/simulation/awards.ts
const DEFAULT_MVP_WEIGHTS = {
	ppg: 1,
	apg: 1.5,
	rpg: 1.2,
	spg: 1.5,
	bpg: 1.5,
	tov: -.5,
	teamWinPct: 10,
	efficiency: 0,
	winShares: 1.2
};
const DEFAULT_DPOY_WEIGHTS = {
	spg: 3,
	bpg: 3,
	rpg: .3,
	defensiveIQ: .1,
	defensiveWinShares: 1.8
};
({ ...DEFAULT_MVP_WEIGHTS }), { ...DEFAULT_DPOY_WEIGHTS };
new Map([
	{
		id: "first_season",
		name: "Welcome to the Office",
		description: "Complete your first season as general manager.",
		icon: "eoy"
	},
	{
		id: "playoffs",
		name: "Postseason Bound",
		description: "Make the playoffs.",
		icon: "allStar"
	},
	{
		id: "series_win",
		name: "Moving On",
		description: "Win a playoff series.",
		icon: "allLeague3"
	},
	{
		id: "finals",
		name: "Conference Kings",
		description: "Reach the Finals.",
		icon: "allLeague2"
	},
	{
		id: "title",
		name: "Banner Raised",
		description: "Win a championship.",
		icon: "champion"
	},
	{
		id: "title_first_season",
		name: "Instant Impact",
		description: "Win a title in your first season with a team.",
		icon: "fmvp"
	},
	{
		id: "back_to_back",
		name: "Back-to-Back",
		description: "Win two championships in a row.",
		icon: "champion"
	},
	{
		id: "three_peat",
		name: "Three-Peat",
		description: "Win three championships in a row.",
		icon: "champion"
	},
	{
		id: "dynasty",
		name: "Dynasty",
		description: "Win five championships as GM.",
		icon: "champion"
	},
	{
		id: "perfect_postseason",
		name: "Perfect Postseason",
		description: "Win the title without losing a playoff game.",
		icon: "fmvp"
	},
	{
		id: "wins_50",
		name: "Fifty-Win Club",
		description: "Win 61% of your games (50 in 82).",
		icon: "allLeague1"
	},
	{
		id: "wins_60",
		name: "Juggernaut",
		description: "Win 73% of your games (60 in 82).",
		icon: "allLeague1"
	},
	{
		id: "wins_70",
		name: "Seventy",
		description: "Win 85% of your games (70 in 82).",
		icon: "mvp"
	},
	{
		id: "turnaround",
		name: "Turnaround Artist",
		description: "Improve by 20 or more wins in one season.",
		icon: "mip"
	},
	{
		id: "lottery_to_title",
		name: "Worst to First",
		description: "Win a title within three seasons of a lottery finish with the same team.",
		icon: "mip"
	},
	{
		id: "all_goals",
		name: "Owner's Favorite",
		description: "Meet every one of the owner's goals in a season.",
		icon: "eoy"
	},
	{
		id: "extended",
		name: "Contract Extension",
		description: "Earn an extension from your owner.",
		icon: "eoy"
	},
	{
		id: "hot_seat_survivor",
		name: "Hot Seat Survivor",
		description: "Get a warning, then earn an extension the next season.",
		icon: "cpoy"
	},
	{
		id: "pink_slip",
		name: "Pink Slip",
		description: "Get fired. It happens to the best.",
		icon: "ironMan",
		secret: true
	},
	{
		id: "second_chance",
		name: "Second Chance",
		description: "Take a job with a new team after leaving your first.",
		icon: "teammate"
	},
	{
		id: "loyal",
		name: "Franchise Fixture",
		description: "Complete five seasons with the same team.",
		icon: "teammate"
	},
	{
		id: "decade",
		name: "Decade in the Chair",
		description: "Complete ten seasons as a general manager.",
		icon: "ironMan"
	},
	{
		id: "eoy",
		name: "Executive of the Year",
		description: "Win Executive of the Year.",
		icon: "eoy"
	},
	{
		id: "mvp",
		name: "MVP Factory",
		description: "Have the league MVP on your roster.",
		icon: "mvp"
	},
	{
		id: "unanimous_mvp",
		name: "Unanimous",
		description: "Have a unanimous MVP on your roster.",
		icon: "mvp"
	},
	{
		id: "fmvp",
		name: "Finals Hero",
		description: "Have the Finals MVP on your roster.",
		icon: "fmvp"
	},
	{
		id: "dpoy",
		name: "Lockdown",
		description: "Have the Defensive Player of the Year on your roster.",
		icon: "dpoy"
	},
	{
		id: "roy",
		name: "Future Is Now",
		description: "Have the Rookie of the Year on your roster.",
		icon: "roy"
	},
	{
		id: "coy",
		name: "Hire of the Year",
		description: "Your head coach wins Coach of the Year.",
		icon: "coy"
	},
	{
		id: "all_stars_3",
		name: "Star Power",
		description: "Have three or more All-Stars in one season.",
		icon: "allStar"
	},
	{
		id: "all_league_1",
		name: "First Team",
		description: "Have an All-League 1st Team player.",
		icon: "allLeague1"
	},
	{
		id: "scoring_champ",
		name: "Bucket Getter",
		description: "Have the scoring champion on your roster.",
		icon: "scoringChamp"
	},
	{
		id: "drafted_mvp",
		name: "Scout of the Century",
		description: "A player you drafted wins MVP, for any team.",
		icon: "roy"
	},
	{
		id: "homegrown_star",
		name: "Homegrown Star",
		description: "A player you drafted reaches 80 Overall.",
		icon: "mip"
	},
	{
		id: "youth_movement",
		name: "Youth Movement",
		description: "Have three players aged 23 or under at 70+ Overall.",
		icon: "allRookie1"
	},
	{
		id: "money_maker",
		name: "Money Maker",
		description: "Finish a season with thriving finances.",
		icon: "eoy"
	},
	{
		id: "thrifty_title",
		name: "Moneyball",
		description: "Win the title with a payroll under the luxury tax.",
		icon: "champion"
	},
	{
		id: "cup_champion",
		name: "Cup Winners",
		description: "Win the In-Season Cup.",
		icon: "cup"
	},
	{
		id: "cup_mvp",
		name: "Cup Hero",
		description: "Have the In-Season Cup MVP on your roster.",
		icon: "cupMvp"
	},
	{
		id: "cup_double",
		name: "The Double",
		description: "Win the In-Season Cup and the championship in the same season.",
		icon: "cup"
	}
].map((a) => [a.id, a]));
//#endregion
//#region src/storage/gmLegacy.ts
const KEY$2 = "courtvision:gmLegacy";
const empty = () => ({
	version: 1,
	achievements: {},
	leagues: {}
});
function readLegacy(read = localRead) {
	try {
		const raw = read(KEY$2);
		const parsed = raw ? JSON.parse(raw) : null;
		return parsed?.version === 1 && parsed.achievements && parsed.leagues ? parsed : empty();
	} catch {
		return empty();
	}
}
function legacyTotals(legacy) {
	const leagues = Object.values(legacy.leagues);
	return {
		leagues: leagues.length,
		seasons: leagues.reduce((n, l) => n + l.seasons, 0),
		wins: leagues.reduce((n, l) => n + l.wins, 0),
		losses: leagues.reduce((n, l) => n + l.losses, 0),
		titles: leagues.reduce((n, l) => n + l.titles, 0),
		achievements: Object.keys(legacy.achievements).length
	};
}
function readFeats(read = localRead) {
	try {
		const raw = JSON.parse(read("cv-feats") ?? "{}");
		const out = {};
		for (const [k, v] of Object.entries(raw)) if (typeof v === "number" && Number.isFinite(v) && v >= 0) out[k] = Math.floor(v);
		return out;
	} catch {
		return {};
	}
}
/** Two copies of the feats: the higher number of each. Keys in a fixed order so a merged copy merges to itself. */
function mergeFeats(a, b) {
	const out = {};
	for (const k of [.../* @__PURE__ */ new Set([...Object.keys(a), ...Object.keys(b)])].sort()) out[k] = Math.max(a[k] ?? 0, b[k] ?? 0);
	return out;
}
//#endregion
//#region src/hunt/coaches.ts
const c = (id, name, bonus, style, franchises, blurb) => ({
	id,
	name,
	bonus,
	style,
	franchises,
	blurb
});
const COACHES = [
	c("jackson", "Phil Jackson", 5, "triangle", ["CHI", "LAL"], "Eleven rings and the triangle."),
	c("auerbach", "Red Auerbach", 5, "pace", ["BOS"], "Nine titles and a victory cigar."),
	c("popovich", "Gregg Popovich", 5, "defense", ["SAS"], "Five titles, two decades of winning."),
	c("riley", "Pat Riley", 4, "defense", [
		"LAL",
		"NYK",
		"MIA"
	], "Showtime, then elbows in New York."),
	c("kerr", "Steve Kerr", 4, "threes", ["GSW"], "Motion, splash and four titles."),
	c("daly", "Chuck Daly", 4, "defense", ["DET"], "The Bad Boys and the Dream Team."),
	c("spoelstra", "Erik Spoelstra", 4, "balanced", ["MIA"], "Any roster, any system."),
	c("holzman", "Red Holzman", 3, "triangle", ["NYK"], "Hit the open man."),
	c("sloan", "Jerry Sloan", 3, "balanced", ["UTA", "CHI"], "Pick-and-roll, every night, for 23 years."),
	c("lbrown", "Larry Brown", 3, "defense", [
		"DET",
		"PHI",
		"IND",
		"DEN",
		"SAS"
	], "Play the right way."),
	c("kcjones", "K.C. Jones", 3, "balanced", ["BOS"], "Let the 80s Celtics be the 80s Celtics."),
	c("rudyt", "Rudy Tomjanovich", 3, "threes", ["HOU"], "Never underestimate the heart of a champion."),
	c("heinsohn", "Tom Heinsohn", 3, "pace", ["BOS"], "Run, press, run."),
	c("rivers", "Doc Rivers", 3, "defense", [
		"BOS",
		"LAC",
		"ORL",
		"PHI"
	], "Ubuntu."),
	c("carlisle", "Rick Carlisle", 2, "balanced", [
		"DAL",
		"IND",
		"DET"
	], "Beat the Heatles in 2011."),
	c("wilkens", "Lenny Wilkens", 2, "balanced", [
		"SEA",
		"ATL",
		"CLE"
	], "More wins than almost anyone."),
	c("nelson", "Don Nelson", 2, "pace", [
		"MIL",
		"GSW",
		"DAL"
	], "Nellie Ball: small, fast, weird."),
	c("dantoni", "Mike D'Antoni", 2, "pace", ["PHO", "HOU"], "Seven seconds or less."),
	c("nurse", "Nick Nurse", 2, "defense", ["TOR"], "Box-and-one in the Finals."),
	c("budenholzer", "Mike Budenholzer", 2, "threes", ["MIL", "ATL"], "Spread it out around a giant."),
	c("thibodeau", "Tom Thibodeau", 2, "defense", [
		"CHI",
		"NYK",
		"MIN"
	], "Load up the strong side."),
	c("karl", "George Karl", 2, "pace", [
		"SEA",
		"DEN",
		"MIL"
	], "Push it, press it."),
	c("fitch", "Bill Fitch", 2, "balanced", [
		"BOS",
		"HOU",
		"CLE"
	], "Turned the Celtics around in one year."),
	c("lue", "Tyronn Lue", 2, "balanced", ["CLE", "LAC"], "Came back from 3-1."),
	c("hannum", "Alex Hannum", 2, "defense", [
		"PHI",
		"STL",
		"SFW"
	], "The coach who beat Russell."),
	c("cunningham", "Billy Cunningham", 2, "pace", ["PHI"], "Fo, fi, fo."),
	c("malone", "Michael Malone", 2, "balanced", ["DEN"], "Built around a passing center."),
	c("hbrown", "Hubie Brown", 1, "balanced", [
		"ATL",
		"NYK",
		"MEM"
	], "Explains the game better than anyone."),
	c("jvg", "Jeff Van Gundy", 1, "defense", ["NYK", "HOU"], "Grind it out."),
	c("svg", "Stan Van Gundy", 1, "threes", [
		"ORL",
		"MIA",
		"DET"
	], "One big and four shooters."),
	c("collins", "Doug Collins", 1, "balanced", [
		"CHI",
		"DET",
		"WAS",
		"PHI"
	], "Young teams, fast turnarounds."),
	c("motta", "Dick Motta", 1, "balanced", [
		"WSB",
		"CHI",
		"DAL"
	], "The opera ain't over till the fat lady sings."),
	c("ramsay", "Jack Ramsay", 1, "pace", [
		"POR",
		"PHI",
		"IND"
	], "Blazermania."),
	c("fitzsimmons", "Cotton Fitzsimmons", 1, "balanced", [
		"PHO",
		"KCK",
		"ATL"
	], "Always got the most out of a roster."),
	c("westhead", "Paul Westhead", 1, "pace", ["LAL", "DEN"], "Fastest offense ever run."),
	c("vogel", "Frank Vogel", 1, "defense", [
		"IND",
		"LAL",
		"ORL"
	], "Size and defense."),
	c("mazzulla", "Joe Mazzulla", 1, "threes", ["BOS"], "Math: threes are worth more."),
	c("playercoach", "Player-Coach Gary", 0, "balanced", [], "Plays 10 minutes, coaches the other 38."),
	c("legend", "The Local High School Legend", 0, "pace", [], "Won state in 1987 and never stopped talking about it."),
	c("interim", "The Interim Coach", -1, "balanced", [], "Nobody told him how long \"interim\" is."),
	c("promoted", "The Assistant Promoted Tuesday", -1, "balanced", [], "Still learning where the timeout button is."),
	c("nephew", "The Owner's Nephew", -2, "threes", [], "Read a blog post about analytics.")
];
new Map(COACHES.map((x) => [x.id, x]));
const DECKS = {
	classic: {
		id: "classic",
		name: "Classic",
		blurb: "Anyone from any era.",
		coins: 0,
		items: [],
		unlock: "Always open."
	},
	bigMen: {
		id: "bigMen",
		name: "Big Man Era",
		blurb: "Your PF and C spins always show a Great or better, and you start with the Bad Boys Rulebook.",
		coins: 0,
		items: ["badBoys"],
		unlock: "Reach series 3 in any hunt."
	},
	oldSchool: {
		id: "oldSchool",
		name: "Old School",
		blurb: "Only players from before 1980, and 50 more coins to start.",
		coins: 50,
		items: [],
		draft: (c) => c.end < 1980,
		unlock: "Play 3 hunts."
	},
	paceSpace: {
		id: "paceSpace",
		name: "Pace & Space",
		blurb: "Only players from 2010 on, and you start with Seven Seconds or Less.",
		coins: 0,
		items: ["sevenSeconds"],
		draft: (c) => c.end >= 2010,
		unlock: "Reach series 5 in any hunt."
	},
	dynasty: {
		id: "dynasty",
		name: "Dynasty",
		blurb: "Every spin after the first shows a real teammate of someone you drafted.",
		coins: 0,
		items: [],
		unlock: "Win a hunt."
	}
};
const DIFFICULTIES = {
	rookie: {
		id: "rookie",
		name: "Rookie",
		blurb: "Softer teams with fewer buffs, four lives (and lives in the shop), and a 96-rated boss.",
		shift: -3,
		buffs: -1,
		lives: 4,
		bossPool: 12,
		bossRating: 96,
		coinShift: 20,
		unlock: "Always open."
	},
	pro: {
		id: "pro",
		name: "Pro",
		blurb: "The hunt as it was meant to be. No lives for sale.",
		shift: 2,
		buffs: 0,
		lives: 3,
		bossPool: 8,
		bossRating: 100,
		coinShift: 0,
		unlock: "Always open."
	},
	legend: {
		id: "legend",
		name: "Legend",
		blurb: "Tougher teams with an extra buff each, two lives, no lives for sale, and the boss is one of the four best teams ever.",
		shift: 5,
		buffs: 1,
		lives: 2,
		bossPool: 4,
		bossRating: 100,
		coinShift: -10,
		unlock: "Win a hunt."
	}
};
//#endregion
//#region src/hunt/storage.ts
const RECORDS_KEY = "cv-hunt-records";
const EMPTY = {
	runs: 0,
	wins: 0,
	bestStop: 0
};
function loadRecords(read = localRead) {
	try {
		return {
			...EMPTY,
			...JSON.parse(read(RECORDS_KEY) ?? "{}")
		};
	} catch {
		return { ...EMPTY };
	}
}
Object.keys(DECKS);
Object.keys(DIFFICULTIES);
//#endregion
//#region src/simulation/rebuildScenarios.ts
const SCENARIOS = [
	{
		id: "bulls99",
		title: "Life After Michael",
		team: "CHI",
		startYear: 1998,
		seasons: 6,
		difficulty: "Very hard",
		blurb: "Jordan, Pippen and Phil are gone. Six rings on the wall, 13 wins on the way. Bring a seventh banner."
	},
	{
		id: "celtics97",
		title: "Celtics in Ruins",
		team: "BOS",
		startYear: 1996,
		seasons: 6,
		difficulty: "Hard",
		blurb: "The most decorated franchise in the league just went 15-67. Restore the pride."
	},
	{
		id: "clippers99",
		title: "The Clipper Curse",
		team: "LAC",
		startYear: 1998,
		seasons: 8,
		difficulty: "Brutal",
		blurb: "9-41 in a lockout year, and nobody wants to play here. Win the first title in franchise history."
	},
	{
		id: "warriors01",
		title: "Before the Dynasty",
		team: "GSW",
		startYear: 2e3,
		seasons: 8,
		difficulty: "Brutal",
		blurb: "17-65, no plan and no stars. Build the Warriors a decade early."
	},
	{
		id: "wolves10",
		title: "Wolves in the Wilderness",
		team: "MIN",
		startYear: 2009,
		seasons: 7,
		difficulty: "Brutal",
		blurb: "Garnett is long gone and the lottery keeps coming. Make Minnesota a champion."
	},
	{
		id: "cavs11",
		title: "The Decision, Undone",
		team: "CLE",
		startYear: 2010,
		seasons: 5,
		difficulty: "Very hard",
		blurb: "LeBron took his talents to South Beach. From 61 wins to 19. Five years to win it without him."
	},
	{
		id: "bobcats13",
		title: "After 7-59",
		team: "CHA",
		startYear: 2012,
		seasons: 7,
		difficulty: "Brutal",
		blurb: "The worst winning percentage in NBA history, one season ago. Take Charlotte all the way."
	},
	{
		id: "sixers14",
		title: "Trust the Process",
		team: "PHI",
		startYear: 2013,
		seasons: 6,
		difficulty: "Very hard",
		blurb: "Tear it down, stack the picks, and see if the process ends with a parade."
	},
	{
		id: "knicks15",
		title: "Garden of Despair",
		team: "NYK",
		startYear: 2014,
		seasons: 6,
		difficulty: "Very hard",
		blurb: "17-65 in the Mecca. Every free agent says no. Make them say yes."
	},
	{
		id: "lakers17",
		title: "The Post-Kobe Lakers",
		team: "LAL",
		startYear: 2016,
		seasons: 5,
		difficulty: "Hard",
		blurb: "Kobe said Mamba out. Five years to bring a ring back to Los Angeles."
	},
	{
		id: "kings17",
		title: "The Longest Drought",
		team: "SAC",
		startYear: 2016,
		seasons: 7,
		difficulty: "Brutal",
		blurb: "Ten straight years without the playoffs, and counting. Break it, then win it all."
	},
	{
		id: "mavs94",
		title: "Eleven and Seventy-One",
		team: "DAL",
		startYear: 1993,
		seasons: 7,
		difficulty: "Brutal",
		blurb: "The worst team in basketball, two years running. Jim Jackson and Jamal Mashburn are a start. Finish it."
	},
	{
		id: "nuggets99",
		title: "Mile-High Misery",
		team: "DEN",
		startYear: 1998,
		seasons: 6,
		difficulty: "Brutal",
		blurb: "11-71 and a 23-game losing streak. McDyess, Van Exel and a young Billups. Make Denver matter."
	},
	{
		id: "heat09",
		title: "Wade Alone",
		team: "MIA",
		startYear: 2008,
		seasons: 5,
		difficulty: "Hard",
		blurb: "Two years after the title, 15-67. Wade is healthy again and the second pick is in. Get him help, fast."
	},
	{
		id: "hawks06",
		title: "Up From 13-69",
		team: "ATL",
		startYear: 2005,
		seasons: 6,
		difficulty: "Very hard",
		blurb: "Joe Johnson just arrived, Josh Smith can fly, and the arena is empty. Fill it with a banner."
	},
	{
		id: "orlando05",
		title: "Orlando After T-Mac",
		team: "ORL",
		startYear: 2004,
		seasons: 6,
		difficulty: "Very hard",
		blurb: "21-61, McGrady traded, and an 18-year-old Dwight Howard in the middle. Build around him."
	},
	{
		id: "nets11",
		title: "Twelve and Seventy",
		team: "NJN",
		startYear: 2010,
		seasons: 6,
		difficulty: "Brutal",
		blurb: "A 0-18 start, a 12-70 finish, and a move to Brooklyn coming. Arrive with a contender."
	},
	{
		id: "bucks15",
		title: "The Greek Freak Project",
		team: "MIL",
		startYear: 2014,
		seasons: 6,
		difficulty: "Hard",
		blurb: "15-67 last year, but a skinny 19-year-old named Giannis is on the roster. Speed up history."
	},
	{
		id: "pistons21",
		title: "Motor City Reset",
		team: "DET",
		startYear: 2020,
		seasons: 5,
		difficulty: "Very hard",
		blurb: "Twenty wins and a blank slate. Five seasons to bring back the Bad Boys."
	}
];
const FINISH_POINTS = {
	"Play-In": 5,
	"First Round": 20,
	Playoffs: 20,
	"Second Round": 40,
	"Conference Finals": 70,
	Finals: 120,
	Champion: 200
};
const MADE_PLAYOFFS = /* @__PURE__ */ new Set([
	"First Round",
	"Playoffs",
	"Second Round",
	"Conference Finals",
	"Finals",
	"Champion"
]);
/** Scores a challenge's seasons: seasons after a title don't count; a title scores 1,000 plus 250 per season to spare. */
function scoreResults(results, seasons) {
	const titleAt = results.findIndex((r) => r.finish === "Champion");
	const counted = titleAt >= 0 ? results.slice(0, titleAt + 1) : results;
	return {
		counted,
		titleAt,
		score: counted.reduce((n, r) => n + r.wins * 2 + (FINISH_POINTS[r.finish] ?? 0), 0) + (titleAt >= 0 ? 1e3 + (seasons - (titleAt + 1)) * 250 : 0),
		stars: titleAt >= 0 ? 3 : counted.some((r) => r.finish === "Finals") ? 2 : counted.some((r) => MADE_PLAYOFFS.has(r.finish)) ? 1 : 0
	};
}
//#endregion
//#region src/simulation/rebuildChallenge.ts
const KEY$1 = "cv-rebuild-records";
function loadRebuildRecords(read = localRead) {
	try {
		return JSON.parse(read(KEY$1) ?? "{}");
	} catch {
		return {};
	}
}
//#endregion
//#region src/retention/week.ts
/** ISO week in UTC, e.g. "2026-W39". Weeks start on Monday. */
function weekKey(now = /* @__PURE__ */ new Date()) {
	const d = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
	const day = d.getUTCDay() || 7;
	d.setUTCDate(d.getUTCDate() + 4 - day);
	const yearStart = Date.UTC(d.getUTCFullYear(), 0, 1);
	const week = Math.ceil(((d.getTime() - yearStart) / 864e5 + 1) / 7);
	return `${d.getUTCFullYear()}-W${String(week).padStart(2, "0")}`;
}
function weeklySeed(kind, week) {
	let h = 2166136261;
	for (const ch of `courtvision-weekly|${kind}|${week}`) {
		h ^= ch.charCodeAt(0);
		h = Math.imul(h, 16777619);
	}
	return (h >>> 0) % 1e9;
}
//#endregion
//#region src/retention/weekly.ts
const TWISTS = [
	{
		id: "standard",
		label: "Standard rules",
		blurb: "The scenario as written.",
		seasonsDelta: 0,
		hardTrades: false
	},
	{
		id: "shortClock",
		label: "Short clock",
		blurb: "One season less than usual. Win faster.",
		seasonsDelta: -1,
		hardTrades: false
	},
	{
		id: "hardTrades",
		label: "Tough GMs",
		blurb: "Trades need tightly matched value. No fleecing the AI.",
		seasonsDelta: 0,
		hardTrades: true
	},
	{
		id: "gauntlet",
		label: "Short clock, tough GMs",
		blurb: "One season less, and trades need tightly matched value.",
		seasonsDelta: -1,
		hardTrades: true
	}
];
function weeklyRebuild(week = weekKey()) {
	const seed = weeklySeed("rebuild", week);
	const scenario = SCENARIOS[seed % SCENARIOS.length];
	const twist = TWISTS[Math.floor(seed / 97) % TWISTS.length];
	return {
		week,
		seed,
		scenario,
		twist,
		seasons: Math.max(3, scenario.seasons + twist.seasonsDelta)
	};
}
const KEY = "cv-weekly-records";
function loadWeeklyRecords(read = localRead) {
	try {
		return JSON.parse(read(KEY) ?? "{}");
	} catch {
		return {};
	}
}
//#endregion
//#region src/profile/dailyGoals.ts
const HISTORY_KEY = "cv-daily-history";
function dailyGoalXp(read = localRead) {
	try {
		const hist = Object.values(JSON.parse(read(HISTORY_KEY) ?? "{}"));
		return {
			xp: hist.reduce((n, h) => n + h.xp, 0),
			done: hist.reduce((n, h) => n + h.done, 0),
			days: hist.filter((h) => h.done).length
		};
	} catch {
		return {
			xp: 0,
			done: 0,
			days: 0
		};
	}
}
//#endregion
//#region src/profile/profile.ts
const CAREER_KEY = "cv-profile-careers";
/** The career summary behind XP and the Career achievements (the server builds the same one from synced careers). */
function careerCacheOf(metas) {
	const retired = metas.filter((m) => m.retired);
	const awards = (m, key) => (m.years ?? []).reduce((n, y) => n + (y.awards ?? []).filter((a) => a.key === key).length, 0);
	const points = (m) => (m.years ?? []).reduce((n, y) => n + (y.stats?.points ?? 0), 0);
	return {
		careers: metas.length,
		retired: retired.length,
		legacy: retired.reduce((n, m) => n + Math.max(0, m.retired.legacy), 0),
		hallOfFame: retired.filter((m) => m.retired.hallOfFame !== "no").length,
		firstBallot: retired.filter((m) => m.retired.hallOfFame === "first-ballot").length,
		top10: retired.filter((m) => m.retired.rank != null && m.retired.rank <= 10).length,
		mvpCareers: retired.filter((m) => awards(m, "mvp") > 0).length,
		mostTitles: Math.max(0, ...retired.map((m) => awards(m, "champion"))),
		mostPoints: Math.max(0, ...retired.map(points))
	};
}
function careerCache(read) {
	try {
		return {
			careers: 0,
			retired: 0,
			legacy: 0,
			hallOfFame: 0,
			...JSON.parse(read(CAREER_KEY) ?? "{}")
		};
	} catch {
		return {
			careers: 0,
			retired: 0,
			legacy: 0,
			hallOfFame: 0
		};
	}
}
const XP = {
	gmSeason: 60,
	gmWin: 1,
	gmTitle: 300,
	achievement: 50,
	huntRun: 40,
	huntWin: 300,
	huntDaily: 40,
	rebuildAttempt: 100,
	rebuildStar: 75,
	rebuildTitle: 250,
	careerRetired: 150,
	careerHof: 150,
	weekly: 150
};
function xpParts(read = localRead) {
	const gm = legacyTotals(readLegacy(read));
	const hunt = loadRecords(read);
	const daily = Object.keys(hunt.daily ?? {}).length;
	const rebuild = Object.values(loadRebuildRecords(read));
	const rbAttempts = rebuild.reduce((n, r) => n + r.attempts, 0), rbStars = rebuild.reduce((n, r) => n + r.stars, 0), rbTitles = rebuild.filter((r) => r.titleIn != null).length;
	const c = careerCache(read);
	const weeks = Object.values(loadWeeklyRecords(read)).reduce((n, w) => n + (w.rebuild ? 1 : 0) + (w.career ? 1 : 0), 0);
	const goals = dailyGoalXp(read);
	return [
		{
			id: "gm",
			label: "GM leagues",
			xp: gm.seasons * XP.gmSeason + gm.wins * XP.gmWin + gm.titles * XP.gmTitle + gm.achievements * XP.achievement,
			detail: `${gm.seasons} season${gm.seasons === 1 ? "" : "s"} · ${gm.wins} wins · ${gm.titles} title${gm.titles === 1 ? "" : "s"} · ${gm.achievements} achievement${gm.achievements === 1 ? "" : "s"}`
		},
		{
			id: "career",
			label: "Career Mode",
			xp: c.retired * XP.careerRetired + c.legacy + c.hallOfFame * XP.careerHof,
			detail: `${c.retired} retired · ${c.hallOfFame} Hall of Famer${c.hallOfFame === 1 ? "" : "s"} · Legacy ${c.legacy} in all`
		},
		{
			id: "hunt",
			label: "League Hunt",
			xp: hunt.runs * XP.huntRun + hunt.wins * XP.huntWin + daily * XP.huntDaily,
			detail: `${hunt.runs} run${hunt.runs === 1 ? "" : "s"} · ${hunt.wins} won · ${daily} Daily Legend${daily === 1 ? "" : "s"}`
		},
		{
			id: "rebuild",
			label: "Rebuild Challenge",
			xp: rbAttempts * XP.rebuildAttempt + rbStars * XP.rebuildStar + rbTitles * XP.rebuildTitle,
			detail: `${rbAttempts} finished · ${rbStars} star${rbStars === 1 ? "" : "s"} · ${rbTitles} rebuilt to a title`
		},
		{
			id: "weekly",
			label: "Weekly challenges",
			xp: weeks * XP.weekly,
			detail: `${weeks} weekly result${weeks === 1 ? "" : "s"}`
		},
		{
			id: "daily",
			label: "Daily goals",
			xp: goals.xp,
			detail: `${goals.done} goal${goals.done === 1 ? "" : "s"} done`
		}
	];
}
const totalXp = (parts = xpParts()) => parts.reduce((n, p) => n + p.xp, 0);
/** XP needed to go from `level` to the next: 200, 300, 400… */
const levelCost = (level) => 100 + 100 * level;
function levelFor(xp) {
	let level = 1, left = xp;
	while (level < 50 && left >= levelCost(level)) {
		left -= levelCost(level);
		level++;
	}
	return {
		level,
		into: left,
		need: level >= 50 ? 0 : levelCost(level)
	};
}
//#endregion
//#region src/profile/modeAchievements.ts
const TIER_NAMES = [
	"Bronze",
	"Silver",
	"Gold",
	"Platinum",
	"Diamond",
	"Legend"
];
const tierLabel = (n) => `Best so far: ${TIER_NAMES[n]}`;
const at = (n, goal) => [Math.min(n, goal), goal];
const MODE_ACHIEVEMENTS = [
	{
		id: "career-retire",
		mode: "career",
		name: "Hang Them Up",
		description: "Retire a created player.",
		icon: "teammate",
		progress: (s) => at(s.retired, 1)
	},
	{
		id: "career-hof",
		mode: "career",
		name: "Enshrined",
		description: "Put a created player in the Hall of Fame.",
		icon: "eoy",
		progress: (s) => at(s.hallOfFame, 1)
	},
	{
		id: "career-first-ballot",
		mode: "career",
		name: "First Ballot",
		description: "A first-ballot Hall of Famer (Legacy 90+).",
		icon: "eoy",
		progress: (s) => at(s.firstBallot, 1)
	},
	{
		id: "career-mvp",
		mode: "career",
		name: "Most Valuable",
		description: "Win MVP with a created player.",
		icon: "mvp",
		progress: (s) => at(s.mvpCareers, 1)
	},
	{
		id: "career-three-rings",
		mode: "career",
		name: "Three Rings",
		description: "Win three titles in one career.",
		icon: "champion",
		progress: (s) => at(s.mostTitles, 3)
	},
	{
		id: "career-30k",
		mode: "career",
		name: "Thirty Thousand",
		description: "Score 30,000 points in one career.",
		icon: "scoringChamp",
		progress: (s) => at(s.mostPoints, 3e4)
	},
	{
		id: "career-top10",
		mode: "career",
		name: "Pantheon",
		description: "Retire in the all-time Top 10.",
		icon: "fmvp",
		progress: (s) => at(s.top10, 1)
	},
	{
		id: "hunt-win",
		mode: "hunt",
		name: "Boss Beaten",
		description: "Win a League Hunt.",
		icon: "champion",
		progress: (s) => at(s.huntWins, 1)
	},
	{
		id: "hunt-five",
		mode: "hunt",
		name: "Serial Hunter",
		description: "Win five League Hunts.",
		icon: "champion",
		progress: (s) => at(s.huntWins, 5)
	},
	{
		id: "hunt-legend",
		mode: "hunt",
		name: "Legendary",
		description: "Win a League Hunt on Legend difficulty.",
		icon: "fmvp",
		progress: (s) => at(s.huntLegendWins, 1)
	},
	{
		id: "hunt-daily-win",
		mode: "hunt",
		name: "Legend of the Day",
		description: "Win a Daily Legend.",
		icon: "pow",
		progress: (s) => at(s.dailyWins, 1)
	},
	{
		id: "hunt-daily-seven",
		mode: "hunt",
		name: "Daily Habit",
		description: "Play seven Daily Legends.",
		icon: "ironMan",
		progress: (s) => at(s.dailyPlayed, 7)
	},
	{
		id: "hunt-album-100",
		mode: "hunt",
		name: "Collector",
		description: "Hold 100 cards in your album.",
		icon: "allStar",
		progress: (s) => at(s.album, 100)
	},
	{
		id: "hunt-album-300",
		mode: "hunt",
		name: "Archivist",
		description: "Hold 300 cards in your album.",
		icon: "allStarMvp",
		progress: (s) => at(s.album, 300)
	},
	{
		id: "rebuild-star",
		mode: "rebuild",
		name: "First Star",
		description: "Earn a star in a Rebuild Challenge.",
		icon: "mip",
		progress: (s) => at(s.rebuildStars, 1)
	},
	{
		id: "rebuild-title",
		mode: "rebuild",
		name: "Rebuilt",
		description: "Rebuild a team into champions.",
		icon: "champion",
		progress: (s) => at(s.rebuildTitles, 1)
	},
	{
		id: "rebuild-year-one",
		mode: "rebuild",
		name: "Instant Contender",
		description: "Win the title in the first season of a rebuild.",
		icon: "fmvp",
		progress: (s) => at(s.rebuildYearOne, 1)
	},
	{
		id: "rebuild-architect",
		mode: "rebuild",
		name: "Architect",
		description: "Three stars in five different rebuilds.",
		icon: "eoy",
		progress: (s) => at(s.rebuildThreeStars, 5)
	},
	{
		id: "draft-done",
		mode: "draft",
		name: "On the Clock",
		description: "Finish an All-Time Draft and start the season.",
		icon: "allRookie1",
		progress: (s) => at(s.drafts, 1)
	},
	{
		id: "draft-top",
		mode: "draft",
		name: "Best Board",
		description: "Leave an All-Time Draft with the strongest team on paper.",
		icon: "allLeague1",
		progress: (s) => at(s.draftTop, 1)
	},
	{
		id: "draft-title",
		mode: "draft",
		name: "All-Time Champions",
		description: "Win a title with an All-Time Draft team.",
		icon: "champion",
		progress: (s) => at(s.draftTitles, 1)
	},
	{
		id: "pvp-win",
		mode: "pvp",
		name: "Ghostbuster",
		description: "Win a PvP series against another GM's ghost.",
		icon: "pom",
		progress: (s) => at(s.pvpWins, 1)
	},
	{
		id: "pvp-ten",
		mode: "pvp",
		name: "Ghost Hunter",
		description: "Win ten PvP series.",
		icon: "pow",
		progress: (s) => at(s.pvpWins, 10)
	},
	{
		id: "pvp-1200",
		mode: "pvp",
		name: "Contender",
		description: "Reach a PvP rating of 1200.",
		icon: "allLeague2",
		progress: (s) => at(Math.max(0, s.pvpBest - 1e3), 200),
		label: (n) => `Best rating ${1e3 + n} / 1200`
	},
	{
		id: "ranked-gold",
		mode: "ranked",
		name: "Gold Standard",
		description: "Reach Gold in a ranked season.",
		icon: "allLeague3",
		progress: (s) => at(s.rankedTier, 2),
		label: tierLabel
	},
	{
		id: "ranked-diamond",
		mode: "ranked",
		name: "Diamond Hands",
		description: "Reach Diamond in a ranked season.",
		icon: "allLeague1",
		progress: (s) => at(s.rankedTier, 4),
		label: tierLabel
	},
	{
		id: "ranked-legend",
		mode: "ranked",
		name: "Legend Tier",
		description: "Reach Legend in a ranked season.",
		icon: "mvp",
		progress: (s) => at(s.rankedTier, 5),
		label: tierLabel
	},
	{
		id: "weekly-first",
		mode: "weekly",
		name: "This Week's Challenge",
		description: "Post a weekly Rebuild or Career result.",
		icon: "pow",
		progress: (s) => at(s.weeks, 1)
	},
	{
		id: "weekly-four",
		mode: "weekly",
		name: "Regular",
		description: "Post four weekly results.",
		icon: "pom",
		progress: (s) => at(s.weeks, 4)
	},
	{
		id: "goals-all",
		mode: "daily",
		name: "Clean Sheet",
		description: "Finish all three daily goals in one day.",
		icon: "hustle",
		progress: (s) => at(s.perfectDays, 1)
	},
	{
		id: "goals-streak",
		mode: "daily",
		name: "Seven Straight",
		description: "Finish a daily goal seven days in a row.",
		icon: "ironMan",
		progress: (s) => at(s.goalStreak, 7)
	}
];
new Map(MODE_ACHIEVEMENTS.map((a) => [a.id, a]));
const RANK_ORDER = [
	"bronze",
	"silver",
	"gold",
	"platinum",
	"diamond",
	"legend"
];
const json$1 = (read, key, fallback) => {
	try {
		return JSON.parse(read(key) ?? "null") ?? fallback;
	} catch {
		return fallback;
	}
};
/** The longest run of consecutive UTC days (YYYY-MM-DD) in a list. */
function longestStreak(days) {
	const t = [...new Set(days)].map((d) => Date.parse(`${d}T00:00:00Z`)).filter(Number.isFinite).sort((a, b) => a - b);
	let best = 0, run = 0;
	t.forEach((d, i) => {
		run = i && d - t[i - 1] === 864e5 ? run + 1 : 1;
		best = Math.max(best, run);
	});
	return best;
}
/** Everything the mode achievements look at. `extra` lets the server add what it knows better (the ranked tier). */
function modeStats(read = localRead, extra = {}) {
	const c = careerCache(read), hunt = loadRecords(read), feats = readFeats(read);
	const daily = Object.values(hunt.daily ?? {});
	const rebuild = Object.values(loadRebuildRecords(read));
	const legacy = readLegacy(read);
	const weeks = Object.values(loadWeeklyRecords(read)).reduce((n, w) => n + (w.rebuild ? 1 : 0) + (w.career ? 1 : 0), 0);
	const goals = json$1(read, "cv-daily-history", {});
	const rankedLocal = RANK_ORDER.indexOf(read("cv-ranked-best") ?? "");
	return {
		retired: c.retired,
		hallOfFame: c.hallOfFame,
		firstBallot: c.firstBallot ?? 0,
		top10: c.top10 ?? 0,
		mvpCareers: c.mvpCareers ?? 0,
		mostTitles: c.mostTitles ?? 0,
		mostPoints: c.mostPoints ?? 0,
		huntWins: hunt.wins,
		huntLegendWins: feats.huntLegendWins ?? 0,
		dailyPlayed: daily.length,
		dailyWins: daily.filter((d) => d.won).length,
		album: json$1(read, "cv-hunt-album", []).length,
		rebuildStars: rebuild.reduce((n, r) => n + r.stars, 0),
		rebuildTitles: rebuild.filter((r) => r.titleIn != null).length,
		rebuildYearOne: rebuild.filter((r) => r.titleIn === 1).length,
		rebuildThreeStars: rebuild.filter((r) => r.stars >= 3).length,
		drafts: feats.drafts ?? 0,
		draftTop: feats.draftTop ?? 0,
		draftTitles: Object.values(legacy.leagues).filter((l) => l.kind === "draft").reduce((n, l) => n + l.titles, 0),
		pvpWins: Math.max(feats.pvpWins ?? 0, extra.pvpWins ?? 0),
		pvpBest: Math.max(feats.pvpBest ?? 0, extra.pvpBest ?? 0),
		rankedTier: Math.max(feats.rankedTier ?? 0, rankedLocal, extra.rankedTier ?? 0),
		weeks,
		perfectDays: Object.values(goals).filter((g) => g.done >= 3).length,
		goalStreak: longestStreak(Object.entries(goals).filter(([, g]) => g.done > 0).map(([d]) => d))
	};
}
const isEarned = (a, s) => {
	const [n, goal] = a.progress(s);
	return n >= goal;
};
function earnedModeAchievements(read = localRead, extra = {}) {
	const s = modeStats(read, extra);
	return MODE_ACHIEVEMENTS.filter((a) => isEarned(a, s)).map((a) => a.id);
}
//#endregion
//#region src/cloud/ranked.ts
const seasonOf = (isoDay) => isoDay.slice(0, 7);
const dailyLegendPoints = (won, stop) => won ? 40 : Math.min(27, Math.max(0, stop) * 3);
const weeklyRebuildPoints = (stars, title) => Math.min(100, Math.max(0, stars) * 25 + (title ? 25 : 0));
const weeklyCareerPoints = (legacy) => Math.min(100, Math.max(0, Math.round(legacy / 2)));
const dailyGoalPoints = (done) => Math.min(3, Math.max(0, done)) * 5 + (done >= 3 ? 5 : 0);
const TIERS = [
	{
		id: "bronze",
		name: "Bronze",
		min: 0,
		color: "#c07a45"
	},
	{
		id: "silver",
		name: "Silver",
		min: 150,
		color: "#b9c4d0"
	},
	{
		id: "gold",
		name: "Gold",
		min: 400,
		color: "#ffd166"
	},
	{
		id: "platinum",
		name: "Platinum",
		min: 800,
		color: "#7fe0d0"
	},
	{
		id: "diamond",
		name: "Diamond",
		min: 1300,
		color: "#7fb7ff"
	},
	{
		id: "legend",
		name: "Legend",
		min: 1900,
		color: "#f47b20"
	}
];
function tierFor(points) {
	let i = 0;
	while (i + 1 < TIERS.length && points >= TIERS[i + 1].min) i++;
	return {
		tier: TIERS[i],
		next: TIERS[i + 1] ?? null,
		into: points - TIERS[i].min
	};
}
//#endregion
//#region src/retention/leagueCode.ts
const DIFFS = [
	"easy",
	"normal",
	"hard"
];
const ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
const check = (body) => ALPHABET[[...body].reduce((h, c, i) => (h * 31 + c.charCodeAt(0) * (i + 1)) % 1000003, 7) % 32];
const fromB32 = (s) => [...s].reduce((n, c) => {
	const v = ALPHABET.indexOf(c);
	if (v < 0) throw new Error("bad");
	return n * 32 + v;
}, 0);
/** Reads a code (any case, spaces and O/I/L typos forgiven). Throws a readable error for anything else. */
function decodeLeagueCode(raw) {
	const parts = raw.trim().toUpperCase().replace(/\s+/g, "").replace(/[–—]/g, "-").split("-");
	if (parts.length < 4 || parts.length > 5) throw new Error("That is not a Court Vision league code.");
	const fix = (s) => s.replace(/O/g, "0").replace(/[IL]/g, "1");
	const sum = fix(parts.pop());
	parts[1] = fix(parts[1]);
	parts[2] = fix(parts[2]);
	if (check(parts.join("-")) !== sum) throw new Error("This code has a typo: check it and try again.");
	const [head, optsRaw, seedRaw, team] = parts;
	let opts, seed;
	try {
		opts = fromB32(optsRaw);
		seed = fromB32(seedRaw);
	} catch {
		throw new Error("This code has a typo: check it and try again.");
	}
	const difficulty = DIFFS[opts % 3];
	const rest = Math.floor(opts / 3);
	const teamId = team ?? null;
	if (head.startsWith("B")) {
		const scenario = SCENARIOS.find((s) => s.id.toUpperCase() === head.slice(1));
		if (!scenario) throw new Error("This code is for a Rebuild scenario this version of the game does not have.");
		const twist = rest ? TWISTS[rest - 1]?.id : void 0;
		return {
			origin: {
				kind: "rebuild",
				seed,
				difficulty,
				scenario: scenario.id,
				...twist ? { twist } : {}
			},
			teamId
		};
	}
	const kind = head[0] === "G" ? "random" : head[0] === "H" ? "history" : null;
	const year = Number(head.slice(1));
	if (!kind || !Number.isInteger(year) || year < 1946 || year > 2100) throw new Error("That is not a Court Vision league code.");
	return {
		origin: {
			kind,
			seed,
			difficulty,
			year,
			...kind === "history" ? {
				realDevelopment: !!(rest & 1),
				forceRosters: !!(rest & 2),
				allPlayers: !!(rest & 4)
			} : rest & 8 ? { balanced: true } : {}
		},
		teamId
	};
}
//#endregion
//#region src/cloud/merge.ts
/** The stored values that belong to the account (everything else is per device). */
const SYNC_KEYS = [
	"courtvision:gmLegacy",
	"cv-hunt-records",
	"cv-hunt-album",
	"cv-rebuild-records",
	"cv-rebuild-records-done",
	"cv-weekly-records",
	"cv-daily-history",
	"cv-profile-equip",
	"cv-code-results",
	"cv-feats"
];
const parse = (raw, fallback) => {
	if (!raw) return fallback;
	try {
		return JSON.parse(raw) ?? fallback;
	} catch {
		return fallback;
	}
};
const max = (a, b) => Math.max(a ?? 0, b ?? 0);
function mergeLegacy(a, b) {
	const out = {
		version: 1,
		achievements: { ...b.achievements },
		leagues: { ...b.leagues }
	};
	for (const [id, x] of Object.entries(a.achievements ?? {})) {
		const y = out.achievements[id];
		out.achievements[id] = y ? {
			...x.at <= y.at ? x : y,
			saveIds: [.../* @__PURE__ */ new Set([...x.saveIds, ...y.saveIds])]
		} : x;
	}
	for (const [id, l] of Object.entries(a.leagues ?? {})) {
		const y = out.leagues[id];
		if (!y || l.updatedAt >= y.updatedAt) out.leagues[id] = l;
	}
	return out;
}
function mergeHunt(a, b) {
	const daily = { ...b.daily ?? {} };
	for (const [d, r] of Object.entries(a.daily ?? {})) {
		const o = daily[d];
		if (!o || r.won && !o.won || r.won === o.won && r.stop > o.stop) daily[d] = r;
	}
	return {
		runs: max(a.runs, b.runs),
		wins: max(a.wins, b.wins),
		bestStop: max(a.bestStop, b.bestStop),
		...a.lastSeed != null ? { lastSeed: a.lastSeed } : b.lastSeed != null ? { lastSeed: b.lastSeed } : {},
		daily
	};
}
function mergeRebuild(a, b) {
	const norm = (r, o = r) => {
		const done = max(r.completedAt, o.completedAt);
		return {
			best: max(r.best, o.best),
			stars: max(r.stars, o.stars),
			titleIn: r.titleIn != null && o.titleIn != null ? Math.min(r.titleIn, o.titleIn) : r.titleIn ?? o.titleIn ?? null,
			attempts: max(r.attempts, o.attempts),
			...done ? { completedAt: done } : {}
		};
	};
	const out = {};
	for (const id of [.../* @__PURE__ */ new Set([...Object.keys(b), ...Object.keys(a)])].sort()) out[id] = a[id] && b[id] ? norm(a[id], b[id]) : norm(a[id] ?? b[id]);
	return out;
}
function mergeWeekly(a, b) {
	const out = JSON.parse(JSON.stringify(b));
	for (const [w, x] of Object.entries(a)) {
		const y = out[w] ?? {};
		out[w] = { ...y };
		for (const k of ["rebuild", "career"]) {
			const r = x[k], o = y[k];
			if (r && (!o || r.best > o.best)) out[w][k] = r;
		}
	}
	return out;
}
function mergeDays(a, b) {
	const out = { ...b };
	for (const [d, x] of Object.entries(a)) {
		const y = out[d];
		if (!y || x.xp > y.xp) out[d] = x;
	}
	return out;
}
function mergeCodes(a, b) {
	const out = { ...b };
	for (const [c, x] of Object.entries(a)) {
		const y = out[c];
		if (!y || x.at > y.at) out[c] = x;
	}
	return out;
}
/** Merges one stored value. `local` wins ties for per-device choices (the frame and floor you just equipped). */
function mergeValue(key, local, cloud) {
	if (local == null || local === "") return cloud ?? null;
	if (cloud == null || cloud === "") return local;
	switch (key) {
		case "courtvision:gmLegacy": return JSON.stringify(mergeLegacy(parse(local, {
			version: 1,
			achievements: {},
			leagues: {}
		}), parse(cloud, {
			version: 1,
			achievements: {},
			leagues: {}
		})));
		case "cv-hunt-records": return JSON.stringify(mergeHunt(parse(local, {
			runs: 0,
			wins: 0,
			bestStop: 0
		}), parse(cloud, {
			runs: 0,
			wins: 0,
			bestStop: 0
		})));
		case "cv-hunt-album":
		case "cv-rebuild-records-done": return JSON.stringify([.../* @__PURE__ */ new Set([...parse(cloud, []), ...parse(local, [])])]);
		case "cv-rebuild-records": return JSON.stringify(mergeRebuild(parse(local, {}), parse(cloud, {})));
		case "cv-weekly-records": return JSON.stringify(mergeWeekly(parse(local, {}), parse(cloud, {})));
		case "cv-daily-history": return JSON.stringify(mergeDays(parse(local, {}), parse(cloud, {})));
		case "cv-code-results": return JSON.stringify(mergeCodes(parse(local, {}), parse(cloud, {})));
		case "cv-feats": return JSON.stringify(mergeFeats(readFeats(() => local), readFeats(() => cloud)));
		case "cv-profile-equip": return local;
	}
}
function mergeStorage(local, cloud) {
	const out = {};
	for (const k of SYNC_KEYS) {
		const v = mergeValue(k, local[k], cloud[k]);
		if (v != null) out[k] = v;
	}
	return out;
}
/** Careers: the newer copy of each (a retired one never goes back to active). */
function mergeCareers(local, cloud) {
	const byId = new Map(cloud.map((c) => [c.id, c]));
	for (const c of local) {
		const o = byId.get(c.id);
		if (!o || o.status !== "retired" && (c.status === "retired" || c.updatedAt >= o.updatedAt)) byId.set(c.id, c);
	}
	return [...byId.values()];
}
//#endregion
//#region src/career/categories.ts
const f = (group, ...keys) => keys.map((k) => [group, k]);
const CATEGORIES = [
	{
		id: "size",
		name: "Height & Length",
		short: "SIZE",
		blurb: "Height, wingspan and reach.",
		fields: f("physical", "heightInches", "wingspanInches", "standingReachInches")
	},
	{
		id: "body",
		name: "Body",
		short: "BODY",
		blurb: "Weight, strength, balance, stamina and durability.",
		fields: f("physical", "weightLbs", "strength", "balance", "stamina", "durability")
	},
	{
		id: "athleticism",
		name: "Athleticism",
		short: "ATH",
		blurb: "Speed, acceleration, vertical and agility.",
		fields: f("physical", "speed", "acceleration", "vertical", "agility")
	},
	{
		id: "finishing",
		name: "Finishing",
		short: "FIN",
		blurb: "Layups, dunks, touch and the post.",
		fields: f("offense", "closeShot", "drivingLayup", "drivingDunk", "standingDunk", "postHook", "postFade", "postControl", "finishing", "touch")
	},
	{
		id: "midRange",
		name: "Mid-Range",
		short: "MID",
		blurb: "Mid-range, long twos and free throws.",
		fields: f("offense", "midrange", "longMidrange", "freeThrow")
	},
	{
		id: "threePoint",
		name: "Three-Point",
		short: "3PT",
		blurb: "Every kind of three.",
		fields: f("offense", "threePoint", "corner3", "aboveBreak3", "pullUp3", "catchAndShoot")
	},
	{
		id: "playmaking",
		name: "Playmaking",
		short: "PLAY",
		blurb: "Handles, passing and decisions.",
		fields: f("offense", "ballHandling", "ballSecurity", "speedWithBall", "passing", "passingAccuracy", "passingIQ", "decisionMaking")
	},
	{
		id: "perimeterD",
		name: "Perimeter D",
		short: "PER D",
		blurb: "On-ball defense, closeouts and steals.",
		fields: f("defense", "perimeterDefense", "pickAndRollDefense", "closeout", "steal", "stealIQ", "onBallSteal", "passingLaneSteal")
	},
	{
		id: "interiorD",
		name: "Interior D & Boards",
		short: "INT D",
		blurb: "Rim protection, blocks and rebounding.",
		fields: [...f("defense", "interiorDefense", "helpDefense", "contest", "block", "blockIQ", "blockTiming", "rimProtection", "defensiveRebounding"), ...f("offense", "offensiveRebounding")]
	},
	{
		id: "iq",
		name: "IQ & Clutch",
		short: "IQ",
		blurb: "Basketball IQ, clutch, composure and consistency.",
		fields: [
			...f("mental", "clutch", "consistency", "confidence", "composure", "discipline", "aggression", "effort", "basketballIQ", "playoffPerformance", "pressurePerformance", "leadership"),
			...f("offense", "offensiveIQ", "shotIQ", "offensiveConsistency"),
			...f("defense", "defensiveIQ", "defensiveConsistency", "defensiveAwareness", "defensiveDiscipline")
		]
	}
];
new Map(CATEGORIES.map((c) => [c.id, c]));
CATEGORIES.filter((c) => c.id !== "size").map((c) => c.id);
//#endregion
//#region src/career/legacy.ts
const emptyResume = () => ({
	titles: 0,
	fmvp: 0,
	mvp: 0,
	allNba1: 0,
	allNba2: 0,
	allNba3: 0,
	allStar: 0,
	dpoy: 0,
	allDef1: 0,
	allDef2: 0,
	roy: 0,
	games: 0,
	pts: 0,
	reb: 0,
	ast: 0,
	stl: 0,
	blk: 0
});
//#endregion
//#region src/career/career.ts
function careerResume(meta) {
	const r = emptyResume();
	for (const y of meta.years) {
		r.games += y.stats.gamesPlayed;
		r.pts += y.stats.points;
		r.reb += y.stats.oreb + y.stats.dreb;
		r.ast += y.stats.ast;
		r.stl += y.stats.stl;
		r.blk += y.stats.blk;
		for (const a of y.awards) if (a.key === "champion") r.titles++;
		else if (a.key === "fmvp") r.fmvp++;
		else if (a.key === "mvp") r.mvp++;
		else if (a.key === "allLeague1") r.allNba1++;
		else if (a.key === "allLeague2") r.allNba2++;
		else if (a.key === "allLeague3") r.allNba3++;
		else if (a.key === "allStar") r.allStar++;
		else if (a.key === "dpoy") r.dpoy++;
		else if (a.key === "allDefense1") r.allDef1++;
		else if (a.key === "allDefense2") r.allDef2++;
		else if (a.key === "roy") r.roy++;
	}
	return r;
}
//#endregion
//#region server/derive.ts
const FIRST_WEEK = "2026-W39";
const FIRST_DAY = "2026-01-01";
const int = (v, lo, hi) => typeof v === "number" && Number.isInteger(v) && v >= lo && v <= hi;
const FINISHES = /* @__PURE__ */ new Set([...Object.keys(FINISH_POINTS), "Missed Playoffs"]);
const plural = (n, w) => `${n} ${w}${n === 1 ? "" : "s"}`;
const mondayOf = (week) => {
	const [y, w] = week.split("-W").map(Number);
	const d = (new Date(Date.UTC(y, 0, 4)).getUTCDay() || 7) - 1;
	return new Date(Date.UTC(y, 0, 4 - d + (w - 1) * 7)).toISOString().slice(0, 10);
};
function sanitizeBlob(raw) {
	const b = raw;
	if (!b || b.version !== 1 || typeof b.storage !== "object" || !Array.isArray(b.careers)) return null;
	const storage = {};
	for (const k of SYNC_KEYS) {
		const v = b.storage[k];
		if (typeof v === "string" && v.length < 4e5) storage[k] = v;
	}
	return {
		version: 1,
		updatedAt: Number(b.updatedAt) || Date.now(),
		storage,
		careers: b.careers.filter((c) => c && typeof c === "object").slice(0, 500)
	};
}
function derive(blob, now = /* @__PURE__ */ new Date()) {
	const read = objectRead(blob.storage);
	const today = now.toISOString().slice(0, 10), thisWeek = weekKey(now);
	const players = [];
	let legacySum = 0, hof = 0, best = null;
	const counted = [];
	for (const m of blob.careers) {
		const r = m.retired, name = cleanName(m.playerId);
		if (m.status !== "retired" || !r || !name || !int(Math.round(r.legacy), 0, 400) || !Array.isArray(m.years) || !int(m.years.length, 1, 25)) continue;
		const res = careerResume(m), legacy = Math.round(r.legacy), g = Math.max(1, res.games);
		if (res.titles > m.years.length || res.mvp > m.years.length || res.games > 3300) continue;
		const hall = ["yes", "first-ballot"].includes(r.hallOfFame) ? r.hallOfFame : "no";
		players.push({
			career_id: String(m.id).slice(0, 60),
			name,
			legacy,
			rank: int(r.rank, 1, 100) ? r.rank : null,
			seasons: m.years.length,
			titles: res.titles,
			mvps: res.mvp,
			all_stars: res.allStar,
			hall_of_fame: hall,
			draft_year: int(m.draftYear, 1946, 2100) ? m.draftYear : null,
			weekly: typeof m.weekly === "string" && /^\d{4}-W\d{2}$/.test(m.weekly) ? m.weekly : null,
			ppg: +(res.pts / g).toFixed(1),
			rpg: +(res.reb / g).toFixed(1),
			apg: +(res.ast / g).toFixed(1),
			points: res.pts,
			retired_at: new Date(m.updatedAt || now).toISOString()
		});
		legacySum += legacy;
		if (hall !== "no") hof++;
		counted.push(m);
		if (!best || legacy > best.legacy) best = {
			name,
			legacy
		};
	}
	const careerCache = {
		...careerCacheOf(counted),
		careers: blob.careers.length,
		retired: players.length,
		legacy: legacySum,
		hallOfFame: hof
	};
	const readWithCareers = (k) => k === "cv-profile-careers" ? JSON.stringify(careerCache) : read(k);
	const weekly = [], ranked = [];
	for (const [week, w] of Object.entries(loadWeeklyRecords(read))) {
		if (!/^\d{4}-W\d{2}$/.test(week) || week < FIRST_WEEK || week > thisWeek) continue;
		const season = seasonOf(mondayOf(week));
		if (w.rebuild) {
			const cfg = weeklyRebuild(week);
			const results = w.rebuild.results ?? [];
			if (results.length > 0 && results.length <= cfg.seasons && results.every((x) => x && int(x.wins, 0, 82) && int(x.losses, 0, 82) && x.wins + x.losses >= 20 && x.wins + x.losses <= 82 && FINISHES.has(x.finish))) {
				const s = scoreResults(results, cfg.seasons);
				if (s.titleAt >= 0 || results.length === cfg.seasons) {
					const bestRec = [...s.counted].sort((a, b) => b.wins - a.wins)[0];
					weekly.push({
						board: "rebuild",
						week,
						score: s.score,
						detail: `${cfg.scenario.title} · ${"★".repeat(s.stars)}${"☆".repeat(3 - s.stars)} · ${s.titleAt >= 0 ? `title in year ${s.titleAt + 1}` : `best ${bestRec.wins}-${bestRec.losses}`}`
					});
					ranked.push({
						event: `wr:${week}`,
						season,
						points: weeklyRebuildPoints(s.stars, s.titleAt >= 0)
					});
				}
			}
		}
		if (w.career && int(Math.round(w.career.best), 0, 400)) {
			const legacy = Math.round(w.career.best);
			const label = cleanName(w.career.label) ?? "A created player";
			weekly.push({
				board: "career",
				week,
				score: legacy,
				detail: `${label} · Legacy ${legacy}`
			});
			ranked.push({
				event: `wc:${week}`,
				season,
				points: weeklyCareerPoints(legacy)
			});
		}
	}
	const hunt = loadRecords(read);
	const daily = [];
	for (const [day, d] of Object.entries(hunt.daily ?? {})) {
		if (!/^\d{4}-\d{2}-\d{2}$/.test(day) || day < FIRST_DAY || day > today || !d || !int(d.stop, 0, 10) || !int(d.wins, 0, 40) || !int(d.losses, 0, 40)) continue;
		const won = !!d.won;
		daily.push({
			day,
			won,
			stop: d.stop,
			wins: d.wins,
			losses: d.losses,
			score: won ? 1e3 + (d.wins - d.losses) * 10 : d.stop * 100 + d.wins * 2
		});
		ranked.push({
			event: `dl:${day}`,
			season: seasonOf(day),
			points: dailyLegendPoints(won, d.stop)
		});
	}
	try {
		const hist = JSON.parse(read("cv-daily-history") ?? "{}");
		for (const [day, h] of Object.entries(hist)) if (/^\d{4}-\d{2}-\d{2}$/.test(day) && day >= FIRST_DAY && day <= today && int(h?.done, 1, 3)) ranked.push({
			event: `dg:${day}`,
			season: seasonOf(day),
			points: dailyGoalPoints(h.done)
		});
	} catch {}
	const rebuild = [];
	for (const [id, r] of Object.entries(loadRebuildRecords(read))) {
		const sc = SCENARIOS.find((s) => s.id === id);
		const cap = sc ? 1e3 + sc.seasons * 614 : 0;
		if (!sc || !r || !int(r.best, 0, cap) || !int(r.stars, 0, 3)) continue;
		rebuild.push({
			scenario: id,
			best: r.best,
			stars: r.stars,
			title_in: int(r.titleIn, 1, sc.seasons) ? r.titleIn : null
		});
	}
	const codes = [];
	try {
		for (const [code, c] of Object.entries(JSON.parse(read("cv-code-results") ?? "{}"))) {
			try {
				decodeLeagueCode(code);
			} catch {
				continue;
			}
			if (!c || !int(c.wins, 0, 82) || !int(c.losses, 0, 82) || c.wins + c.losses < 20 || c.wins + c.losses > 82 || !FINISHES.has(c.finish)) continue;
			codes.push({
				code: code.toUpperCase().slice(0, 40),
				team: typeof c.team === "string" ? c.team.slice(0, 12) : null,
				wins: c.wins,
				losses: c.losses,
				finish: c.finish,
				score: c.wins * 2 + (FINISH_POINTS[c.finish] ?? 0)
			});
		}
	} catch {}
	const parts = xpParts(readWithCareers), xp = totalXp(parts);
	const legacy = readLegacy(read), gm = legacyTotals(legacy);
	const bySeason = {};
	for (const e of ranked) bySeason[e.season] = (bySeason[e.season] ?? 0) + e.points;
	const stats = {
		ranked: bySeason,
		rankedBest: tierFor(Object.values(bySeason).reduce((b, p) => tierFor(p).tier.min > tierFor(b).tier.min ? p : b, 0)).tier.id,
		seasons: gm.seasons,
		wins: gm.wins,
		titles: gm.titles,
		achievements: gm.achievements,
		huntRuns: hunt.runs,
		huntWins: hunt.wins,
		dailyWins: daily.filter((d) => d.won).length,
		rebuildStars: rebuild.reduce((n, r) => n + r.stars, 0),
		rebuildTitles: rebuild.filter((r) => r.title_in != null).length,
		careers: players.length,
		hallOfFame: hof,
		bestPlayer: best,
		xpParts: Object.fromEntries(parts.map((p) => [p.id, p.xp])),
		summary: `${plural(gm.titles, "title")} · ${plural(hof, "Hall of Famer")} · ${plural(hunt.wins, "hunt")} won`
	};
	const modes = earnedModeAchievements(readWithCareers, { rankedTier: TIERS.findIndex((t) => t.id === stats.rankedBest) }).map((id) => `mode-${id}`);
	return {
		profile: {
			level: levelFor(xp).level,
			xp,
			stats: {
				...stats,
				modeAchievements: modes.length
			}
		},
		achievements: [...Object.keys(legacy.achievements).filter((a) => /^[\w-]{1,40}$/.test(a)).slice(0, 200), ...modes],
		players,
		weekly,
		daily,
		rebuild,
		codes,
		ranked
	};
}
//#endregion
//#region server/supabase.ts
const pick = (env, ...names) => names.map((n) => env[n]).find((v) => !!v);
function supaEnv(env = globalThis.process?.env ?? {}) {
	const url = pick(env, "SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_URL", "VITE_SUPABASE_URL");
	const serviceKey = pick(env, "SUPABASE_SERVICE_ROLE_KEY", "SUPABASE_SECRET_KEY");
	const publicKey = pick(env, "SUPABASE_ANON_KEY", "NEXT_PUBLIC_SUPABASE_ANON_KEY", "SUPABASE_PUBLISHABLE_KEY", "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_ANON_KEY") ?? serviceKey;
	return url && serviceKey && publicKey ? {
		url: url.replace(/\/$/, ""),
		serviceKey,
		publicKey
	} : null;
}
/** New-style keys (sb_…) go in the apikey header only; legacy JWT keys also as the bearer token. */
const keyHeaders = (key) => key.startsWith("sb_") ? { apikey: key } : {
	apikey: key,
	Authorization: `Bearer ${key}`
};
/** The signed-in user behind an access token, or null. */
async function getUser(env, token, f = fetch) {
	const res = await f(`${env.url}/auth/v1/user`, { headers: {
		apikey: env.publicKey,
		Authorization: `Bearer ${token}`
	} });
	if (!res.ok) return null;
	const u = await res.json();
	return u.id ? {
		id: u.id,
		email: u.email
	} : null;
}
/** A PostgREST call with the service key (row level security does not apply). */
async function rest(env, method, path, body, prefer, f = fetch) {
	const res = await f(`${env.url}/rest/v1/${path}`, {
		method,
		headers: {
			...keyHeaders(env.serviceKey),
			"Content-Type": "application/json",
			...prefer ? { Prefer: prefer } : {}
		},
		...body !== void 0 ? { body: JSON.stringify(body) } : {}
	});
	if (!res.ok) throw new Error(`${method} ${path.split("?")[0]}: ${res.status} ${(await res.text()).slice(0, 200)}`);
	const text = await res.text();
	return text ? JSON.parse(text) : null;
}
/** How many rows match a query (PostgREST's exact count, without the rows). */
async function count(env, path, f = fetch) {
	const res = await f(`${env.url}/rest/v1/${path}${path.includes("?") ? "&" : "?"}limit=1`, {
		method: "GET",
		headers: {
			...keyHeaders(env.serviceKey),
			Prefer: "count=exact"
		}
	});
	if (!res.ok) throw new Error(`count ${path.split("?")[0]}: ${res.status}`);
	const total = Number(res.headers.get("content-range")?.split("/")[1]);
	return Number.isFinite(total) ? total : 0;
}
const upsert = (env, table, rows, onConflict, f) => rows.length ? rest(env, "POST", `${table}?on_conflict=${onConflict}`, rows, "resolution=merge-duplicates,return=minimal", f) : Promise.resolve(null);
async function deleteUser(env, id, f = fetch) {
	const res = await f(`${env.url}/auth/v1/admin/users/${encodeURIComponent(id)}`, {
		method: "DELETE",
		headers: keyHeaders(env.serviceKey)
	});
	if (!res.ok) throw new Error(`delete user: ${res.status}`);
}
const json = (body, status = 200) => new Response(JSON.stringify(body), {
	status,
	headers: {
		"Content-Type": "application/json",
		"Cache-Control": "no-store"
	}
});
const bearer = (req) => req.headers.get("authorization")?.match(/^Bearer\s+(.+)$/i)?.[1] ?? null;
//#endregion
//#region server/honors.ts
const MIN_FIELD = {
	gm: 10,
	weekly: 3,
	daily: 3,
	pvp: 20,
	ranked: 20
};
const enc = encodeURIComponent;
async function computeHonors(env, userId, d, now, previous, f = fetch) {
	const honors = new Set(previous);
	const others = `user_id=neq.${userId}`;
	if (await count(env, `lb_users?select=id`, f) >= MIN_FIELD.gm) {
		const rank = await count(env, `lb_users?select=id&xp=gt.${d.profile.xp}&id=neq.${userId}`, f) + 1;
		if (rank === 1) honors.add("gm-1");
		if (rank <= 10) honors.add("gm-10");
		if (rank <= 100) honors.add("gm-100");
	}
	const today = now.toISOString().slice(0, 10), thisWeek = weekKey(now);
	for (const w of d.weekly.filter((x) => x.week < thisWeek).slice(-6)) {
		const q = `weekly_scores?select=user_id&board=eq.${enc(w.board)}&week=eq.${enc(w.week)}&${others}`;
		if (await count(env, q, f) + 1 >= MIN_FIELD.weekly && await count(env, `${q}&score=gt.${w.score}`, f) === 0) honors.add("weekly-1");
	}
	for (const day of d.daily.filter((x) => x.day < today).slice(-7)) {
		const q = `daily_legend?select=user_id&day=eq.${enc(day.day)}&${others}`;
		if (await count(env, q, f) + 1 >= MIN_FIELD.daily && await count(env, `${q}&score=gt.${day.score}`, f) === 0) honors.add("daily-1");
	}
	const season = seasonOf(today);
	const mine = d.ranked.filter((r) => r.season === season).reduce((n, r) => n + r.points, 0);
	if (mine > 0) {
		const q = `lb_ranked?select=user_id&season=eq.${enc(season)}&${others}`;
		if (await count(env, q, f) + 1 >= MIN_FIELD.ranked && await count(env, `${q}&points=gt.${mine}`, f) < 10) honors.add("ranked-10");
	}
	return [...honors].sort();
}
/** PvP is rated on the server (hunt_ghosts), so its honor is checked there after each result. */
async function pvpHonor(env, userId, rating, f = fetch) {
	const q = `hunt_ghosts?select=user_id&user_id=neq.${userId}`;
	return await count(env, q, f) + 1 >= MIN_FIELD.pvp && await count(env, `${q}&rating=gt.${rating}`, f) < 10;
}
const careerRows = (list) => list.filter((c) => typeof c.id === "string" && typeof c.updatedAt === "number");
async function handleSync(req, env, now = /* @__PURE__ */ new Date(), f = fetch) {
	if (!env) return json({ error: "Accounts are not set up on this site yet." }, 503);
	const token = bearer(req);
	const user = token ? await getUser(env, token, f).catch(() => null) : null;
	if (!user) return json({ error: "Please sign in again." }, 401);
	const id = user.id, eq = `user_id=eq.${id}`;
	try {
		if (req.method === "DELETE") {
			await deleteUser(env, id, f);
			return json({ ok: true });
		}
		if (req.method !== "POST") return json({ error: "Method not allowed." }, 405);
		const text = await req.text();
		if (text.length > 8e5) return json({ error: "Your progress is too large to sync." }, 413);
		let blob;
		try {
			blob = sanitizeBlob(JSON.parse(text));
		} catch {
			blob = null;
		}
		if (!blob) return json({ error: "Bad progress data." }, 400);
		const stored = (await rest(env, "GET", `progress?${eq}&select=data,updated_at`, void 0, void 0, f))?.[0];
		if (stored && now.getTime() - Date.parse(stored.updated_at) < 3e3) return json({
			error: "Syncing too often.",
			retry: true
		}, 429);
		const prev = stored ? sanitizeBlob(stored.data) : null;
		if (prev) blob = {
			...blob,
			storage: mergeStorage(blob.storage, prev.storage),
			careers: mergeCareers(careerRows(blob.careers), careerRows(prev.careers))
		};
		const size = JSON.stringify(blob).length;
		if (size > 8e5) return json({ error: "Your progress is too large to sync." }, 413);
		const d = derive(blob, now);
		const own = (rows) => rows.map((r) => ({
			...r,
			user_id: id
		}));
		await upsert(env, "progress", [{
			user_id: id,
			data: blob,
			size,
			updated_at: now.toISOString()
		}], "user_id", f);
		const current = (await rest(env, "GET", `profiles?id=eq.${id}&select=stats`, void 0, void 0, f))?.[0];
		const previous = Array.isArray(current?.stats?.honors) ? current.stats.honors.filter((h) => typeof h === "string") : [];
		let honors = previous;
		try {
			honors = await computeHonors(env, id, d, now, previous, f);
			const ghost = (await rest(env, "GET", `hunt_ghosts?${eq}&select=rating`, void 0, void 0, f))?.[0];
			if (ghost && !honors.includes("pvp-10") && await pvpHonor(env, id, ghost.rating, f)) honors = [...honors, "pvp-10"].sort();
		} catch {}
		await Promise.all([
			rest(env, "PATCH", `profiles?id=eq.${id}`, {
				level: d.profile.level,
				xp: d.profile.xp,
				stats: {
					...d.profile.stats,
					honors
				},
				updated_at: now.toISOString()
			}, "return=minimal", f),
			rest(env, "DELETE", `user_achievements?${eq}`, void 0, "return=minimal", f).then(() => upsert(env, "user_achievements", own(d.achievements.map((a) => ({ achievement_id: a }))), "user_id,achievement_id", f)),
			upsert(env, "created_players", own(d.players), "user_id,career_id", f),
			upsert(env, "weekly_scores", own(d.weekly.map((w) => ({
				...w,
				updated_at: now.toISOString()
			}))), "board,week,user_id", f),
			upsert(env, "daily_legend", own(d.daily), "day,user_id", f),
			upsert(env, "rebuild_records", own(d.rebuild), "scenario,user_id", f),
			upsert(env, "code_results", own(d.codes.map((c) => ({
				...c,
				updated_at: now.toISOString()
			}))), "code,user_id", f),
			upsert(env, "ranked_events", own(d.ranked), "user_id,event", f)
		]);
		return json({
			ok: true,
			level: d.profile.level,
			xp: d.profile.xp,
			honors
		});
	} catch {
		return json({ error: "Cloud sync is having trouble. Your progress is safe on this device; it will sync later." }, 502);
	}
}
//#endregion
//#region server/api-sync.ts
const POST = (request) => handleSync(request, supaEnv());
const DELETE = (request) => handleSync(request, supaEnv());
//#endregion
export { DELETE, POST };
